// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: pb/usercenter.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ==================== 通用响应结构 ====================
type JwtToken struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AccessToken   string                 `protobuf:"bytes,1,opt,name=accessToken,proto3" json:"accessToken,omitempty"`
	AccessExpire  int64                  `protobuf:"varint,2,opt,name=accessExpire,proto3" json:"accessExpire,omitempty"` // 过期时间戳
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JwtToken) Reset() {
	*x = JwtToken{}
	mi := &file_pb_usercenter_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JwtToken) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JwtToken) ProtoMessage() {}

func (x *JwtToken) ProtoReflect() protoreflect.Message {
	mi := &file_pb_usercenter_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JwtToken.ProtoReflect.Descriptor instead.
func (*JwtToken) Descriptor() ([]byte, []int) {
	return file_pb_usercenter_proto_rawDescGZIP(), []int{0}
}

func (x *JwtToken) GetAccessToken() string {
	if x != nil {
		return x.AccessToken
	}
	return ""
}

func (x *JwtToken) GetAccessExpire() int64 {
	if x != nil {
		return x.AccessExpire
	}
	return 0
}

// ==================== 用户信息 ====================
type UserInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uid           int64                  `protobuf:"varint,1,opt,name=uid,proto3" json:"uid,omitempty"`
	Nickname      string                 `protobuf:"bytes,2,opt,name=nickname,proto3" json:"nickname,omitempty"`
	Avatar        string                 `protobuf:"bytes,3,opt,name=avatar,proto3" json:"avatar,omitempty"`
	Bio           string                 `protobuf:"bytes,4,opt,name=bio,proto3" json:"bio,omitempty"`
	FollowCount   int64                  `protobuf:"varint,5,opt,name=follow_count,json=followCount,proto3" json:"follow_count,omitempty"`
	FansCount     int64                  `protobuf:"varint,6,opt,name=fans_count,json=fansCount,proto3" json:"fans_count,omitempty"`
	PostCount     int64                  `protobuf:"varint,7,opt,name=post_count,json=postCount,proto3" json:"post_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserInfo) Reset() {
	*x = UserInfo{}
	mi := &file_pb_usercenter_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserInfo) ProtoMessage() {}

func (x *UserInfo) ProtoReflect() protoreflect.Message {
	mi := &file_pb_usercenter_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserInfo.ProtoReflect.Descriptor instead.
func (*UserInfo) Descriptor() ([]byte, []int) {
	return file_pb_usercenter_proto_rawDescGZIP(), []int{1}
}

func (x *UserInfo) GetUid() int64 {
	if x != nil {
		return x.Uid
	}
	return 0
}

func (x *UserInfo) GetNickname() string {
	if x != nil {
		return x.Nickname
	}
	return ""
}

func (x *UserInfo) GetAvatar() string {
	if x != nil {
		return x.Avatar
	}
	return ""
}

func (x *UserInfo) GetBio() string {
	if x != nil {
		return x.Bio
	}
	return ""
}

func (x *UserInfo) GetFollowCount() int64 {
	if x != nil {
		return x.FollowCount
	}
	return 0
}

func (x *UserInfo) GetFansCount() int64 {
	if x != nil {
		return x.FansCount
	}
	return 0
}

func (x *UserInfo) GetPostCount() int64 {
	if x != nil {
		return x.PostCount
	}
	return 0
}

type UserBrief struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uid           int64                  `protobuf:"varint,1,opt,name=uid,proto3" json:"uid,omitempty"`
	Nickname      string                 `protobuf:"bytes,2,opt,name=nickname,proto3" json:"nickname,omitempty"`
	Avatar        string                 `protobuf:"bytes,3,opt,name=avatar,proto3" json:"avatar,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserBrief) Reset() {
	*x = UserBrief{}
	mi := &file_pb_usercenter_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserBrief) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserBrief) ProtoMessage() {}

func (x *UserBrief) ProtoReflect() protoreflect.Message {
	mi := &file_pb_usercenter_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserBrief.ProtoReflect.Descriptor instead.
func (*UserBrief) Descriptor() ([]byte, []int) {
	return file_pb_usercenter_proto_rawDescGZIP(), []int{2}
}

func (x *UserBrief) GetUid() int64 {
	if x != nil {
		return x.Uid
	}
	return 0
}

func (x *UserBrief) GetNickname() string {
	if x != nil {
		return x.Nickname
	}
	return ""
}

func (x *UserBrief) GetAvatar() string {
	if x != nil {
		return x.Avatar
	}
	return ""
}

// ==================== 注册登录 ====================
type RegisterReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Mobile        string                 `protobuf:"bytes,1,opt,name=mobile,proto3" json:"mobile,omitempty"`
	Password      string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterReq) Reset() {
	*x = RegisterReq{}
	mi := &file_pb_usercenter_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterReq) ProtoMessage() {}

func (x *RegisterReq) ProtoReflect() protoreflect.Message {
	mi := &file_pb_usercenter_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterReq.ProtoReflect.Descriptor instead.
func (*RegisterReq) Descriptor() ([]byte, []int) {
	return file_pb_usercenter_proto_rawDescGZIP(), []int{3}
}

func (x *RegisterReq) GetMobile() string {
	if x != nil {
		return x.Mobile
	}
	return ""
}

func (x *RegisterReq) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type RegisterResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int64                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Msg           string                 `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	UserInfo      *UserInfo              `protobuf:"bytes,3,opt,name=user_info,json=userInfo,proto3" json:"user_info,omitempty"`
	Token         *JwtToken              `protobuf:"bytes,4,opt,name=token,proto3" json:"token,omitempty"` // 注册后直接登录，返回token
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterResp) Reset() {
	*x = RegisterResp{}
	mi := &file_pb_usercenter_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterResp) ProtoMessage() {}

func (x *RegisterResp) ProtoReflect() protoreflect.Message {
	mi := &file_pb_usercenter_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterResp.ProtoReflect.Descriptor instead.
func (*RegisterResp) Descriptor() ([]byte, []int) {
	return file_pb_usercenter_proto_rawDescGZIP(), []int{4}
}

func (x *RegisterResp) GetCode() int64 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *RegisterResp) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

func (x *RegisterResp) GetUserInfo() *UserInfo {
	if x != nil {
		return x.UserInfo
	}
	return nil
}

func (x *RegisterResp) GetToken() *JwtToken {
	if x != nil {
		return x.Token
	}
	return nil
}

type LoginReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Mobile        string                 `protobuf:"bytes,1,opt,name=mobile,proto3" json:"mobile,omitempty"`
	Password      string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginReq) Reset() {
	*x = LoginReq{}
	mi := &file_pb_usercenter_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginReq) ProtoMessage() {}

func (x *LoginReq) ProtoReflect() protoreflect.Message {
	mi := &file_pb_usercenter_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginReq.ProtoReflect.Descriptor instead.
func (*LoginReq) Descriptor() ([]byte, []int) {
	return file_pb_usercenter_proto_rawDescGZIP(), []int{5}
}

func (x *LoginReq) GetMobile() string {
	if x != nil {
		return x.Mobile
	}
	return ""
}

func (x *LoginReq) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type LoginResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int64                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Msg           string                 `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	UserInfo      *UserInfo              `protobuf:"bytes,3,opt,name=user_info,json=userInfo,proto3" json:"user_info,omitempty"`
	Token         *JwtToken              `protobuf:"bytes,4,opt,name=token,proto3" json:"token,omitempty"` // 登录成功返回token
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginResp) Reset() {
	*x = LoginResp{}
	mi := &file_pb_usercenter_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginResp) ProtoMessage() {}

func (x *LoginResp) ProtoReflect() protoreflect.Message {
	mi := &file_pb_usercenter_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginResp.ProtoReflect.Descriptor instead.
func (*LoginResp) Descriptor() ([]byte, []int) {
	return file_pb_usercenter_proto_rawDescGZIP(), []int{6}
}

func (x *LoginResp) GetCode() int64 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *LoginResp) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

func (x *LoginResp) GetUserInfo() *UserInfo {
	if x != nil {
		return x.UserInfo
	}
	return nil
}

func (x *LoginResp) GetToken() *JwtToken {
	if x != nil {
		return x.Token
	}
	return nil
}

// ==================== 用户信息查询 ====================
type GetUserInfoReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uid           int64                  `protobuf:"varint,1,opt,name=uid,proto3" json:"uid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserInfoReq) Reset() {
	*x = GetUserInfoReq{}
	mi := &file_pb_usercenter_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserInfoReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserInfoReq) ProtoMessage() {}

func (x *GetUserInfoReq) ProtoReflect() protoreflect.Message {
	mi := &file_pb_usercenter_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserInfoReq.ProtoReflect.Descriptor instead.
func (*GetUserInfoReq) Descriptor() ([]byte, []int) {
	return file_pb_usercenter_proto_rawDescGZIP(), []int{7}
}

func (x *GetUserInfoReq) GetUid() int64 {
	if x != nil {
		return x.Uid
	}
	return 0
}

type GetUserInfoResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int64                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Msg           string                 `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	UserInfo      *UserInfo              `protobuf:"bytes,3,opt,name=user_info,json=userInfo,proto3" json:"user_info,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserInfoResp) Reset() {
	*x = GetUserInfoResp{}
	mi := &file_pb_usercenter_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserInfoResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserInfoResp) ProtoMessage() {}

func (x *GetUserInfoResp) ProtoReflect() protoreflect.Message {
	mi := &file_pb_usercenter_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserInfoResp.ProtoReflect.Descriptor instead.
func (*GetUserInfoResp) Descriptor() ([]byte, []int) {
	return file_pb_usercenter_proto_rawDescGZIP(), []int{8}
}

func (x *GetUserInfoResp) GetCode() int64 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *GetUserInfoResp) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

func (x *GetUserInfoResp) GetUserInfo() *UserInfo {
	if x != nil {
		return x.UserInfo
	}
	return nil
}

// ==========批量查询（给其它微服务返回评论区） ============
type BatchUserBriefReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uids          []int64                `protobuf:"varint,1,rep,packed,name=uids,proto3" json:"uids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatchUserBriefReq) Reset() {
	*x = BatchUserBriefReq{}
	mi := &file_pb_usercenter_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchUserBriefReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchUserBriefReq) ProtoMessage() {}

func (x *BatchUserBriefReq) ProtoReflect() protoreflect.Message {
	mi := &file_pb_usercenter_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchUserBriefReq.ProtoReflect.Descriptor instead.
func (*BatchUserBriefReq) Descriptor() ([]byte, []int) {
	return file_pb_usercenter_proto_rawDescGZIP(), []int{9}
}

func (x *BatchUserBriefReq) GetUids() []int64 {
	if x != nil {
		return x.Uids
	}
	return nil
}

type BatchUserBriefResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int64                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Msg           string                 `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	Users         []*UserBrief           `protobuf:"bytes,3,rep,name=users,proto3" json:"users,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatchUserBriefResp) Reset() {
	*x = BatchUserBriefResp{}
	mi := &file_pb_usercenter_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchUserBriefResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchUserBriefResp) ProtoMessage() {}

func (x *BatchUserBriefResp) ProtoReflect() protoreflect.Message {
	mi := &file_pb_usercenter_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchUserBriefResp.ProtoReflect.Descriptor instead.
func (*BatchUserBriefResp) Descriptor() ([]byte, []int) {
	return file_pb_usercenter_proto_rawDescGZIP(), []int{10}
}

func (x *BatchUserBriefResp) GetCode() int64 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *BatchUserBriefResp) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

func (x *BatchUserBriefResp) GetUsers() []*UserBrief {
	if x != nil {
		return x.Users
	}
	return nil
}

// ==================== 更新用户统计 ====================
type UpdateUserStatsReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uid           int64                  `protobuf:"varint,1,opt,name=uid,proto3" json:"uid,omitempty"`
	UpdateType    int64                  `protobuf:"varint,2,opt,name=update_type,json=updateType,proto3" json:"update_type,omitempty"` // 1=follow_count, 2=fans_count, 3=post_count
	Delta         int64                  `protobuf:"varint,3,opt,name=delta,proto3" json:"delta,omitempty"`                             // +1 或 -1
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateUserStatsReq) Reset() {
	*x = UpdateUserStatsReq{}
	mi := &file_pb_usercenter_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateUserStatsReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateUserStatsReq) ProtoMessage() {}

func (x *UpdateUserStatsReq) ProtoReflect() protoreflect.Message {
	mi := &file_pb_usercenter_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateUserStatsReq.ProtoReflect.Descriptor instead.
func (*UpdateUserStatsReq) Descriptor() ([]byte, []int) {
	return file_pb_usercenter_proto_rawDescGZIP(), []int{11}
}

func (x *UpdateUserStatsReq) GetUid() int64 {
	if x != nil {
		return x.Uid
	}
	return 0
}

func (x *UpdateUserStatsReq) GetUpdateType() int64 {
	if x != nil {
		return x.UpdateType
	}
	return 0
}

func (x *UpdateUserStatsReq) GetDelta() int64 {
	if x != nil {
		return x.Delta
	}
	return 0
}

type UpdateUserStatsResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int64                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Msg           string                 `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateUserStatsResp) Reset() {
	*x = UpdateUserStatsResp{}
	mi := &file_pb_usercenter_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateUserStatsResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateUserStatsResp) ProtoMessage() {}

func (x *UpdateUserStatsResp) ProtoReflect() protoreflect.Message {
	mi := &file_pb_usercenter_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateUserStatsResp.ProtoReflect.Descriptor instead.
func (*UpdateUserStatsResp) Descriptor() ([]byte, []int) {
	return file_pb_usercenter_proto_rawDescGZIP(), []int{12}
}

func (x *UpdateUserStatsResp) GetCode() int64 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *UpdateUserStatsResp) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

var File_pb_usercenter_proto protoreflect.FileDescriptor

const file_pb_usercenter_proto_rawDesc = "" +
	"\n" +
	"\x13pb/usercenter.proto\x12\x02pb\"P\n" +
	"\bJwtToken\x12 \n" +
	"\vaccessToken\x18\x01 \x01(\tR\vaccessToken\x12\"\n" +
	"\faccessExpire\x18\x02 \x01(\x03R\faccessExpire\"\xc3\x01\n" +
	"\bUserInfo\x12\x10\n" +
	"\x03uid\x18\x01 \x01(\x03R\x03uid\x12\x1a\n" +
	"\bnickname\x18\x02 \x01(\tR\bnickname\x12\x16\n" +
	"\x06avatar\x18\x03 \x01(\tR\x06avatar\x12\x10\n" +
	"\x03bio\x18\x04 \x01(\tR\x03bio\x12!\n" +
	"\ffollow_count\x18\x05 \x01(\x03R\vfollowCount\x12\x1d\n" +
	"\n" +
	"fans_count\x18\x06 \x01(\x03R\tfansCount\x12\x1d\n" +
	"\n" +
	"post_count\x18\a \x01(\x03R\tpostCount\"Q\n" +
	"\tUserBrief\x12\x10\n" +
	"\x03uid\x18\x01 \x01(\x03R\x03uid\x12\x1a\n" +
	"\bnickname\x18\x02 \x01(\tR\bnickname\x12\x16\n" +
	"\x06avatar\x18\x03 \x01(\tR\x06avatar\"A\n" +
	"\vRegisterReq\x12\x16\n" +
	"\x06mobile\x18\x01 \x01(\tR\x06mobile\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\"\x83\x01\n" +
	"\fRegisterResp\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x03R\x04code\x12\x10\n" +
	"\x03msg\x18\x02 \x01(\tR\x03msg\x12)\n" +
	"\tuser_info\x18\x03 \x01(\v2\f.pb.UserInfoR\buserInfo\x12\"\n" +
	"\x05token\x18\x04 \x01(\v2\f.pb.JwtTokenR\x05token\">\n" +
	"\bLoginReq\x12\x16\n" +
	"\x06mobile\x18\x01 \x01(\tR\x06mobile\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\"\x80\x01\n" +
	"\tLoginResp\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x03R\x04code\x12\x10\n" +
	"\x03msg\x18\x02 \x01(\tR\x03msg\x12)\n" +
	"\tuser_info\x18\x03 \x01(\v2\f.pb.UserInfoR\buserInfo\x12\"\n" +
	"\x05token\x18\x04 \x01(\v2\f.pb.JwtTokenR\x05token\"\"\n" +
	"\x0eGetUserInfoReq\x12\x10\n" +
	"\x03uid\x18\x01 \x01(\x03R\x03uid\"b\n" +
	"\x0fGetUserInfoResp\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x03R\x04code\x12\x10\n" +
	"\x03msg\x18\x02 \x01(\tR\x03msg\x12)\n" +
	"\tuser_info\x18\x03 \x01(\v2\f.pb.UserInfoR\buserInfo\"'\n" +
	"\x11BatchUserBriefReq\x12\x12\n" +
	"\x04uids\x18\x01 \x03(\x03R\x04uids\"_\n" +
	"\x12BatchUserBriefResp\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x03R\x04code\x12\x10\n" +
	"\x03msg\x18\x02 \x01(\tR\x03msg\x12#\n" +
	"\x05users\x18\x03 \x03(\v2\r.pb.UserBriefR\x05users\"]\n" +
	"\x12UpdateUserStatsReq\x12\x10\n" +
	"\x03uid\x18\x01 \x01(\x03R\x03uid\x12\x1f\n" +
	"\vupdate_type\x18\x02 \x01(\x03R\n" +
	"updateType\x12\x14\n" +
	"\x05delta\x18\x03 \x01(\x03R\x05delta\";\n" +
	"\x13UpdateUserStatsResp\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x03R\x04code\x12\x10\n" +
	"\x03msg\x18\x02 \x01(\tR\x03msg2\xa1\x02\n" +
	"\n" +
	"UserCenter\x12-\n" +
	"\bRegister\x12\x0f.pb.RegisterReq\x1a\x10.pb.RegisterResp\x12$\n" +
	"\x05Login\x12\f.pb.LoginReq\x1a\r.pb.LoginResp\x126\n" +
	"\vGetUserInfo\x12\x12.pb.GetUserInfoReq\x1a\x13.pb.GetUserInfoResp\x12B\n" +
	"\x11BatchGetUserBrief\x12\x15.pb.BatchUserBriefReq\x1a\x16.pb.BatchUserBriefResp\x12B\n" +
	"\x0fUpdateUserStats\x12\x16.pb.UpdateUserStatsReq\x1a\x17.pb.UpdateUserStatsRespB\x06Z\x04./pbb\x06proto3"

var (
	file_pb_usercenter_proto_rawDescOnce sync.Once
	file_pb_usercenter_proto_rawDescData []byte
)

func file_pb_usercenter_proto_rawDescGZIP() []byte {
	file_pb_usercenter_proto_rawDescOnce.Do(func() {
		file_pb_usercenter_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pb_usercenter_proto_rawDesc), len(file_pb_usercenter_proto_rawDesc)))
	})
	return file_pb_usercenter_proto_rawDescData
}

var file_pb_usercenter_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_pb_usercenter_proto_goTypes = []any{
	(*JwtToken)(nil),            // 0: pb.JwtToken
	(*UserInfo)(nil),            // 1: pb.UserInfo
	(*UserBrief)(nil),           // 2: pb.UserBrief
	(*RegisterReq)(nil),         // 3: pb.RegisterReq
	(*RegisterResp)(nil),        // 4: pb.RegisterResp
	(*LoginReq)(nil),            // 5: pb.LoginReq
	(*LoginResp)(nil),           // 6: pb.LoginResp
	(*GetUserInfoReq)(nil),      // 7: pb.GetUserInfoReq
	(*GetUserInfoResp)(nil),     // 8: pb.GetUserInfoResp
	(*BatchUserBriefReq)(nil),   // 9: pb.BatchUserBriefReq
	(*BatchUserBriefResp)(nil),  // 10: pb.BatchUserBriefResp
	(*UpdateUserStatsReq)(nil),  // 11: pb.UpdateUserStatsReq
	(*UpdateUserStatsResp)(nil), // 12: pb.UpdateUserStatsResp
}
var file_pb_usercenter_proto_depIdxs = []int32{
	1,  // 0: pb.RegisterResp.user_info:type_name -> pb.UserInfo
	0,  // 1: pb.RegisterResp.token:type_name -> pb.JwtToken
	1,  // 2: pb.LoginResp.user_info:type_name -> pb.UserInfo
	0,  // 3: pb.LoginResp.token:type_name -> pb.JwtToken
	1,  // 4: pb.GetUserInfoResp.user_info:type_name -> pb.UserInfo
	2,  // 5: pb.BatchUserBriefResp.users:type_name -> pb.UserBrief
	3,  // 6: pb.UserCenter.Register:input_type -> pb.RegisterReq
	5,  // 7: pb.UserCenter.Login:input_type -> pb.LoginReq
	7,  // 8: pb.UserCenter.GetUserInfo:input_type -> pb.GetUserInfoReq
	9,  // 9: pb.UserCenter.BatchGetUserBrief:input_type -> pb.BatchUserBriefReq
	11, // 10: pb.UserCenter.UpdateUserStats:input_type -> pb.UpdateUserStatsReq
	4,  // 11: pb.UserCenter.Register:output_type -> pb.RegisterResp
	6,  // 12: pb.UserCenter.Login:output_type -> pb.LoginResp
	8,  // 13: pb.UserCenter.GetUserInfo:output_type -> pb.GetUserInfoResp
	10, // 14: pb.UserCenter.BatchGetUserBrief:output_type -> pb.BatchUserBriefResp
	12, // 15: pb.UserCenter.UpdateUserStats:output_type -> pb.UpdateUserStatsResp
	11, // [11:16] is the sub-list for method output_type
	6,  // [6:11] is the sub-list for method input_type
	6,  // [6:6] is the sub-list for extension type_name
	6,  // [6:6] is the sub-list for extension extendee
	0,  // [0:6] is the sub-list for field type_name
}

func init() { file_pb_usercenter_proto_init() }
func file_pb_usercenter_proto_init() {
	if File_pb_usercenter_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pb_usercenter_proto_rawDesc), len(file_pb_usercenter_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pb_usercenter_proto_goTypes,
		DependencyIndexes: file_pb_usercenter_proto_depIdxs,
		MessageInfos:      file_pb_usercenter_proto_msgTypes,
	}.Build()
	File_pb_usercenter_proto = out.File
	file_pb_usercenter_proto_goTypes = nil
	file_pb_usercenter_proto_depIdxs = nil
}
