// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1

package handler

import (
	"gozeroX/pkg/jwt"
	"net/http"

	interaction "gozeroX/app/interactService/cmd/api/internal/handler/interaction"
	"gozeroX/app/interactService/cmd/api/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	jwtMiddleware := jwt.NewJwtMiddleware(serverCtx.Config.JwtAuth.AccessSecret)
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/createComment",
				Handler: jwtMiddleware.Handle(interaction.CreateCommentHandler(serverCtx)),
			},
			{
				Method:  http.MethodDelete,
				Path:    "/deleteComment",
				Handler: jwtMiddleware.Handle(interaction.DeleteCommentHandler(serverCtx)),
			},
			{
				Method:  http.MethodGet,
				Path:    "/getComments",
				Handler: jwtMiddleware.Handle(interaction.GetCommentsHandler(serverCtx)),
			},
			{
				Method:  http.MethodGet,
				Path:    "/getReplies",
				Handler: jwtMiddleware.Handle(interaction.GetRepliesHandler(serverCtx)),
			},
			{
				Method:  http.MethodGet,
				Path:    "/getUserLikesAll",
				Handler: jwtMiddleware.Handle(interaction.GetUserLikesAllHandler(serverCtx)),
			},
			{
				Method:  http.MethodGet,
				Path:    "/like",
				Handler: jwtMiddleware.Handle(interaction.LikeHandler(serverCtx)),
			},
		},
		rest.WithPrefix("/interactService/v1"),
	)
}
