// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.31.0
// source: pb/interactService.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PageReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Page          int64                  `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int64                  `protobuf:"varint,2,opt,name=pageSize,proto3" json:"pageSize,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PageReq) Reset() {
	*x = PageReq{}
	mi := &file_pb_interactService_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PageReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PageReq) ProtoMessage() {}

func (x *PageReq) ProtoReflect() protoreflect.Message {
	mi := &file_pb_interactService_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PageReq.ProtoReflect.Descriptor instead.
func (*PageReq) Descriptor() ([]byte, []int) {
	return file_pb_interactService_proto_rawDescGZIP(), []int{0}
}

func (x *PageReq) GetPage() int64 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *PageReq) GetPageSize() int64 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

type PageResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Total         int64                  `protobuf:"varint,1,opt,name=total,proto3" json:"total,omitempty"`
	Page          int64                  `protobuf:"varint,2,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int64                  `protobuf:"varint,3,opt,name=pageSize,proto3" json:"pageSize,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PageResp) Reset() {
	*x = PageResp{}
	mi := &file_pb_interactService_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PageResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PageResp) ProtoMessage() {}

func (x *PageResp) ProtoReflect() protoreflect.Message {
	mi := &file_pb_interactService_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PageResp.ProtoReflect.Descriptor instead.
func (*PageResp) Descriptor() ([]byte, []int) {
	return file_pb_interactService_proto_rawDescGZIP(), []int{1}
}

func (x *PageResp) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *PageResp) GetPage() int64 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *PageResp) GetPageSize() int64 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

// 评论基础信息
type CommentInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Cid           int64                  `protobuf:"varint,1,opt,name=cid,proto3" json:"cid,omitempty"`
	Tid           int64                  `protobuf:"varint,2,opt,name=tid,proto3" json:"tid,omitempty"`
	Uid           int64                  `protobuf:"varint,3,opt,name=uid,proto3" json:"uid,omitempty"`
	ParentId      int64                  `protobuf:"varint,4,opt,name=parentId,proto3" json:"parentId,omitempty"`
	RootId        int64                  `protobuf:"varint,5,opt,name=rootId,proto3" json:"rootId,omitempty"`
	Content       string                 `protobuf:"bytes,6,opt,name=content,proto3" json:"content,omitempty"`
	LikeCount     int64                  `protobuf:"varint,7,opt,name=likeCount,proto3" json:"likeCount,omitempty"`   // 点赞总数
	ReplyCount    int64                  `protobuf:"varint,8,opt,name=replyCount,proto3" json:"replyCount,omitempty"` // 回复总数
	Status        int32                  `protobuf:"varint,9,opt,name=status,proto3" json:"status,omitempty"`         // 0-正常 1-删除 2-审核中
	CreateTime    string                 `protobuf:"bytes,10,opt,name=createTime,proto3" json:"createTime,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CommentInfo) Reset() {
	*x = CommentInfo{}
	mi := &file_pb_interactService_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommentInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommentInfo) ProtoMessage() {}

func (x *CommentInfo) ProtoReflect() protoreflect.Message {
	mi := &file_pb_interactService_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommentInfo.ProtoReflect.Descriptor instead.
func (*CommentInfo) Descriptor() ([]byte, []int) {
	return file_pb_interactService_proto_rawDescGZIP(), []int{2}
}

func (x *CommentInfo) GetCid() int64 {
	if x != nil {
		return x.Cid
	}
	return 0
}

func (x *CommentInfo) GetTid() int64 {
	if x != nil {
		return x.Tid
	}
	return 0
}

func (x *CommentInfo) GetUid() int64 {
	if x != nil {
		return x.Uid
	}
	return 0
}

func (x *CommentInfo) GetParentId() int64 {
	if x != nil {
		return x.ParentId
	}
	return 0
}

func (x *CommentInfo) GetRootId() int64 {
	if x != nil {
		return x.RootId
	}
	return 0
}

func (x *CommentInfo) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *CommentInfo) GetLikeCount() int64 {
	if x != nil {
		return x.LikeCount
	}
	return 0
}

func (x *CommentInfo) GetReplyCount() int64 {
	if x != nil {
		return x.ReplyCount
	}
	return 0
}

func (x *CommentInfo) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *CommentInfo) GetCreateTime() string {
	if x != nil {
		return x.CreateTime
	}
	return ""
}

// 创建评论
type CreateCommentReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tid           int64                  `protobuf:"varint,1,opt,name=tid,proto3" json:"tid,omitempty"`
	Uid           int64                  `protobuf:"varint,2,opt,name=uid,proto3" json:"uid,omitempty"`
	Content       string                 `protobuf:"bytes,3,opt,name=content,proto3" json:"content,omitempty"`
	ParentId      int64                  `protobuf:"varint,4,opt,name=parentId,proto3" json:"parentId,omitempty"` // 0表示顶级评论
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateCommentReq) Reset() {
	*x = CreateCommentReq{}
	mi := &file_pb_interactService_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateCommentReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateCommentReq) ProtoMessage() {}

func (x *CreateCommentReq) ProtoReflect() protoreflect.Message {
	mi := &file_pb_interactService_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateCommentReq.ProtoReflect.Descriptor instead.
func (*CreateCommentReq) Descriptor() ([]byte, []int) {
	return file_pb_interactService_proto_rawDescGZIP(), []int{3}
}

func (x *CreateCommentReq) GetTid() int64 {
	if x != nil {
		return x.Tid
	}
	return 0
}

func (x *CreateCommentReq) GetUid() int64 {
	if x != nil {
		return x.Uid
	}
	return 0
}

func (x *CreateCommentReq) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *CreateCommentReq) GetParentId() int64 {
	if x != nil {
		return x.ParentId
	}
	return 0
}

type CreateCommentResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Comment       *CommentInfo           `protobuf:"bytes,1,opt,name=comment,proto3" json:"comment,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateCommentResp) Reset() {
	*x = CreateCommentResp{}
	mi := &file_pb_interactService_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateCommentResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateCommentResp) ProtoMessage() {}

func (x *CreateCommentResp) ProtoReflect() protoreflect.Message {
	mi := &file_pb_interactService_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateCommentResp.ProtoReflect.Descriptor instead.
func (*CreateCommentResp) Descriptor() ([]byte, []int) {
	return file_pb_interactService_proto_rawDescGZIP(), []int{4}
}

func (x *CreateCommentResp) GetComment() *CommentInfo {
	if x != nil {
		return x.Comment
	}
	return nil
}

// 删除评论
type DeleteCommentReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Cid           int64                  `protobuf:"varint,1,opt,name=cid,proto3" json:"cid,omitempty"`
	Uid           int64                  `protobuf:"varint,2,opt,name=uid,proto3" json:"uid,omitempty"` // 操作用户ID，用于权限校验
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteCommentReq) Reset() {
	*x = DeleteCommentReq{}
	mi := &file_pb_interactService_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteCommentReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteCommentReq) ProtoMessage() {}

func (x *DeleteCommentReq) ProtoReflect() protoreflect.Message {
	mi := &file_pb_interactService_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteCommentReq.ProtoReflect.Descriptor instead.
func (*DeleteCommentReq) Descriptor() ([]byte, []int) {
	return file_pb_interactService_proto_rawDescGZIP(), []int{5}
}

func (x *DeleteCommentReq) GetCid() int64 {
	if x != nil {
		return x.Cid
	}
	return 0
}

func (x *DeleteCommentReq) GetUid() int64 {
	if x != nil {
		return x.Uid
	}
	return 0
}

type DeleteCommentResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"` // 是否删除成功
	Cid           int64                  `protobuf:"varint,2,opt,name=cid,proto3" json:"cid,omitempty"`         // 被删除的评论ID
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteCommentResp) Reset() {
	*x = DeleteCommentResp{}
	mi := &file_pb_interactService_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteCommentResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteCommentResp) ProtoMessage() {}

func (x *DeleteCommentResp) ProtoReflect() protoreflect.Message {
	mi := &file_pb_interactService_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteCommentResp.ProtoReflect.Descriptor instead.
func (*DeleteCommentResp) Descriptor() ([]byte, []int) {
	return file_pb_interactService_proto_rawDescGZIP(), []int{6}
}

func (x *DeleteCommentResp) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *DeleteCommentResp) GetCid() int64 {
	if x != nil {
		return x.Cid
	}
	return 0
}

// 获取评论列表
type GetCommentsReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tid           int64                  `protobuf:"varint,1,opt,name=tid,proto3" json:"tid,omitempty"`
	Page          int64                  `protobuf:"varint,2,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int64                  `protobuf:"varint,3,opt,name=pageSize,proto3" json:"pageSize,omitempty"`
	Sort          string                 `protobuf:"bytes,4,opt,name=sort,proto3" json:"sort,omitempty"` // hot-热门 new-最新
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCommentsReq) Reset() {
	*x = GetCommentsReq{}
	mi := &file_pb_interactService_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCommentsReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCommentsReq) ProtoMessage() {}

func (x *GetCommentsReq) ProtoReflect() protoreflect.Message {
	mi := &file_pb_interactService_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCommentsReq.ProtoReflect.Descriptor instead.
func (*GetCommentsReq) Descriptor() ([]byte, []int) {
	return file_pb_interactService_proto_rawDescGZIP(), []int{7}
}

func (x *GetCommentsReq) GetTid() int64 {
	if x != nil {
		return x.Tid
	}
	return 0
}

func (x *GetCommentsReq) GetPage() int64 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *GetCommentsReq) GetPageSize() int64 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *GetCommentsReq) GetSort() string {
	if x != nil {
		return x.Sort
	}
	return ""
}

type GetCommentsResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Comments      []*CommentInfo         `protobuf:"bytes,1,rep,name=comments,proto3" json:"comments,omitempty"`
	Total         int64                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCommentsResp) Reset() {
	*x = GetCommentsResp{}
	mi := &file_pb_interactService_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCommentsResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCommentsResp) ProtoMessage() {}

func (x *GetCommentsResp) ProtoReflect() protoreflect.Message {
	mi := &file_pb_interactService_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCommentsResp.ProtoReflect.Descriptor instead.
func (*GetCommentsResp) Descriptor() ([]byte, []int) {
	return file_pb_interactService_proto_rawDescGZIP(), []int{8}
}

func (x *GetCommentsResp) GetComments() []*CommentInfo {
	if x != nil {
		return x.Comments
	}
	return nil
}

func (x *GetCommentsResp) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

// 获取评论回复列表
type GetRepliesReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Cid           int64                  `protobuf:"varint,1,opt,name=cid,proto3" json:"cid,omitempty"` // 父评论ID
	Page          int64                  `protobuf:"varint,2,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int64                  `protobuf:"varint,3,opt,name=pageSize,proto3" json:"pageSize,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRepliesReq) Reset() {
	*x = GetRepliesReq{}
	mi := &file_pb_interactService_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRepliesReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRepliesReq) ProtoMessage() {}

func (x *GetRepliesReq) ProtoReflect() protoreflect.Message {
	mi := &file_pb_interactService_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRepliesReq.ProtoReflect.Descriptor instead.
func (*GetRepliesReq) Descriptor() ([]byte, []int) {
	return file_pb_interactService_proto_rawDescGZIP(), []int{9}
}

func (x *GetRepliesReq) GetCid() int64 {
	if x != nil {
		return x.Cid
	}
	return 0
}

func (x *GetRepliesReq) GetPage() int64 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *GetRepliesReq) GetPageSize() int64 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

type GetRepliesResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Replies       []*CommentInfo         `protobuf:"bytes,1,rep,name=replies,proto3" json:"replies,omitempty"`
	Total         int64                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRepliesResp) Reset() {
	*x = GetRepliesResp{}
	mi := &file_pb_interactService_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRepliesResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRepliesResp) ProtoMessage() {}

func (x *GetRepliesResp) ProtoReflect() protoreflect.Message {
	mi := &file_pb_interactService_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRepliesResp.ProtoReflect.Descriptor instead.
func (*GetRepliesResp) Descriptor() ([]byte, []int) {
	return file_pb_interactService_proto_rawDescGZIP(), []int{10}
}

func (x *GetRepliesResp) GetReplies() []*CommentInfo {
	if x != nil {
		return x.Replies
	}
	return nil
}

func (x *GetRepliesResp) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

// 点赞记录信息（内部使用）
type LikeInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	LikesId       int64                  `protobuf:"varint,1,opt,name=likesId,proto3" json:"likesId,omitempty"`
	Uid           int64                  `protobuf:"varint,2,opt,name=uid,proto3" json:"uid,omitempty"`
	TargetType    int32                  `protobuf:"varint,3,opt,name=targetType,proto3" json:"targetType,omitempty"` // 1-内容 2-评论
	TargetId      int64                  `protobuf:"varint,4,opt,name=targetId,proto3" json:"targetId,omitempty"`
	Status        int32                  `protobuf:"varint,5,opt,name=status,proto3" json:"status,omitempty"` // 1-点赞 0-取消
	CreateTime    string                 `protobuf:"bytes,6,opt,name=createTime,proto3" json:"createTime,omitempty"`
	UpdateTime    string                 `protobuf:"bytes,7,opt,name=updateTime,proto3" json:"updateTime,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LikeInfo) Reset() {
	*x = LikeInfo{}
	mi := &file_pb_interactService_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LikeInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LikeInfo) ProtoMessage() {}

func (x *LikeInfo) ProtoReflect() protoreflect.Message {
	mi := &file_pb_interactService_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LikeInfo.ProtoReflect.Descriptor instead.
func (*LikeInfo) Descriptor() ([]byte, []int) {
	return file_pb_interactService_proto_rawDescGZIP(), []int{11}
}

func (x *LikeInfo) GetLikesId() int64 {
	if x != nil {
		return x.LikesId
	}
	return 0
}

func (x *LikeInfo) GetUid() int64 {
	if x != nil {
		return x.Uid
	}
	return 0
}

func (x *LikeInfo) GetTargetType() int32 {
	if x != nil {
		return x.TargetType
	}
	return 0
}

func (x *LikeInfo) GetTargetId() int64 {
	if x != nil {
		return x.TargetId
	}
	return 0
}

func (x *LikeInfo) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *LikeInfo) GetCreateTime() string {
	if x != nil {
		return x.CreateTime
	}
	return ""
}

func (x *LikeInfo) GetUpdateTime() string {
	if x != nil {
		return x.UpdateTime
	}
	return ""
}

// 点赞/取消点赞
type LikeReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uid           int64                  `protobuf:"varint,1,opt,name=uid,proto3" json:"uid,omitempty"`
	TargetType    int32                  `protobuf:"varint,2,opt,name=targetType,proto3" json:"targetType,omitempty"`
	TargetId      int64                  `protobuf:"varint,3,opt,name=targetId,proto3" json:"targetId,omitempty"`
	Action        int32                  `protobuf:"varint,4,opt,name=action,proto3" json:"action,omitempty"` // 1-点赞 0-取消
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LikeReq) Reset() {
	*x = LikeReq{}
	mi := &file_pb_interactService_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LikeReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LikeReq) ProtoMessage() {}

func (x *LikeReq) ProtoReflect() protoreflect.Message {
	mi := &file_pb_interactService_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LikeReq.ProtoReflect.Descriptor instead.
func (*LikeReq) Descriptor() ([]byte, []int) {
	return file_pb_interactService_proto_rawDescGZIP(), []int{12}
}

func (x *LikeReq) GetUid() int64 {
	if x != nil {
		return x.Uid
	}
	return 0
}

func (x *LikeReq) GetTargetType() int32 {
	if x != nil {
		return x.TargetType
	}
	return 0
}

func (x *LikeReq) GetTargetId() int64 {
	if x != nil {
		return x.TargetId
	}
	return 0
}

func (x *LikeReq) GetAction() int32 {
	if x != nil {
		return x.Action
	}
	return 0
}

type LikeResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IsLiked       bool                   `protobuf:"varint,1,opt,name=isLiked,proto3" json:"isLiked,omitempty"` // 当前是否点赞（操作后的状态）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LikeResp) Reset() {
	*x = LikeResp{}
	mi := &file_pb_interactService_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LikeResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LikeResp) ProtoMessage() {}

func (x *LikeResp) ProtoReflect() protoreflect.Message {
	mi := &file_pb_interactService_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LikeResp.ProtoReflect.Descriptor instead.
func (*LikeResp) Descriptor() ([]byte, []int) {
	return file_pb_interactService_proto_rawDescGZIP(), []int{13}
}

func (x *LikeResp) GetIsLiked() bool {
	if x != nil {
		return x.IsLiked
	}
	return false
}

// 获取单个点赞状态
type GetLikeStatusReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uid           int64                  `protobuf:"varint,1,opt,name=uid,proto3" json:"uid,omitempty"`
	TargetType    int32                  `protobuf:"varint,2,opt,name=targetType,proto3" json:"targetType,omitempty"`
	TargetId      int64                  `protobuf:"varint,3,opt,name=targetId,proto3" json:"targetId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetLikeStatusReq) Reset() {
	*x = GetLikeStatusReq{}
	mi := &file_pb_interactService_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetLikeStatusReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLikeStatusReq) ProtoMessage() {}

func (x *GetLikeStatusReq) ProtoReflect() protoreflect.Message {
	mi := &file_pb_interactService_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLikeStatusReq.ProtoReflect.Descriptor instead.
func (*GetLikeStatusReq) Descriptor() ([]byte, []int) {
	return file_pb_interactService_proto_rawDescGZIP(), []int{14}
}

func (x *GetLikeStatusReq) GetUid() int64 {
	if x != nil {
		return x.Uid
	}
	return 0
}

func (x *GetLikeStatusReq) GetTargetType() int32 {
	if x != nil {
		return x.TargetType
	}
	return 0
}

func (x *GetLikeStatusReq) GetTargetId() int64 {
	if x != nil {
		return x.TargetId
	}
	return 0
}

type GetLikeStatusResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IsLiked       bool                   `protobuf:"varint,1,opt,name=isLiked,proto3" json:"isLiked,omitempty"` // 只返回是否点赞，likeCount从资源本身获取
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetLikeStatusResp) Reset() {
	*x = GetLikeStatusResp{}
	mi := &file_pb_interactService_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetLikeStatusResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLikeStatusResp) ProtoMessage() {}

func (x *GetLikeStatusResp) ProtoReflect() protoreflect.Message {
	mi := &file_pb_interactService_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLikeStatusResp.ProtoReflect.Descriptor instead.
func (*GetLikeStatusResp) Descriptor() ([]byte, []int) {
	return file_pb_interactService_proto_rawDescGZIP(), []int{15}
}

func (x *GetLikeStatusResp) GetIsLiked() bool {
	if x != nil {
		return x.IsLiked
	}
	return false
}

// 批量获取点赞状态
type BatchGetLikeStatusReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uid           int64                  `protobuf:"varint,1,opt,name=uid,proto3" json:"uid,omitempty"`
	TargetType    int32                  `protobuf:"varint,2,opt,name=targetType,proto3" json:"targetType,omitempty"`
	TargetIds     []int64                `protobuf:"varint,3,rep,packed,name=targetIds,proto3" json:"targetIds,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatchGetLikeStatusReq) Reset() {
	*x = BatchGetLikeStatusReq{}
	mi := &file_pb_interactService_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchGetLikeStatusReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchGetLikeStatusReq) ProtoMessage() {}

func (x *BatchGetLikeStatusReq) ProtoReflect() protoreflect.Message {
	mi := &file_pb_interactService_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchGetLikeStatusReq.ProtoReflect.Descriptor instead.
func (*BatchGetLikeStatusReq) Descriptor() ([]byte, []int) {
	return file_pb_interactService_proto_rawDescGZIP(), []int{16}
}

func (x *BatchGetLikeStatusReq) GetUid() int64 {
	if x != nil {
		return x.Uid
	}
	return 0
}

func (x *BatchGetLikeStatusReq) GetTargetType() int32 {
	if x != nil {
		return x.TargetType
	}
	return 0
}

func (x *BatchGetLikeStatusReq) GetTargetIds() []int64 {
	if x != nil {
		return x.TargetIds
	}
	return nil
}

type BatchGetLikeStatusResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IsLiked       map[int64]bool         `protobuf:"bytes,1,rep,name=isLiked,proto3" json:"isLiked,omitempty" protobuf_key:"varint,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"` // targetId -> isLiked
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatchGetLikeStatusResp) Reset() {
	*x = BatchGetLikeStatusResp{}
	mi := &file_pb_interactService_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchGetLikeStatusResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchGetLikeStatusResp) ProtoMessage() {}

func (x *BatchGetLikeStatusResp) ProtoReflect() protoreflect.Message {
	mi := &file_pb_interactService_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchGetLikeStatusResp.ProtoReflect.Descriptor instead.
func (*BatchGetLikeStatusResp) Descriptor() ([]byte, []int) {
	return file_pb_interactService_proto_rawDescGZIP(), []int{17}
}

func (x *BatchGetLikeStatusResp) GetIsLiked() map[int64]bool {
	if x != nil {
		return x.IsLiked
	}
	return nil
}

var File_pb_interactService_proto protoreflect.FileDescriptor

const file_pb_interactService_proto_rawDesc = "" +
	"\n" +
	"\x18pb/interactService.proto\x12\x02pb\"9\n" +
	"\aPageReq\x12\x12\n" +
	"\x04page\x18\x01 \x01(\x03R\x04page\x12\x1a\n" +
	"\bpageSize\x18\x02 \x01(\x03R\bpageSize\"P\n" +
	"\bPageResp\x12\x14\n" +
	"\x05total\x18\x01 \x01(\x03R\x05total\x12\x12\n" +
	"\x04page\x18\x02 \x01(\x03R\x04page\x12\x1a\n" +
	"\bpageSize\x18\x03 \x01(\x03R\bpageSize\"\x87\x02\n" +
	"\vCommentInfo\x12\x10\n" +
	"\x03cid\x18\x01 \x01(\x03R\x03cid\x12\x10\n" +
	"\x03tid\x18\x02 \x01(\x03R\x03tid\x12\x10\n" +
	"\x03uid\x18\x03 \x01(\x03R\x03uid\x12\x1a\n" +
	"\bparentId\x18\x04 \x01(\x03R\bparentId\x12\x16\n" +
	"\x06rootId\x18\x05 \x01(\x03R\x06rootId\x12\x18\n" +
	"\acontent\x18\x06 \x01(\tR\acontent\x12\x1c\n" +
	"\tlikeCount\x18\a \x01(\x03R\tlikeCount\x12\x1e\n" +
	"\n" +
	"replyCount\x18\b \x01(\x03R\n" +
	"replyCount\x12\x16\n" +
	"\x06status\x18\t \x01(\x05R\x06status\x12\x1e\n" +
	"\n" +
	"createTime\x18\n" +
	" \x01(\tR\n" +
	"createTime\"l\n" +
	"\x10CreateCommentReq\x12\x10\n" +
	"\x03tid\x18\x01 \x01(\x03R\x03tid\x12\x10\n" +
	"\x03uid\x18\x02 \x01(\x03R\x03uid\x12\x18\n" +
	"\acontent\x18\x03 \x01(\tR\acontent\x12\x1a\n" +
	"\bparentId\x18\x04 \x01(\x03R\bparentId\">\n" +
	"\x11CreateCommentResp\x12)\n" +
	"\acomment\x18\x01 \x01(\v2\x0f.pb.CommentInfoR\acomment\"6\n" +
	"\x10DeleteCommentReq\x12\x10\n" +
	"\x03cid\x18\x01 \x01(\x03R\x03cid\x12\x10\n" +
	"\x03uid\x18\x02 \x01(\x03R\x03uid\"?\n" +
	"\x11DeleteCommentResp\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x10\n" +
	"\x03cid\x18\x02 \x01(\x03R\x03cid\"f\n" +
	"\x0eGetCommentsReq\x12\x10\n" +
	"\x03tid\x18\x01 \x01(\x03R\x03tid\x12\x12\n" +
	"\x04page\x18\x02 \x01(\x03R\x04page\x12\x1a\n" +
	"\bpageSize\x18\x03 \x01(\x03R\bpageSize\x12\x12\n" +
	"\x04sort\x18\x04 \x01(\tR\x04sort\"T\n" +
	"\x0fGetCommentsResp\x12+\n" +
	"\bcomments\x18\x01 \x03(\v2\x0f.pb.CommentInfoR\bcomments\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x03R\x05total\"Q\n" +
	"\rGetRepliesReq\x12\x10\n" +
	"\x03cid\x18\x01 \x01(\x03R\x03cid\x12\x12\n" +
	"\x04page\x18\x02 \x01(\x03R\x04page\x12\x1a\n" +
	"\bpageSize\x18\x03 \x01(\x03R\bpageSize\"Q\n" +
	"\x0eGetRepliesResp\x12)\n" +
	"\areplies\x18\x01 \x03(\v2\x0f.pb.CommentInfoR\areplies\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x03R\x05total\"\xca\x01\n" +
	"\bLikeInfo\x12\x18\n" +
	"\alikesId\x18\x01 \x01(\x03R\alikesId\x12\x10\n" +
	"\x03uid\x18\x02 \x01(\x03R\x03uid\x12\x1e\n" +
	"\n" +
	"targetType\x18\x03 \x01(\x05R\n" +
	"targetType\x12\x1a\n" +
	"\btargetId\x18\x04 \x01(\x03R\btargetId\x12\x16\n" +
	"\x06status\x18\x05 \x01(\x05R\x06status\x12\x1e\n" +
	"\n" +
	"createTime\x18\x06 \x01(\tR\n" +
	"createTime\x12\x1e\n" +
	"\n" +
	"updateTime\x18\a \x01(\tR\n" +
	"updateTime\"o\n" +
	"\aLikeReq\x12\x10\n" +
	"\x03uid\x18\x01 \x01(\x03R\x03uid\x12\x1e\n" +
	"\n" +
	"targetType\x18\x02 \x01(\x05R\n" +
	"targetType\x12\x1a\n" +
	"\btargetId\x18\x03 \x01(\x03R\btargetId\x12\x16\n" +
	"\x06action\x18\x04 \x01(\x05R\x06action\"$\n" +
	"\bLikeResp\x12\x18\n" +
	"\aisLiked\x18\x01 \x01(\bR\aisLiked\"`\n" +
	"\x10GetLikeStatusReq\x12\x10\n" +
	"\x03uid\x18\x01 \x01(\x03R\x03uid\x12\x1e\n" +
	"\n" +
	"targetType\x18\x02 \x01(\x05R\n" +
	"targetType\x12\x1a\n" +
	"\btargetId\x18\x03 \x01(\x03R\btargetId\"-\n" +
	"\x11GetLikeStatusResp\x12\x18\n" +
	"\aisLiked\x18\x01 \x01(\bR\aisLiked\"g\n" +
	"\x15BatchGetLikeStatusReq\x12\x10\n" +
	"\x03uid\x18\x01 \x01(\x03R\x03uid\x12\x1e\n" +
	"\n" +
	"targetType\x18\x02 \x01(\x05R\n" +
	"targetType\x12\x1c\n" +
	"\ttargetIds\x18\x03 \x03(\x03R\ttargetIds\"\x97\x01\n" +
	"\x16BatchGetLikeStatusResp\x12A\n" +
	"\aisLiked\x18\x01 \x03(\v2'.pb.BatchGetLikeStatusResp.IsLikedEntryR\aisLiked\x1a:\n" +
	"\fIsLikedEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\x03R\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\bR\x05value:\x028\x012\xa4\x03\n" +
	"\vInteraction\x12<\n" +
	"\rCreateComment\x12\x14.pb.CreateCommentReq\x1a\x15.pb.CreateCommentResp\x12<\n" +
	"\rDeleteComment\x12\x14.pb.DeleteCommentReq\x1a\x15.pb.DeleteCommentResp\x126\n" +
	"\vGetComments\x12\x12.pb.GetCommentsReq\x1a\x13.pb.GetCommentsResp\x123\n" +
	"\n" +
	"GetReplies\x12\x11.pb.GetRepliesReq\x1a\x12.pb.GetRepliesResp\x12!\n" +
	"\x04Like\x12\v.pb.LikeReq\x1a\f.pb.LikeResp\x12<\n" +
	"\rGetLikeStatus\x12\x14.pb.GetLikeStatusReq\x1a\x15.pb.GetLikeStatusResp\x12K\n" +
	"\x12BatchGetLikeStatus\x12\x19.pb.BatchGetLikeStatusReq\x1a\x1a.pb.BatchGetLikeStatusRespB\x06Z\x04./pbb\x06proto3"

var (
	file_pb_interactService_proto_rawDescOnce sync.Once
	file_pb_interactService_proto_rawDescData []byte
)

func file_pb_interactService_proto_rawDescGZIP() []byte {
	file_pb_interactService_proto_rawDescOnce.Do(func() {
		file_pb_interactService_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pb_interactService_proto_rawDesc), len(file_pb_interactService_proto_rawDesc)))
	})
	return file_pb_interactService_proto_rawDescData
}

var file_pb_interactService_proto_msgTypes = make([]protoimpl.MessageInfo, 19)
var file_pb_interactService_proto_goTypes = []any{
	(*PageReq)(nil),                // 0: pb.PageReq
	(*PageResp)(nil),               // 1: pb.PageResp
	(*CommentInfo)(nil),            // 2: pb.CommentInfo
	(*CreateCommentReq)(nil),       // 3: pb.CreateCommentReq
	(*CreateCommentResp)(nil),      // 4: pb.CreateCommentResp
	(*DeleteCommentReq)(nil),       // 5: pb.DeleteCommentReq
	(*DeleteCommentResp)(nil),      // 6: pb.DeleteCommentResp
	(*GetCommentsReq)(nil),         // 7: pb.GetCommentsReq
	(*GetCommentsResp)(nil),        // 8: pb.GetCommentsResp
	(*GetRepliesReq)(nil),          // 9: pb.GetRepliesReq
	(*GetRepliesResp)(nil),         // 10: pb.GetRepliesResp
	(*LikeInfo)(nil),               // 11: pb.LikeInfo
	(*LikeReq)(nil),                // 12: pb.LikeReq
	(*LikeResp)(nil),               // 13: pb.LikeResp
	(*GetLikeStatusReq)(nil),       // 14: pb.GetLikeStatusReq
	(*GetLikeStatusResp)(nil),      // 15: pb.GetLikeStatusResp
	(*BatchGetLikeStatusReq)(nil),  // 16: pb.BatchGetLikeStatusReq
	(*BatchGetLikeStatusResp)(nil), // 17: pb.BatchGetLikeStatusResp
	nil,                            // 18: pb.BatchGetLikeStatusResp.IsLikedEntry
}
var file_pb_interactService_proto_depIdxs = []int32{
	2,  // 0: pb.CreateCommentResp.comment:type_name -> pb.CommentInfo
	2,  // 1: pb.GetCommentsResp.comments:type_name -> pb.CommentInfo
	2,  // 2: pb.GetRepliesResp.replies:type_name -> pb.CommentInfo
	18, // 3: pb.BatchGetLikeStatusResp.isLiked:type_name -> pb.BatchGetLikeStatusResp.IsLikedEntry
	3,  // 4: pb.Interaction.CreateComment:input_type -> pb.CreateCommentReq
	5,  // 5: pb.Interaction.DeleteComment:input_type -> pb.DeleteCommentReq
	7,  // 6: pb.Interaction.GetComments:input_type -> pb.GetCommentsReq
	9,  // 7: pb.Interaction.GetReplies:input_type -> pb.GetRepliesReq
	12, // 8: pb.Interaction.Like:input_type -> pb.LikeReq
	14, // 9: pb.Interaction.GetLikeStatus:input_type -> pb.GetLikeStatusReq
	16, // 10: pb.Interaction.BatchGetLikeStatus:input_type -> pb.BatchGetLikeStatusReq
	4,  // 11: pb.Interaction.CreateComment:output_type -> pb.CreateCommentResp
	6,  // 12: pb.Interaction.DeleteComment:output_type -> pb.DeleteCommentResp
	8,  // 13: pb.Interaction.GetComments:output_type -> pb.GetCommentsResp
	10, // 14: pb.Interaction.GetReplies:output_type -> pb.GetRepliesResp
	13, // 15: pb.Interaction.Like:output_type -> pb.LikeResp
	15, // 16: pb.Interaction.GetLikeStatus:output_type -> pb.GetLikeStatusResp
	17, // 17: pb.Interaction.BatchGetLikeStatus:output_type -> pb.BatchGetLikeStatusResp
	11, // [11:18] is the sub-list for method output_type
	4,  // [4:11] is the sub-list for method input_type
	4,  // [4:4] is the sub-list for extension type_name
	4,  // [4:4] is the sub-list for extension extendee
	0,  // [0:4] is the sub-list for field type_name
}

func init() { file_pb_interactService_proto_init() }
func file_pb_interactService_proto_init() {
	if File_pb_interactService_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pb_interactService_proto_rawDesc), len(file_pb_interactService_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   19,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pb_interactService_proto_goTypes,
		DependencyIndexes: file_pb_interactService_proto_depIdxs,
		MessageInfos:      file_pb_interactService_proto_msgTypes,
	}.Build()
	File_pb_interactService_proto = out.File
	file_pb_interactService_proto_goTypes = nil
	file_pb_interactService_proto_depIdxs = nil
}
