// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: pb/interactService.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 评论基础信息
type CommentInfo struct {
	state      protoimpl.MessageState `protogen:"open.v1"`
	SnowCid    int64                  `protobuf:"varint,1,opt,name=snow_cid,json=snowCid,proto3" json:"snow_cid,omitempty"` // 评论ID，使用雪花算法生成，保证全局唯一且有序，方便分页查询
	SnowTid    int64                  `protobuf:"varint,2,opt,name=snow_tid,json=snowTid,proto3" json:"snow_tid,omitempty"` // 评论所属推文ID
	Uid        int64                  `protobuf:"varint,3,opt,name=uid,proto3" json:"uid,omitempty"`                        // 评论用户ID
	ParentId   int64                  `protobuf:"varint,4,opt,name=parentId,proto3" json:"parentId,omitempty"`              // 0表示顶级评论，否则为回复对象的snow_cid
	RootId     int64                  `protobuf:"varint,5,opt,name=rootId,proto3" json:"rootId,omitempty"`                  // 顶级评论ID，方便查询一个评论树下的所有评论。顶级评论的rootId等于自己的snow_cid，回复评论的rootId等于它所在的顶级评论的snow_cid。
	Content    string                 `protobuf:"bytes,6,opt,name=content,proto3" json:"content,omitempty"`                 // 评论内容
	LikeCount  int64                  `protobuf:"varint,7,opt,name=likeCount,proto3" json:"likeCount,omitempty"`            // 点赞总数
	ReplyCount int64                  `protobuf:"varint,8,opt,name=replyCount,proto3" json:"replyCount,omitempty"`          // 回复总数
	CreateTime int64                  `protobuf:"varint,9,opt,name=createTime,proto3" json:"createTime,omitempty"`          // 评论创建时间，毫秒级时间戳
	// 以下字段不存储在数据库中，而是通过关联查询获取的额外信息
	Nickname      string `protobuf:"bytes,10,opt,name=nickname,proto3" json:"nickname,omitempty"` // 评论用户昵称
	Avatar        string `protobuf:"bytes,11,opt,name=avatar,proto3" json:"avatar,omitempty"`     // 评论用户头像
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CommentInfo) Reset() {
	*x = CommentInfo{}
	mi := &file_pb_interactService_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommentInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommentInfo) ProtoMessage() {}

func (x *CommentInfo) ProtoReflect() protoreflect.Message {
	mi := &file_pb_interactService_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommentInfo.ProtoReflect.Descriptor instead.
func (*CommentInfo) Descriptor() ([]byte, []int) {
	return file_pb_interactService_proto_rawDescGZIP(), []int{0}
}

func (x *CommentInfo) GetSnowCid() int64 {
	if x != nil {
		return x.SnowCid
	}
	return 0
}

func (x *CommentInfo) GetSnowTid() int64 {
	if x != nil {
		return x.SnowTid
	}
	return 0
}

func (x *CommentInfo) GetUid() int64 {
	if x != nil {
		return x.Uid
	}
	return 0
}

func (x *CommentInfo) GetParentId() int64 {
	if x != nil {
		return x.ParentId
	}
	return 0
}

func (x *CommentInfo) GetRootId() int64 {
	if x != nil {
		return x.RootId
	}
	return 0
}

func (x *CommentInfo) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *CommentInfo) GetLikeCount() int64 {
	if x != nil {
		return x.LikeCount
	}
	return 0
}

func (x *CommentInfo) GetReplyCount() int64 {
	if x != nil {
		return x.ReplyCount
	}
	return 0
}

func (x *CommentInfo) GetCreateTime() int64 {
	if x != nil {
		return x.CreateTime
	}
	return 0
}

func (x *CommentInfo) GetNickname() string {
	if x != nil {
		return x.Nickname
	}
	return ""
}

func (x *CommentInfo) GetAvatar() string {
	if x != nil {
		return x.Avatar
	}
	return ""
}

// 创建评论
type CreateCommentReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SnowTid       int64                  `protobuf:"varint,1,opt,name=snow_tid,json=snowTid,proto3" json:"snow_tid,omitempty"`
	Uid           int64                  `protobuf:"varint,2,opt,name=uid,proto3" json:"uid,omitempty"`
	Content       string                 `protobuf:"bytes,3,opt,name=content,proto3" json:"content,omitempty"`
	ParentId      int64                  `protobuf:"varint,4,opt,name=parentId,proto3" json:"parentId,omitempty"` // 0表示顶级评论,否则为回复对象的snow_cid。
	RootId        int64                  `protobuf:"varint,5,opt,name=rootId,proto3" json:"rootId,omitempty"`     // 顶级评论ID，如果parentId!=0,说明是回复评论，那么这个rootId应该已经是为它所在的顶级评论的snow_cid，否则是0，代表根评论
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateCommentReq) Reset() {
	*x = CreateCommentReq{}
	mi := &file_pb_interactService_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateCommentReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateCommentReq) ProtoMessage() {}

func (x *CreateCommentReq) ProtoReflect() protoreflect.Message {
	mi := &file_pb_interactService_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateCommentReq.ProtoReflect.Descriptor instead.
func (*CreateCommentReq) Descriptor() ([]byte, []int) {
	return file_pb_interactService_proto_rawDescGZIP(), []int{1}
}

func (x *CreateCommentReq) GetSnowTid() int64 {
	if x != nil {
		return x.SnowTid
	}
	return 0
}

func (x *CreateCommentReq) GetUid() int64 {
	if x != nil {
		return x.Uid
	}
	return 0
}

func (x *CreateCommentReq) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *CreateCommentReq) GetParentId() int64 {
	if x != nil {
		return x.ParentId
	}
	return 0
}

func (x *CreateCommentReq) GetRootId() int64 {
	if x != nil {
		return x.RootId
	}
	return 0
}

type CreateCommentResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int64                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Msg           string                 `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	Comment       *CommentInfo           `protobuf:"bytes,3,opt,name=comment,proto3" json:"comment,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateCommentResp) Reset() {
	*x = CreateCommentResp{}
	mi := &file_pb_interactService_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateCommentResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateCommentResp) ProtoMessage() {}

func (x *CreateCommentResp) ProtoReflect() protoreflect.Message {
	mi := &file_pb_interactService_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateCommentResp.ProtoReflect.Descriptor instead.
func (*CreateCommentResp) Descriptor() ([]byte, []int) {
	return file_pb_interactService_proto_rawDescGZIP(), []int{2}
}

func (x *CreateCommentResp) GetCode() int64 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *CreateCommentResp) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

func (x *CreateCommentResp) GetComment() *CommentInfo {
	if x != nil {
		return x.Comment
	}
	return nil
}

// 删除评论
type DeleteCommentReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SnowCid       int64                  `protobuf:"varint,1,opt,name=snow_cid,json=snowCid,proto3" json:"snow_cid,omitempty"`
	Uid           int64                  `protobuf:"varint,2,opt,name=uid,proto3" json:"uid,omitempty"` // 删除评论的用户ID，后端需要校验这个用户是否有权限删除这条评论（只能删除自己的评论或者管理员可以删除任何评论）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteCommentReq) Reset() {
	*x = DeleteCommentReq{}
	mi := &file_pb_interactService_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteCommentReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteCommentReq) ProtoMessage() {}

func (x *DeleteCommentReq) ProtoReflect() protoreflect.Message {
	mi := &file_pb_interactService_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteCommentReq.ProtoReflect.Descriptor instead.
func (*DeleteCommentReq) Descriptor() ([]byte, []int) {
	return file_pb_interactService_proto_rawDescGZIP(), []int{3}
}

func (x *DeleteCommentReq) GetSnowCid() int64 {
	if x != nil {
		return x.SnowCid
	}
	return 0
}

func (x *DeleteCommentReq) GetUid() int64 {
	if x != nil {
		return x.Uid
	}
	return 0
}

type DeleteCommentResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int64                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Msg           string                 `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	Success       bool                   `protobuf:"varint,3,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteCommentResp) Reset() {
	*x = DeleteCommentResp{}
	mi := &file_pb_interactService_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteCommentResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteCommentResp) ProtoMessage() {}

func (x *DeleteCommentResp) ProtoReflect() protoreflect.Message {
	mi := &file_pb_interactService_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteCommentResp.ProtoReflect.Descriptor instead.
func (*DeleteCommentResp) Descriptor() ([]byte, []int) {
	return file_pb_interactService_proto_rawDescGZIP(), []int{4}
}

func (x *DeleteCommentResp) GetCode() int64 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *DeleteCommentResp) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

func (x *DeleteCommentResp) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

// 获取评论列表
type GetCommentsReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SnowTid       int64                  `protobuf:"varint,1,opt,name=snow_tid,json=snowTid,proto3" json:"snow_tid,omitempty"`
	Cursor        int64                  `protobuf:"varint,2,opt,name=cursor,proto3" json:"cursor,omitempty"` // 上次请求最后一条评论的createtime或者是likecount或者是综合加权对应的值，第一次请求可以不传或者传0
	Limit         int64                  `protobuf:"varint,3,opt,name=limit,proto3" json:"limit,omitempty"`   // 需要评论数量
	Sort          int64                  `protobuf:"varint,4,opt,name=sort,proto3" json:"sort,omitempty"`     // 0-按综合排序加权，1-按createTime倒序排序（最新的）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCommentsReq) Reset() {
	*x = GetCommentsReq{}
	mi := &file_pb_interactService_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCommentsReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCommentsReq) ProtoMessage() {}

func (x *GetCommentsReq) ProtoReflect() protoreflect.Message {
	mi := &file_pb_interactService_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCommentsReq.ProtoReflect.Descriptor instead.
func (*GetCommentsReq) Descriptor() ([]byte, []int) {
	return file_pb_interactService_proto_rawDescGZIP(), []int{5}
}

func (x *GetCommentsReq) GetSnowTid() int64 {
	if x != nil {
		return x.SnowTid
	}
	return 0
}

func (x *GetCommentsReq) GetCursor() int64 {
	if x != nil {
		return x.Cursor
	}
	return 0
}

func (x *GetCommentsReq) GetLimit() int64 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *GetCommentsReq) GetSort() int64 {
	if x != nil {
		return x.Sort
	}
	return 0
}

type GetCommentsResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int64                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Msg           string                 `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	Comments      []*CommentInfo         `protobuf:"bytes,3,rep,name=comments,proto3" json:"comments,omitempty"`
	Total         int64                  `protobuf:"varint,4,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCommentsResp) Reset() {
	*x = GetCommentsResp{}
	mi := &file_pb_interactService_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCommentsResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCommentsResp) ProtoMessage() {}

func (x *GetCommentsResp) ProtoReflect() protoreflect.Message {
	mi := &file_pb_interactService_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCommentsResp.ProtoReflect.Descriptor instead.
func (*GetCommentsResp) Descriptor() ([]byte, []int) {
	return file_pb_interactService_proto_rawDescGZIP(), []int{6}
}

func (x *GetCommentsResp) GetCode() int64 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *GetCommentsResp) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

func (x *GetCommentsResp) GetComments() []*CommentInfo {
	if x != nil {
		return x.Comments
	}
	return nil
}

func (x *GetCommentsResp) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

// 获取评论回复列表
type GetRepliesReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RootCid       int64                  `protobuf:"varint,1,opt,name=root_cid,json=rootCid,proto3" json:"root_cid,omitempty"` // 根评论的snow_cid
	Cursor        int64                  `protobuf:"varint,2,opt,name=cursor,proto3" json:"cursor,omitempty"`                  // 上次请求最后一条评论的createtime对应的值
	Limit         int64                  `protobuf:"varint,3,opt,name=limit,proto3" json:"limit,omitempty"`                    // 需要评论数量
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRepliesReq) Reset() {
	*x = GetRepliesReq{}
	mi := &file_pb_interactService_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRepliesReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRepliesReq) ProtoMessage() {}

func (x *GetRepliesReq) ProtoReflect() protoreflect.Message {
	mi := &file_pb_interactService_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRepliesReq.ProtoReflect.Descriptor instead.
func (*GetRepliesReq) Descriptor() ([]byte, []int) {
	return file_pb_interactService_proto_rawDescGZIP(), []int{7}
}

func (x *GetRepliesReq) GetRootCid() int64 {
	if x != nil {
		return x.RootCid
	}
	return 0
}

func (x *GetRepliesReq) GetCursor() int64 {
	if x != nil {
		return x.Cursor
	}
	return 0
}

func (x *GetRepliesReq) GetLimit() int64 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type GetRepliesResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int64                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Msg           string                 `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	Replies       []*CommentInfo         `protobuf:"bytes,3,rep,name=replies,proto3" json:"replies,omitempty"`
	Total         int64                  `protobuf:"varint,4,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRepliesResp) Reset() {
	*x = GetRepliesResp{}
	mi := &file_pb_interactService_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRepliesResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRepliesResp) ProtoMessage() {}

func (x *GetRepliesResp) ProtoReflect() protoreflect.Message {
	mi := &file_pb_interactService_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRepliesResp.ProtoReflect.Descriptor instead.
func (*GetRepliesResp) Descriptor() ([]byte, []int) {
	return file_pb_interactService_proto_rawDescGZIP(), []int{8}
}

func (x *GetRepliesResp) GetCode() int64 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *GetRepliesResp) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

func (x *GetRepliesResp) GetReplies() []*CommentInfo {
	if x != nil {
		return x.Replies
	}
	return nil
}

func (x *GetRepliesResp) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

// 点赞记录信息
type LikeTweetInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SnowLikesId   int64                  `protobuf:"varint,1,opt,name=snow_likes_id,json=snowLikesId,proto3" json:"snow_likes_id,omitempty"`
	Uid           int64                  `protobuf:"varint,2,opt,name=uid,proto3" json:"uid,omitempty"`
	SnowTid       int64                  `protobuf:"varint,3,opt,name=snow_tid,json=snowTid,proto3" json:"snow_tid,omitempty"`
	Status        int64                  `protobuf:"varint,4,opt,name=status,proto3" json:"status,omitempty"` // 1-点赞 0-取消
	UpdateTime    int64                  `protobuf:"varint,5,opt,name=updateTime,proto3" json:"updateTime,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LikeTweetInfo) Reset() {
	*x = LikeTweetInfo{}
	mi := &file_pb_interactService_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LikeTweetInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LikeTweetInfo) ProtoMessage() {}

func (x *LikeTweetInfo) ProtoReflect() protoreflect.Message {
	mi := &file_pb_interactService_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LikeTweetInfo.ProtoReflect.Descriptor instead.
func (*LikeTweetInfo) Descriptor() ([]byte, []int) {
	return file_pb_interactService_proto_rawDescGZIP(), []int{9}
}

func (x *LikeTweetInfo) GetSnowLikesId() int64 {
	if x != nil {
		return x.SnowLikesId
	}
	return 0
}

func (x *LikeTweetInfo) GetUid() int64 {
	if x != nil {
		return x.Uid
	}
	return 0
}

func (x *LikeTweetInfo) GetSnowTid() int64 {
	if x != nil {
		return x.SnowTid
	}
	return 0
}

func (x *LikeTweetInfo) GetStatus() int64 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *LikeTweetInfo) GetUpdateTime() int64 {
	if x != nil {
		return x.UpdateTime
	}
	return 0
}

type LikeCommentInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SnowLikesId   int64                  `protobuf:"varint,1,opt,name=snow_likes_id,json=snowLikesId,proto3" json:"snow_likes_id,omitempty"`
	Uid           int64                  `protobuf:"varint,2,opt,name=uid,proto3" json:"uid,omitempty"`
	SnowCid       int64                  `protobuf:"varint,3,opt,name=snow_cid,json=snowCid,proto3" json:"snow_cid,omitempty"`
	SnowTid       int64                  `protobuf:"varint,4,opt,name=snow_tid,json=snowTid,proto3" json:"snow_tid,omitempty"`
	Status        int64                  `protobuf:"varint,5,opt,name=status,proto3" json:"status,omitempty"` // 1-点赞 0-取消
	UpdateTime    int64                  `protobuf:"varint,6,opt,name=updateTime,proto3" json:"updateTime,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LikeCommentInfo) Reset() {
	*x = LikeCommentInfo{}
	mi := &file_pb_interactService_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LikeCommentInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LikeCommentInfo) ProtoMessage() {}

func (x *LikeCommentInfo) ProtoReflect() protoreflect.Message {
	mi := &file_pb_interactService_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LikeCommentInfo.ProtoReflect.Descriptor instead.
func (*LikeCommentInfo) Descriptor() ([]byte, []int) {
	return file_pb_interactService_proto_rawDescGZIP(), []int{10}
}

func (x *LikeCommentInfo) GetSnowLikesId() int64 {
	if x != nil {
		return x.SnowLikesId
	}
	return 0
}

func (x *LikeCommentInfo) GetUid() int64 {
	if x != nil {
		return x.Uid
	}
	return 0
}

func (x *LikeCommentInfo) GetSnowCid() int64 {
	if x != nil {
		return x.SnowCid
	}
	return 0
}

func (x *LikeCommentInfo) GetSnowTid() int64 {
	if x != nil {
		return x.SnowTid
	}
	return 0
}

func (x *LikeCommentInfo) GetStatus() int64 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *LikeCommentInfo) GetUpdateTime() int64 {
	if x != nil {
		return x.UpdateTime
	}
	return 0
}

// 点赞/取消点赞
type LikeTweetReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IsCreated     int64                  `protobuf:"varint,1,opt,name=is_created,json=isCreated,proto3" json:"is_created,omitempty"`         // 0-第一次操作（创建），1-非第一次（更新）
	SnowLikesId   int64                  `protobuf:"varint,2,opt,name=snow_likes_id,json=snowLikesId,proto3" json:"snow_likes_id,omitempty"` // 第一次操作时为空，更新时为之前创建的点赞记录ID
	Uid           int64                  `protobuf:"varint,3,opt,name=uid,proto3" json:"uid,omitempty"`
	SnowTid       int64                  `protobuf:"varint,4,opt,name=snow_tid,json=snowTid,proto3" json:"snow_tid,omitempty"`
	Status        int64                  `protobuf:"varint,5,opt,name=status,proto3" json:"status,omitempty"`         // 1-点赞 0-取消
	UpdateTime    int64                  `protobuf:"varint,6,opt,name=updateTime,proto3" json:"updateTime,omitempty"` // 操作时间（毫秒级时间戳）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LikeTweetReq) Reset() {
	*x = LikeTweetReq{}
	mi := &file_pb_interactService_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LikeTweetReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LikeTweetReq) ProtoMessage() {}

func (x *LikeTweetReq) ProtoReflect() protoreflect.Message {
	mi := &file_pb_interactService_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LikeTweetReq.ProtoReflect.Descriptor instead.
func (*LikeTweetReq) Descriptor() ([]byte, []int) {
	return file_pb_interactService_proto_rawDescGZIP(), []int{11}
}

func (x *LikeTweetReq) GetIsCreated() int64 {
	if x != nil {
		return x.IsCreated
	}
	return 0
}

func (x *LikeTweetReq) GetSnowLikesId() int64 {
	if x != nil {
		return x.SnowLikesId
	}
	return 0
}

func (x *LikeTweetReq) GetUid() int64 {
	if x != nil {
		return x.Uid
	}
	return 0
}

func (x *LikeTweetReq) GetSnowTid() int64 {
	if x != nil {
		return x.SnowTid
	}
	return 0
}

func (x *LikeTweetReq) GetStatus() int64 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *LikeTweetReq) GetUpdateTime() int64 {
	if x != nil {
		return x.UpdateTime
	}
	return 0
}

type LikeCommentReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IsCreated     int64                  `protobuf:"varint,1,opt,name=is_created,json=isCreated,proto3" json:"is_created,omitempty"`
	SnowLikesId   int64                  `protobuf:"varint,2,opt,name=snow_likes_id,json=snowLikesId,proto3" json:"snow_likes_id,omitempty"`
	Uid           int64                  `protobuf:"varint,3,opt,name=uid,proto3" json:"uid,omitempty"`
	SnowCid       int64                  `protobuf:"varint,4,opt,name=snow_cid,json=snowCid,proto3" json:"snow_cid,omitempty"`
	SnowTid       int64                  `protobuf:"varint,5,opt,name=snow_tid,json=snowTid,proto3" json:"snow_tid,omitempty"`
	Status        int64                  `protobuf:"varint,6,opt,name=status,proto3" json:"status,omitempty"`
	UpdateTime    int64                  `protobuf:"varint,7,opt,name=updateTime,proto3" json:"updateTime,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LikeCommentReq) Reset() {
	*x = LikeCommentReq{}
	mi := &file_pb_interactService_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LikeCommentReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LikeCommentReq) ProtoMessage() {}

func (x *LikeCommentReq) ProtoReflect() protoreflect.Message {
	mi := &file_pb_interactService_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LikeCommentReq.ProtoReflect.Descriptor instead.
func (*LikeCommentReq) Descriptor() ([]byte, []int) {
	return file_pb_interactService_proto_rawDescGZIP(), []int{12}
}

func (x *LikeCommentReq) GetIsCreated() int64 {
	if x != nil {
		return x.IsCreated
	}
	return 0
}

func (x *LikeCommentReq) GetSnowLikesId() int64 {
	if x != nil {
		return x.SnowLikesId
	}
	return 0
}

func (x *LikeCommentReq) GetUid() int64 {
	if x != nil {
		return x.Uid
	}
	return 0
}

func (x *LikeCommentReq) GetSnowCid() int64 {
	if x != nil {
		return x.SnowCid
	}
	return 0
}

func (x *LikeCommentReq) GetSnowTid() int64 {
	if x != nil {
		return x.SnowTid
	}
	return 0
}

func (x *LikeCommentReq) GetStatus() int64 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *LikeCommentReq) GetUpdateTime() int64 {
	if x != nil {
		return x.UpdateTime
	}
	return 0
}

type LikeTweetResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int64                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Msg           string                 `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	Like          *LikeTweetInfo         `protobuf:"bytes,3,opt,name=like,proto3" json:"like,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LikeTweetResp) Reset() {
	*x = LikeTweetResp{}
	mi := &file_pb_interactService_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LikeTweetResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LikeTweetResp) ProtoMessage() {}

func (x *LikeTweetResp) ProtoReflect() protoreflect.Message {
	mi := &file_pb_interactService_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LikeTweetResp.ProtoReflect.Descriptor instead.
func (*LikeTweetResp) Descriptor() ([]byte, []int) {
	return file_pb_interactService_proto_rawDescGZIP(), []int{13}
}

func (x *LikeTweetResp) GetCode() int64 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *LikeTweetResp) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

func (x *LikeTweetResp) GetLike() *LikeTweetInfo {
	if x != nil {
		return x.Like
	}
	return nil
}

type LikeCommentResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int64                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Msg           string                 `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	Like          *LikeCommentInfo       `protobuf:"bytes,3,opt,name=like,proto3" json:"like,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LikeCommentResp) Reset() {
	*x = LikeCommentResp{}
	mi := &file_pb_interactService_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LikeCommentResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LikeCommentResp) ProtoMessage() {}

func (x *LikeCommentResp) ProtoReflect() protoreflect.Message {
	mi := &file_pb_interactService_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LikeCommentResp.ProtoReflect.Descriptor instead.
func (*LikeCommentResp) Descriptor() ([]byte, []int) {
	return file_pb_interactService_proto_rawDescGZIP(), []int{14}
}

func (x *LikeCommentResp) GetCode() int64 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *LikeCommentResp) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

func (x *LikeCommentResp) GetLike() *LikeCommentInfo {
	if x != nil {
		return x.Like
	}
	return nil
}

// 用户推文点赞关系（用于前端本地存储）
type UserTweetLike struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SnowTid       int64                  `protobuf:"varint,1,opt,name=snow_tid,json=snowTid,proto3" json:"snow_tid,omitempty"`               // 推文ID
	SnowLikesId   int64                  `protobuf:"varint,2,opt,name=snow_likes_id,json=snowLikesId,proto3" json:"snow_likes_id,omitempty"` // 点赞记录ID
	Status        int64                  `protobuf:"varint,3,opt,name=status,proto3" json:"status,omitempty"`                                // 1-已点赞，0-已取消
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserTweetLike) Reset() {
	*x = UserTweetLike{}
	mi := &file_pb_interactService_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserTweetLike) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserTweetLike) ProtoMessage() {}

func (x *UserTweetLike) ProtoReflect() protoreflect.Message {
	mi := &file_pb_interactService_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserTweetLike.ProtoReflect.Descriptor instead.
func (*UserTweetLike) Descriptor() ([]byte, []int) {
	return file_pb_interactService_proto_rawDescGZIP(), []int{15}
}

func (x *UserTweetLike) GetSnowTid() int64 {
	if x != nil {
		return x.SnowTid
	}
	return 0
}

func (x *UserTweetLike) GetSnowLikesId() int64 {
	if x != nil {
		return x.SnowLikesId
	}
	return 0
}

func (x *UserTweetLike) GetStatus() int64 {
	if x != nil {
		return x.Status
	}
	return 0
}

// 用户评论点赞关系（用于前端本地存储）
type UserCommentLike struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SnowTid       int64                  `protobuf:"varint,1,opt,name=snow_tid,json=snowTid,proto3" json:"snow_tid,omitempty"`               // 评论ID
	SnowCid       int64                  `protobuf:"varint,2,opt,name=snow_cid,json=snowCid,proto3" json:"snow_cid,omitempty"`               // 评论ID
	SnowLikesId   int64                  `protobuf:"varint,3,opt,name=snow_likes_id,json=snowLikesId,proto3" json:"snow_likes_id,omitempty"` // 点赞记录ID
	Status        int64                  `protobuf:"varint,4,opt,name=status,proto3" json:"status,omitempty"`                                // 1-已点赞，0-已取消
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserCommentLike) Reset() {
	*x = UserCommentLike{}
	mi := &file_pb_interactService_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserCommentLike) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserCommentLike) ProtoMessage() {}

func (x *UserCommentLike) ProtoReflect() protoreflect.Message {
	mi := &file_pb_interactService_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserCommentLike.ProtoReflect.Descriptor instead.
func (*UserCommentLike) Descriptor() ([]byte, []int) {
	return file_pb_interactService_proto_rawDescGZIP(), []int{16}
}

func (x *UserCommentLike) GetSnowTid() int64 {
	if x != nil {
		return x.SnowTid
	}
	return 0
}

func (x *UserCommentLike) GetSnowCid() int64 {
	if x != nil {
		return x.SnowCid
	}
	return 0
}

func (x *UserCommentLike) GetSnowLikesId() int64 {
	if x != nil {
		return x.SnowLikesId
	}
	return 0
}

func (x *UserCommentLike) GetStatus() int64 {
	if x != nil {
		return x.Status
	}
	return 0
}

// 获取用户所有点赞关系（登录时调用，前端存储到本地）
type GetUserAllLikesReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uid           int64                  `protobuf:"varint,1,opt,name=uid,proto3" json:"uid,omitempty"`
	Cursor        int64                  `protobuf:"varint,2,opt,name=cursor,proto3" json:"cursor,omitempty"` //返回updateTime在此时间后面的所有点赞关系
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserAllLikesReq) Reset() {
	*x = GetUserAllLikesReq{}
	mi := &file_pb_interactService_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserAllLikesReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserAllLikesReq) ProtoMessage() {}

func (x *GetUserAllLikesReq) ProtoReflect() protoreflect.Message {
	mi := &file_pb_interactService_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserAllLikesReq.ProtoReflect.Descriptor instead.
func (*GetUserAllLikesReq) Descriptor() ([]byte, []int) {
	return file_pb_interactService_proto_rawDescGZIP(), []int{17}
}

func (x *GetUserAllLikesReq) GetUid() int64 {
	if x != nil {
		return x.Uid
	}
	return 0
}

func (x *GetUserAllLikesReq) GetCursor() int64 {
	if x != nil {
		return x.Cursor
	}
	return 0
}

type GetUserAllLikesResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int64                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Msg           string                 `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	TweetLikes    []*UserTweetLike       `protobuf:"bytes,3,rep,name=tweet_likes,json=tweetLikes,proto3" json:"tweet_likes,omitempty"`       // 用户所有推文点赞关系
	CommentLikes  []*UserCommentLike     `protobuf:"bytes,4,rep,name=comment_likes,json=commentLikes,proto3" json:"comment_likes,omitempty"` // 用户所有评论点赞关系
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserAllLikesResp) Reset() {
	*x = GetUserAllLikesResp{}
	mi := &file_pb_interactService_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserAllLikesResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserAllLikesResp) ProtoMessage() {}

func (x *GetUserAllLikesResp) ProtoReflect() protoreflect.Message {
	mi := &file_pb_interactService_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserAllLikesResp.ProtoReflect.Descriptor instead.
func (*GetUserAllLikesResp) Descriptor() ([]byte, []int) {
	return file_pb_interactService_proto_rawDescGZIP(), []int{18}
}

func (x *GetUserAllLikesResp) GetCode() int64 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *GetUserAllLikesResp) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

func (x *GetUserAllLikesResp) GetTweetLikes() []*UserTweetLike {
	if x != nil {
		return x.TweetLikes
	}
	return nil
}

func (x *GetUserAllLikesResp) GetCommentLikes() []*UserCommentLike {
	if x != nil {
		return x.CommentLikes
	}
	return nil
}

var File_pb_interactService_proto protoreflect.FileDescriptor

const file_pb_interactService_proto_rawDesc = "" +
	"\n" +
	"\x18pb/interactService.proto\x12\x02pb\"\xb5\x02\n" +
	"\vCommentInfo\x12\x19\n" +
	"\bsnow_cid\x18\x01 \x01(\x03R\asnowCid\x12\x19\n" +
	"\bsnow_tid\x18\x02 \x01(\x03R\asnowTid\x12\x10\n" +
	"\x03uid\x18\x03 \x01(\x03R\x03uid\x12\x1a\n" +
	"\bparentId\x18\x04 \x01(\x03R\bparentId\x12\x16\n" +
	"\x06rootId\x18\x05 \x01(\x03R\x06rootId\x12\x18\n" +
	"\acontent\x18\x06 \x01(\tR\acontent\x12\x1c\n" +
	"\tlikeCount\x18\a \x01(\x03R\tlikeCount\x12\x1e\n" +
	"\n" +
	"replyCount\x18\b \x01(\x03R\n" +
	"replyCount\x12\x1e\n" +
	"\n" +
	"createTime\x18\t \x01(\x03R\n" +
	"createTime\x12\x1a\n" +
	"\bnickname\x18\n" +
	" \x01(\tR\bnickname\x12\x16\n" +
	"\x06avatar\x18\v \x01(\tR\x06avatar\"\x8d\x01\n" +
	"\x10CreateCommentReq\x12\x19\n" +
	"\bsnow_tid\x18\x01 \x01(\x03R\asnowTid\x12\x10\n" +
	"\x03uid\x18\x02 \x01(\x03R\x03uid\x12\x18\n" +
	"\acontent\x18\x03 \x01(\tR\acontent\x12\x1a\n" +
	"\bparentId\x18\x04 \x01(\x03R\bparentId\x12\x16\n" +
	"\x06rootId\x18\x05 \x01(\x03R\x06rootId\"d\n" +
	"\x11CreateCommentResp\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x03R\x04code\x12\x10\n" +
	"\x03msg\x18\x02 \x01(\tR\x03msg\x12)\n" +
	"\acomment\x18\x03 \x01(\v2\x0f.pb.CommentInfoR\acomment\"?\n" +
	"\x10DeleteCommentReq\x12\x19\n" +
	"\bsnow_cid\x18\x01 \x01(\x03R\asnowCid\x12\x10\n" +
	"\x03uid\x18\x02 \x01(\x03R\x03uid\"S\n" +
	"\x11DeleteCommentResp\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x03R\x04code\x12\x10\n" +
	"\x03msg\x18\x02 \x01(\tR\x03msg\x12\x18\n" +
	"\asuccess\x18\x03 \x01(\bR\asuccess\"m\n" +
	"\x0eGetCommentsReq\x12\x19\n" +
	"\bsnow_tid\x18\x01 \x01(\x03R\asnowTid\x12\x16\n" +
	"\x06cursor\x18\x02 \x01(\x03R\x06cursor\x12\x14\n" +
	"\x05limit\x18\x03 \x01(\x03R\x05limit\x12\x12\n" +
	"\x04sort\x18\x04 \x01(\x03R\x04sort\"z\n" +
	"\x0fGetCommentsResp\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x03R\x04code\x12\x10\n" +
	"\x03msg\x18\x02 \x01(\tR\x03msg\x12+\n" +
	"\bcomments\x18\x03 \x03(\v2\x0f.pb.CommentInfoR\bcomments\x12\x14\n" +
	"\x05total\x18\x04 \x01(\x03R\x05total\"X\n" +
	"\rGetRepliesReq\x12\x19\n" +
	"\broot_cid\x18\x01 \x01(\x03R\arootCid\x12\x16\n" +
	"\x06cursor\x18\x02 \x01(\x03R\x06cursor\x12\x14\n" +
	"\x05limit\x18\x03 \x01(\x03R\x05limit\"w\n" +
	"\x0eGetRepliesResp\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x03R\x04code\x12\x10\n" +
	"\x03msg\x18\x02 \x01(\tR\x03msg\x12)\n" +
	"\areplies\x18\x03 \x03(\v2\x0f.pb.CommentInfoR\areplies\x12\x14\n" +
	"\x05total\x18\x04 \x01(\x03R\x05total\"\x98\x01\n" +
	"\rLikeTweetInfo\x12\"\n" +
	"\rsnow_likes_id\x18\x01 \x01(\x03R\vsnowLikesId\x12\x10\n" +
	"\x03uid\x18\x02 \x01(\x03R\x03uid\x12\x19\n" +
	"\bsnow_tid\x18\x03 \x01(\x03R\asnowTid\x12\x16\n" +
	"\x06status\x18\x04 \x01(\x03R\x06status\x12\x1e\n" +
	"\n" +
	"updateTime\x18\x05 \x01(\x03R\n" +
	"updateTime\"\xb5\x01\n" +
	"\x0fLikeCommentInfo\x12\"\n" +
	"\rsnow_likes_id\x18\x01 \x01(\x03R\vsnowLikesId\x12\x10\n" +
	"\x03uid\x18\x02 \x01(\x03R\x03uid\x12\x19\n" +
	"\bsnow_cid\x18\x03 \x01(\x03R\asnowCid\x12\x19\n" +
	"\bsnow_tid\x18\x04 \x01(\x03R\asnowTid\x12\x16\n" +
	"\x06status\x18\x05 \x01(\x03R\x06status\x12\x1e\n" +
	"\n" +
	"updateTime\x18\x06 \x01(\x03R\n" +
	"updateTime\"\xb6\x01\n" +
	"\fLikeTweetReq\x12\x1d\n" +
	"\n" +
	"is_created\x18\x01 \x01(\x03R\tisCreated\x12\"\n" +
	"\rsnow_likes_id\x18\x02 \x01(\x03R\vsnowLikesId\x12\x10\n" +
	"\x03uid\x18\x03 \x01(\x03R\x03uid\x12\x19\n" +
	"\bsnow_tid\x18\x04 \x01(\x03R\asnowTid\x12\x16\n" +
	"\x06status\x18\x05 \x01(\x03R\x06status\x12\x1e\n" +
	"\n" +
	"updateTime\x18\x06 \x01(\x03R\n" +
	"updateTime\"\xd3\x01\n" +
	"\x0eLikeCommentReq\x12\x1d\n" +
	"\n" +
	"is_created\x18\x01 \x01(\x03R\tisCreated\x12\"\n" +
	"\rsnow_likes_id\x18\x02 \x01(\x03R\vsnowLikesId\x12\x10\n" +
	"\x03uid\x18\x03 \x01(\x03R\x03uid\x12\x19\n" +
	"\bsnow_cid\x18\x04 \x01(\x03R\asnowCid\x12\x19\n" +
	"\bsnow_tid\x18\x05 \x01(\x03R\asnowTid\x12\x16\n" +
	"\x06status\x18\x06 \x01(\x03R\x06status\x12\x1e\n" +
	"\n" +
	"updateTime\x18\a \x01(\x03R\n" +
	"updateTime\"\\\n" +
	"\rLikeTweetResp\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x03R\x04code\x12\x10\n" +
	"\x03msg\x18\x02 \x01(\tR\x03msg\x12%\n" +
	"\x04like\x18\x03 \x01(\v2\x11.pb.LikeTweetInfoR\x04like\"`\n" +
	"\x0fLikeCommentResp\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x03R\x04code\x12\x10\n" +
	"\x03msg\x18\x02 \x01(\tR\x03msg\x12'\n" +
	"\x04like\x18\x03 \x01(\v2\x13.pb.LikeCommentInfoR\x04like\"f\n" +
	"\rUserTweetLike\x12\x19\n" +
	"\bsnow_tid\x18\x01 \x01(\x03R\asnowTid\x12\"\n" +
	"\rsnow_likes_id\x18\x02 \x01(\x03R\vsnowLikesId\x12\x16\n" +
	"\x06status\x18\x03 \x01(\x03R\x06status\"\x83\x01\n" +
	"\x0fUserCommentLike\x12\x19\n" +
	"\bsnow_tid\x18\x01 \x01(\x03R\asnowTid\x12\x19\n" +
	"\bsnow_cid\x18\x02 \x01(\x03R\asnowCid\x12\"\n" +
	"\rsnow_likes_id\x18\x03 \x01(\x03R\vsnowLikesId\x12\x16\n" +
	"\x06status\x18\x04 \x01(\x03R\x06status\">\n" +
	"\x12GetUserAllLikesReq\x12\x10\n" +
	"\x03uid\x18\x01 \x01(\x03R\x03uid\x12\x16\n" +
	"\x06cursor\x18\x02 \x01(\x03R\x06cursor\"\xa9\x01\n" +
	"\x13GetUserAllLikesResp\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x03R\x04code\x12\x10\n" +
	"\x03msg\x18\x02 \x01(\tR\x03msg\x122\n" +
	"\vtweet_likes\x18\x03 \x03(\v2\x11.pb.UserTweetLikeR\n" +
	"tweetLikes\x128\n" +
	"\rcomment_likes\x18\x04 \x03(\v2\x13.pb.UserCommentLikeR\fcommentLikes2\xa4\x03\n" +
	"\vInteraction\x12<\n" +
	"\rCreateComment\x12\x14.pb.CreateCommentReq\x1a\x15.pb.CreateCommentResp\x12<\n" +
	"\rDeleteComment\x12\x14.pb.DeleteCommentReq\x1a\x15.pb.DeleteCommentResp\x126\n" +
	"\vGetComments\x12\x12.pb.GetCommentsReq\x1a\x13.pb.GetCommentsResp\x123\n" +
	"\n" +
	"GetReplies\x12\x11.pb.GetRepliesReq\x1a\x12.pb.GetRepliesResp\x120\n" +
	"\tLikeTweet\x12\x10.pb.LikeTweetReq\x1a\x11.pb.LikeTweetResp\x126\n" +
	"\vLikeComment\x12\x12.pb.LikeCommentReq\x1a\x13.pb.LikeCommentResp\x12B\n" +
	"\x0fGetUserAllLikes\x12\x16.pb.GetUserAllLikesReq\x1a\x17.pb.GetUserAllLikesRespB\x06Z\x04./pbb\x06proto3"

var (
	file_pb_interactService_proto_rawDescOnce sync.Once
	file_pb_interactService_proto_rawDescData []byte
)

func file_pb_interactService_proto_rawDescGZIP() []byte {
	file_pb_interactService_proto_rawDescOnce.Do(func() {
		file_pb_interactService_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pb_interactService_proto_rawDesc), len(file_pb_interactService_proto_rawDesc)))
	})
	return file_pb_interactService_proto_rawDescData
}

var file_pb_interactService_proto_msgTypes = make([]protoimpl.MessageInfo, 19)
var file_pb_interactService_proto_goTypes = []any{
	(*CommentInfo)(nil),         // 0: pb.CommentInfo
	(*CreateCommentReq)(nil),    // 1: pb.CreateCommentReq
	(*CreateCommentResp)(nil),   // 2: pb.CreateCommentResp
	(*DeleteCommentReq)(nil),    // 3: pb.DeleteCommentReq
	(*DeleteCommentResp)(nil),   // 4: pb.DeleteCommentResp
	(*GetCommentsReq)(nil),      // 5: pb.GetCommentsReq
	(*GetCommentsResp)(nil),     // 6: pb.GetCommentsResp
	(*GetRepliesReq)(nil),       // 7: pb.GetRepliesReq
	(*GetRepliesResp)(nil),      // 8: pb.GetRepliesResp
	(*LikeTweetInfo)(nil),       // 9: pb.LikeTweetInfo
	(*LikeCommentInfo)(nil),     // 10: pb.LikeCommentInfo
	(*LikeTweetReq)(nil),        // 11: pb.LikeTweetReq
	(*LikeCommentReq)(nil),      // 12: pb.LikeCommentReq
	(*LikeTweetResp)(nil),       // 13: pb.LikeTweetResp
	(*LikeCommentResp)(nil),     // 14: pb.LikeCommentResp
	(*UserTweetLike)(nil),       // 15: pb.UserTweetLike
	(*UserCommentLike)(nil),     // 16: pb.UserCommentLike
	(*GetUserAllLikesReq)(nil),  // 17: pb.GetUserAllLikesReq
	(*GetUserAllLikesResp)(nil), // 18: pb.GetUserAllLikesResp
}
var file_pb_interactService_proto_depIdxs = []int32{
	0,  // 0: pb.CreateCommentResp.comment:type_name -> pb.CommentInfo
	0,  // 1: pb.GetCommentsResp.comments:type_name -> pb.CommentInfo
	0,  // 2: pb.GetRepliesResp.replies:type_name -> pb.CommentInfo
	9,  // 3: pb.LikeTweetResp.like:type_name -> pb.LikeTweetInfo
	10, // 4: pb.LikeCommentResp.like:type_name -> pb.LikeCommentInfo
	15, // 5: pb.GetUserAllLikesResp.tweet_likes:type_name -> pb.UserTweetLike
	16, // 6: pb.GetUserAllLikesResp.comment_likes:type_name -> pb.UserCommentLike
	1,  // 7: pb.Interaction.CreateComment:input_type -> pb.CreateCommentReq
	3,  // 8: pb.Interaction.DeleteComment:input_type -> pb.DeleteCommentReq
	5,  // 9: pb.Interaction.GetComments:input_type -> pb.GetCommentsReq
	7,  // 10: pb.Interaction.GetReplies:input_type -> pb.GetRepliesReq
	11, // 11: pb.Interaction.LikeTweet:input_type -> pb.LikeTweetReq
	12, // 12: pb.Interaction.LikeComment:input_type -> pb.LikeCommentReq
	17, // 13: pb.Interaction.GetUserAllLikes:input_type -> pb.GetUserAllLikesReq
	2,  // 14: pb.Interaction.CreateComment:output_type -> pb.CreateCommentResp
	4,  // 15: pb.Interaction.DeleteComment:output_type -> pb.DeleteCommentResp
	6,  // 16: pb.Interaction.GetComments:output_type -> pb.GetCommentsResp
	8,  // 17: pb.Interaction.GetReplies:output_type -> pb.GetRepliesResp
	13, // 18: pb.Interaction.LikeTweet:output_type -> pb.LikeTweetResp
	14, // 19: pb.Interaction.LikeComment:output_type -> pb.LikeCommentResp
	18, // 20: pb.Interaction.GetUserAllLikes:output_type -> pb.GetUserAllLikesResp
	14, // [14:21] is the sub-list for method output_type
	7,  // [7:14] is the sub-list for method input_type
	7,  // [7:7] is the sub-list for extension type_name
	7,  // [7:7] is the sub-list for extension extendee
	0,  // [0:7] is the sub-list for field type_name
}

func init() { file_pb_interactService_proto_init() }
func file_pb_interactService_proto_init() {
	if File_pb_interactService_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pb_interactService_proto_rawDesc), len(file_pb_interactService_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   19,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pb_interactService_proto_goTypes,
		DependencyIndexes: file_pb_interactService_proto_depIdxs,
		MessageInfos:      file_pb_interactService_proto_msgTypes,
	}.Build()
	File_pb_interactService_proto = out.File
	file_pb_interactService_proto_goTypes = nil
	file_pb_interactService_proto_depIdxs = nil
}
