// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1

package types

type RecommendFeedReq struct {
	Limit  int64 `form:"limit,default=8"`
	Cursor int64 `form:"cursor,optional"`
}

type RecommendFeedResp struct {
	Code    int64       `json:"code"`
	Msg     string      `json:"msg"`
	Data    []TweetInfo `json:"data"`
	Cursor  int64       `json:"cursor"`
	HasMore bool        `json:"hasMore"`
}

type TweetInfo struct {
	SnowTid      int64    `json:"snowTid,string"`
	Uid          int64    `json:"uid"`
	Content      string   `json:"content"`
	MediaUrls    []string `json:"mediaUrls"`
	Tags         []string `json:"tags"`
	LikeCount    int64    `json:"likeCount"`
	CommentCount int64    `json:"commentCount"`
	CreatedAt    int64    `json:"createdAt"`
	Nickname     string   `json:"nickname"`
	Avatar       string   `json:"avatar"`
}
