######## gozeroX 应用服务 ########
######## docker compose build / docker compose up ########

services:
  # ===== API 网关 =====
  nginx-gateway:
    image: nginx:1.28.0
    container_name: nginx-gateway
    restart: always
    environment:
      TZ: Asia/Shanghai
    ports:
      - 8888:8081
    volumes:
      - ./deploy/nginx/conf.d:/etc/nginx/conf.d
      - ./data/nginx/log:/var/log/nginx
    network_mode: host

  # ===== usercenter =====
  usercenter-api:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        BUILD_SERVICE: ./app/usercenter/cmd/api
    image: gozerox/usercenter-api:latest
    container_name: usercenter-api
    network_mode: host

  usercenter-rpc:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        BUILD_SERVICE: ./app/usercenter/cmd/rpc
    image: gozerox/usercenter-rpc:latest
    container_name: usercenter-rpc
    network_mode: host

  # ===== contentService =====
  contentservice-api:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        BUILD_SERVICE: ./app/contentService/cmd/api
    image: gozerox/contentservice-api:latest
    container_name: contentservice-api
    network_mode: host

  contentservice-rpc:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        BUILD_SERVICE: ./app/contentService/cmd/rpc
    image: gozerox/contentservice-rpc:latest
    container_name: contentservice-rpc
    network_mode: host

  # ===== interactService =====
  interactservice-api:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        BUILD_SERVICE: ./app/interactService/cmd/api
    image: gozerox/interactservice-api:latest
    container_name: interactservice-api
    network_mode: host

  interactservice-rpc:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        BUILD_SERVICE: ./app/interactService/cmd/rpc
    image: gozerox/interactservice-rpc:latest
    container_name: interactservice-rpc
    network_mode: host

  interactservice-mq:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        BUILD_SERVICE: ./app/interactService/cmd/mq
    image: gozerox/interactservice-mq:latest
    container_name: interactservice-mq
    network_mode: host

  # ===== noticeService =====
  noticeservice-api:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        BUILD_SERVICE: ./app/noticeService/cmd/api
    image: gozerox/noticeservice-api:latest
    container_name: noticeservice-api
    network_mode: host

  noticeservice-rpc:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        BUILD_SERVICE: ./app/noticeService/cmd/rpc
    image: gozerox/noticeservice-rpc:latest
    container_name: noticeservice-rpc
    network_mode: host

  noticeservice-mq:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        BUILD_SERVICE: ./app/noticeService/cmd/mq
    image: gozerox/noticeservice-mq:latest
    container_name: noticeservice-mq
    network_mode: host

  # ===== recommendService =====
  recommendservice-api:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        BUILD_SERVICE: ./app/recommendService/cmd/api
    image: gozerox/recommendservice-api:latest
    container_name: recommendservice-api
    network_mode: host

  recommendservice-rpc:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        BUILD_SERVICE: ./app/recommendService/cmd/rpc
    image: gozerox/recommendservice-rpc:latest
    container_name: recommendservice-rpc
    network_mode: host
