global:
  scrape_interval: 5s
  external_labels:
    monitor: 'codelab-monitor'

scrape_configs:
  - job_name: 'prometheus'
    scrape_interval: 5s
    static_configs:
      - targets: ['127.0.0.1:9090']

  # ===== usercenter =====
  - job_name: 'user-api'
    static_configs:
      - targets: ['usercenter-api:4001']
        labels:
          job: user-api
          app: user-api
          env: dev
  - job_name: 'user-rpc'
    static_configs:
      - targets: ['usercenter-rpc:4002']
        labels:
          job: user-rpc
          app: user-rpc
          env: dev

  # ===== contentService =====
  - job_name: 'content-api'
    static_configs:
      - targets: ['contentservice-api:4003']
        labels:
          job: content-api
          app: content-api
          env: dev
  - job_name: 'content-rpc'
    static_configs:
      - targets: ['contentservice-rpc:4004']
        labels:
          job: content-rpc
          app: content-rpc
          env: dev

  # ===== interactService =====
  - job_name: 'interact-api'
    static_configs:
      - targets: ['interactservice-api:4005']
        labels:
          job: interact-api
          app: interact-api
          env: dev
  - job_name: 'interact-rpc'
    static_configs:
      - targets: ['interactservice-rpc:4006']
        labels:
          job: interact-rpc
          app: interact-rpc
          env: dev
  - job_name: 'interact-mq'
    static_configs:
      - targets: ['interactservice-mq:4007']
        labels:
          job: interact-mq
          app: interact-mq
          env: dev

  # ===== noticeService =====
  - job_name: 'notice-api'
    static_configs:
      - targets: ['noticeservice-api:4008']
        labels:
          job: notice-api
          app: notice-api
          env: dev
  - job_name: 'notice-rpc'
    static_configs:
      - targets: ['noticeservice-rpc:4009']
        labels:
          job: notice-rpc
          app: notice-rpc
          env: dev
  - job_name: 'notice-mq'
    static_configs:
      - targets: ['noticeservice-mq:4010']
        labels:
          job: notice-mq
          app: notice-mq
          env: dev

  # ===== recommendService =====
  - job_name: 'recommend-api'
    static_configs:
      - targets: ['recommendservice-api:4011']
        labels:
          job: recommend-api
          app: recommend-api
          env: dev
  - job_name: 'recommend-rpc'
    static_configs:
      - targets: ['recommendservice-rpc:4012']
        labels:
          job: recommend-rpc
          app: recommend-rpc
          env: dev

  # ===== python-recall =====
  - job_name: 'python-recall'
    static_configs:
      - targets: ['python-recall:4013']
        labels:
          job: python-recall
          app: python-recall
          env: dev
