// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2

package handler

import (
	"net/http"

	user "gozeroX/app/usercenter/cmd/api/internal/handler/user"
	"gozeroX/app/usercenter/cmd/api/internal/svc"
	"gozeroX/pkg/jwt"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				// login
				Method:  http.MethodPost,
				Path:    "/user/login",
				Handler: user.LoginHandler(serverCtx),
			},
			{
				// register
				Method:  http.MethodPost,
				Path:    "/user/register",
				Handler: user.RegisterHandler(serverCtx),
			},
		},
		rest.WithPrefix("/usercenter/v1"),
	)


	jwtMiddleware := jwt.NewJwtMiddleware(serverCtx.Config.JwtAuth.AccessSecret)

	server.AddRoutes(
		[]rest.Route{
			{
				// get user info
				Method:  http.MethodPost,
				Path:    "/user/detail",
				Handler: jwtMiddleware.Handle(user.DetailHandler(serverCtx)),
			},
		},
		rest.WithPrefix("/usercenter/v1"),
	)
}
