apiVersion: v1
kind: Secret
metadata:
  name: db-redis-secret
  namespace: gozerox
type: Opaque
stringData:
  POSTGRES_PASSWORD: "mTRT1XBhk9VgWb9n"
  REDIS_PASSWORD: "mTRT1XBhk9VgWb9n"
  DATASOURCE: "postgres://postgres:mTRT1XBhk9VgWb9n@postgresql:5432/gozerox_db?sslmode=disable"
  JWT_SECRET: "a7f3d9c1e5b8290f4a6e8d2c7b5a3f9e1"
