// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1
// Source: recommendService.proto

package server

import (
	"context"

	"gozeroX/app/recommendService/cmd/rpc/internal/logic"
	"gozeroX/app/recommendService/cmd/rpc/internal/svc"
	"gozeroX/app/recommendService/cmd/rpc/pb"
)

type RecommendServer struct {
	svcCtx *svc.ServiceContext
	pb.UnimplementedRecommendServer
}

func NewRecommendServer(svcCtx *svc.ServiceContext) *RecommendServer {
	return &RecommendServer{
		svcCtx: svcCtx,
	}
}

// 推荐首页 Feed
func (s *RecommendServer) RecommendFeed(ctx context.Context, in *pb.RecommendFeedReq) (*pb.RecommendFeedResp, error) {
	l := logic.NewRecommendFeedLogic(ctx, s.svcCtx)
	return l.RecommendFeed(in)
}

// 搜索推荐（预留）
func (s *RecommendServer) SearchRecommend(ctx context.Context, in *pb.SearchRecommendReq) (*pb.SearchRecommendResp, error) {
	l := logic.NewSearchRecommendLogic(ctx, s.svcCtx)
	return l.SearchRecommend(in)
}
