// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: pb/noticeService.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ==================== 点赞通知 ====================
type NoticeLikeInfo struct {
	state       protoimpl.MessageState `protogen:"open.v1"`
	SnowNid     int64                  `protobuf:"varint,1,opt,name=snow_nid,json=snowNid,proto3" json:"snow_nid,omitempty"`
	TargetType  int64                  `protobuf:"varint,2,opt,name=target_type,json=targetType,proto3" json:"target_type,omitempty"` // 0=推文点赞, 1=评论点赞
	TargetId    int64                  `protobuf:"varint,3,opt,name=target_id,json=targetId,proto3" json:"target_id,omitempty"`
	SnowTid     int64                  `protobuf:"varint,4,opt,name=snow_tid,json=snowTid,proto3" json:"snow_tid,omitempty"`
	RootId      int64                  `protobuf:"varint,5,opt,name=root_id,json=rootId,proto3" json:"root_id,omitempty"`
	RecentUid_1 int64                  `protobuf:"varint,6,opt,name=recent_uid_1,json=recentUid1,proto3" json:"recent_uid_1,omitempty"`
	RecentUid_2 int64                  `protobuf:"varint,7,opt,name=recent_uid_2,json=recentUid2,proto3" json:"recent_uid_2,omitempty"`
	Uid         int64                  `protobuf:"varint,8,opt,name=uid,proto3" json:"uid,omitempty"` // 通知接收者
	TotalCount  int64                  `protobuf:"varint,9,opt,name=total_count,json=totalCount,proto3" json:"total_count,omitempty"`
	RecentCount int64                  `protobuf:"varint,17,opt,name=recent_count,json=recentCount,proto3" json:"recent_count,omitempty"` // 自上次查看以来的新增点赞数
	IsRead      int64                  `protobuf:"varint,10,opt,name=is_read,json=isRead,proto3" json:"is_read,omitempty"`
	CreatedAt   int64                  `protobuf:"varint,11,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt   int64                  `protobuf:"varint,12,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	// 以下字段通过 usercenter RPC 按需获取
	RecentNickname_1 string `protobuf:"bytes,13,opt,name=recent_nickname_1,json=recentNickname1,proto3" json:"recent_nickname_1,omitempty"`
	RecentAvatar_1   string `protobuf:"bytes,14,opt,name=recent_avatar_1,json=recentAvatar1,proto3" json:"recent_avatar_1,omitempty"`
	RecentNickname_2 string `protobuf:"bytes,15,opt,name=recent_nickname_2,json=recentNickname2,proto3" json:"recent_nickname_2,omitempty"`
	RecentAvatar_2   string `protobuf:"bytes,16,opt,name=recent_avatar_2,json=recentAvatar2,proto3" json:"recent_avatar_2,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *NoticeLikeInfo) Reset() {
	*x = NoticeLikeInfo{}
	mi := &file_pb_noticeService_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NoticeLikeInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NoticeLikeInfo) ProtoMessage() {}

func (x *NoticeLikeInfo) ProtoReflect() protoreflect.Message {
	mi := &file_pb_noticeService_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NoticeLikeInfo.ProtoReflect.Descriptor instead.
func (*NoticeLikeInfo) Descriptor() ([]byte, []int) {
	return file_pb_noticeService_proto_rawDescGZIP(), []int{0}
}

func (x *NoticeLikeInfo) GetSnowNid() int64 {
	if x != nil {
		return x.SnowNid
	}
	return 0
}

func (x *NoticeLikeInfo) GetTargetType() int64 {
	if x != nil {
		return x.TargetType
	}
	return 0
}

func (x *NoticeLikeInfo) GetTargetId() int64 {
	if x != nil {
		return x.TargetId
	}
	return 0
}

func (x *NoticeLikeInfo) GetSnowTid() int64 {
	if x != nil {
		return x.SnowTid
	}
	return 0
}

func (x *NoticeLikeInfo) GetRootId() int64 {
	if x != nil {
		return x.RootId
	}
	return 0
}

func (x *NoticeLikeInfo) GetRecentUid_1() int64 {
	if x != nil {
		return x.RecentUid_1
	}
	return 0
}

func (x *NoticeLikeInfo) GetRecentUid_2() int64 {
	if x != nil {
		return x.RecentUid_2
	}
	return 0
}

func (x *NoticeLikeInfo) GetUid() int64 {
	if x != nil {
		return x.Uid
	}
	return 0
}

func (x *NoticeLikeInfo) GetTotalCount() int64 {
	if x != nil {
		return x.TotalCount
	}
	return 0
}

func (x *NoticeLikeInfo) GetRecentCount() int64 {
	if x != nil {
		return x.RecentCount
	}
	return 0
}

func (x *NoticeLikeInfo) GetIsRead() int64 {
	if x != nil {
		return x.IsRead
	}
	return 0
}

func (x *NoticeLikeInfo) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *NoticeLikeInfo) GetUpdatedAt() int64 {
	if x != nil {
		return x.UpdatedAt
	}
	return 0
}

func (x *NoticeLikeInfo) GetRecentNickname_1() string {
	if x != nil {
		return x.RecentNickname_1
	}
	return ""
}

func (x *NoticeLikeInfo) GetRecentAvatar_1() string {
	if x != nil {
		return x.RecentAvatar_1
	}
	return ""
}

func (x *NoticeLikeInfo) GetRecentNickname_2() string {
	if x != nil {
		return x.RecentNickname_2
	}
	return ""
}

func (x *NoticeLikeInfo) GetRecentAvatar_2() string {
	if x != nil {
		return x.RecentAvatar_2
	}
	return ""
}

// ==================== 评论通知 ====================
type NoticeCommentInfo struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	SnowNid        int64                  `protobuf:"varint,1,opt,name=snow_nid,json=snowNid,proto3" json:"snow_nid,omitempty"`
	TargetType     int64                  `protobuf:"varint,2,opt,name=target_type,json=targetType,proto3" json:"target_type,omitempty"` // 0=推文评论, 1=评论回复
	CommenterUid   int64                  `protobuf:"varint,3,opt,name=commenter_uid,json=commenterUid,proto3" json:"commenter_uid,omitempty"`
	Uid            int64                  `protobuf:"varint,4,opt,name=uid,proto3" json:"uid,omitempty"` // 通知接收者
	SnowTid        int64                  `protobuf:"varint,5,opt,name=snow_tid,json=snowTid,proto3" json:"snow_tid,omitempty"`
	SnowCid        int64                  `protobuf:"varint,6,opt,name=snow_cid,json=snowCid,proto3" json:"snow_cid,omitempty"`
	RootId         int64                  `protobuf:"varint,7,opt,name=root_id,json=rootId,proto3" json:"root_id,omitempty"`
	ParentId       int64                  `protobuf:"varint,8,opt,name=parent_id,json=parentId,proto3" json:"parent_id,omitempty"`
	Content        string                 `protobuf:"bytes,9,opt,name=content,proto3" json:"content,omitempty"`
	RepliedContent string                 `protobuf:"bytes,10,opt,name=replied_content,json=repliedContent,proto3" json:"replied_content,omitempty"`
	IsRead         int64                  `protobuf:"varint,11,opt,name=is_read,json=isRead,proto3" json:"is_read,omitempty"`
	CreatedAt      int64                  `protobuf:"varint,12,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt      int64                  `protobuf:"varint,13,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	// 通过 usercenter RPC 按需获取
	CommenterNickname string `protobuf:"bytes,14,opt,name=commenter_nickname,json=commenterNickname,proto3" json:"commenter_nickname,omitempty"`
	CommenterAvatar   string `protobuf:"bytes,15,opt,name=commenter_avatar,json=commenterAvatar,proto3" json:"commenter_avatar,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *NoticeCommentInfo) Reset() {
	*x = NoticeCommentInfo{}
	mi := &file_pb_noticeService_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NoticeCommentInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NoticeCommentInfo) ProtoMessage() {}

func (x *NoticeCommentInfo) ProtoReflect() protoreflect.Message {
	mi := &file_pb_noticeService_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NoticeCommentInfo.ProtoReflect.Descriptor instead.
func (*NoticeCommentInfo) Descriptor() ([]byte, []int) {
	return file_pb_noticeService_proto_rawDescGZIP(), []int{1}
}

func (x *NoticeCommentInfo) GetSnowNid() int64 {
	if x != nil {
		return x.SnowNid
	}
	return 0
}

func (x *NoticeCommentInfo) GetTargetType() int64 {
	if x != nil {
		return x.TargetType
	}
	return 0
}

func (x *NoticeCommentInfo) GetCommenterUid() int64 {
	if x != nil {
		return x.CommenterUid
	}
	return 0
}

func (x *NoticeCommentInfo) GetUid() int64 {
	if x != nil {
		return x.Uid
	}
	return 0
}

func (x *NoticeCommentInfo) GetSnowTid() int64 {
	if x != nil {
		return x.SnowTid
	}
	return 0
}

func (x *NoticeCommentInfo) GetSnowCid() int64 {
	if x != nil {
		return x.SnowCid
	}
	return 0
}

func (x *NoticeCommentInfo) GetRootId() int64 {
	if x != nil {
		return x.RootId
	}
	return 0
}

func (x *NoticeCommentInfo) GetParentId() int64 {
	if x != nil {
		return x.ParentId
	}
	return 0
}

func (x *NoticeCommentInfo) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *NoticeCommentInfo) GetRepliedContent() string {
	if x != nil {
		return x.RepliedContent
	}
	return ""
}

func (x *NoticeCommentInfo) GetIsRead() int64 {
	if x != nil {
		return x.IsRead
	}
	return 0
}

func (x *NoticeCommentInfo) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *NoticeCommentInfo) GetUpdatedAt() int64 {
	if x != nil {
		return x.UpdatedAt
	}
	return 0
}

func (x *NoticeCommentInfo) GetCommenterNickname() string {
	if x != nil {
		return x.CommenterNickname
	}
	return ""
}

func (x *NoticeCommentInfo) GetCommenterAvatar() string {
	if x != nil {
		return x.CommenterAvatar
	}
	return ""
}

// ==================== 获取通知列表 ====================
type GetNoticesReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uid           int64                  `protobuf:"varint,1,opt,name=uid,proto3" json:"uid,omitempty"`
	Cursor        int64                  `protobuf:"varint,2,opt,name=cursor,proto3" json:"cursor,omitempty"` // 游标：上次最后一条的updated_at，首次传0
	Limit         int64                  `protobuf:"varint,3,opt,name=limit,proto3" json:"limit,omitempty"`   // 每页条数，默认20
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetNoticesReq) Reset() {
	*x = GetNoticesReq{}
	mi := &file_pb_noticeService_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetNoticesReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetNoticesReq) ProtoMessage() {}

func (x *GetNoticesReq) ProtoReflect() protoreflect.Message {
	mi := &file_pb_noticeService_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetNoticesReq.ProtoReflect.Descriptor instead.
func (*GetNoticesReq) Descriptor() ([]byte, []int) {
	return file_pb_noticeService_proto_rawDescGZIP(), []int{2}
}

func (x *GetNoticesReq) GetUid() int64 {
	if x != nil {
		return x.Uid
	}
	return 0
}

func (x *GetNoticesReq) GetCursor() int64 {
	if x != nil {
		return x.Cursor
	}
	return 0
}

func (x *GetNoticesReq) GetLimit() int64 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type GetNoticesResp struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Code           int64                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Msg            string                 `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	LikeNotices    []*NoticeLikeInfo      `protobuf:"bytes,3,rep,name=like_notices,json=likeNotices,proto3" json:"like_notices,omitempty"`
	CommentNotices []*NoticeCommentInfo   `protobuf:"bytes,4,rep,name=comment_notices,json=commentNotices,proto3" json:"comment_notices,omitempty"`
	UnreadCount    int64                  `protobuf:"varint,5,opt,name=unread_count,json=unreadCount,proto3" json:"unread_count,omitempty"` // 总未读数
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *GetNoticesResp) Reset() {
	*x = GetNoticesResp{}
	mi := &file_pb_noticeService_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetNoticesResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetNoticesResp) ProtoMessage() {}

func (x *GetNoticesResp) ProtoReflect() protoreflect.Message {
	mi := &file_pb_noticeService_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetNoticesResp.ProtoReflect.Descriptor instead.
func (*GetNoticesResp) Descriptor() ([]byte, []int) {
	return file_pb_noticeService_proto_rawDescGZIP(), []int{3}
}

func (x *GetNoticesResp) GetCode() int64 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *GetNoticesResp) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

func (x *GetNoticesResp) GetLikeNotices() []*NoticeLikeInfo {
	if x != nil {
		return x.LikeNotices
	}
	return nil
}

func (x *GetNoticesResp) GetCommentNotices() []*NoticeCommentInfo {
	if x != nil {
		return x.CommentNotices
	}
	return nil
}

func (x *GetNoticesResp) GetUnreadCount() int64 {
	if x != nil {
		return x.UnreadCount
	}
	return 0
}

// ==================== 获取未读数 ====================
type GetUnreadCountReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uid           int64                  `protobuf:"varint,1,opt,name=uid,proto3" json:"uid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUnreadCountReq) Reset() {
	*x = GetUnreadCountReq{}
	mi := &file_pb_noticeService_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUnreadCountReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUnreadCountReq) ProtoMessage() {}

func (x *GetUnreadCountReq) ProtoReflect() protoreflect.Message {
	mi := &file_pb_noticeService_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUnreadCountReq.ProtoReflect.Descriptor instead.
func (*GetUnreadCountReq) Descriptor() ([]byte, []int) {
	return file_pb_noticeService_proto_rawDescGZIP(), []int{4}
}

func (x *GetUnreadCountReq) GetUid() int64 {
	if x != nil {
		return x.Uid
	}
	return 0
}

type GetUnreadCountResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int64                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Msg           string                 `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	LikeUnread    int64                  `protobuf:"varint,3,opt,name=like_unread,json=likeUnread,proto3" json:"like_unread,omitempty"`
	CommentUnread int64                  `protobuf:"varint,4,opt,name=comment_unread,json=commentUnread,proto3" json:"comment_unread,omitempty"`
	TotalUnread   int64                  `protobuf:"varint,5,opt,name=total_unread,json=totalUnread,proto3" json:"total_unread,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUnreadCountResp) Reset() {
	*x = GetUnreadCountResp{}
	mi := &file_pb_noticeService_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUnreadCountResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUnreadCountResp) ProtoMessage() {}

func (x *GetUnreadCountResp) ProtoReflect() protoreflect.Message {
	mi := &file_pb_noticeService_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUnreadCountResp.ProtoReflect.Descriptor instead.
func (*GetUnreadCountResp) Descriptor() ([]byte, []int) {
	return file_pb_noticeService_proto_rawDescGZIP(), []int{5}
}

func (x *GetUnreadCountResp) GetCode() int64 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *GetUnreadCountResp) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

func (x *GetUnreadCountResp) GetLikeUnread() int64 {
	if x != nil {
		return x.LikeUnread
	}
	return 0
}

func (x *GetUnreadCountResp) GetCommentUnread() int64 {
	if x != nil {
		return x.CommentUnread
	}
	return 0
}

func (x *GetUnreadCountResp) GetTotalUnread() int64 {
	if x != nil {
		return x.TotalUnread
	}
	return 0
}

// ==================== 标记已读 ====================
type MarkReadReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uid           int64                  `protobuf:"varint,1,opt,name=uid,proto3" json:"uid,omitempty"`
	NoticeType    int64                  `protobuf:"varint,2,opt,name=notice_type,json=noticeType,proto3" json:"notice_type,omitempty"` // 0=全部, 1=点赞通知, 2=评论通知
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MarkReadReq) Reset() {
	*x = MarkReadReq{}
	mi := &file_pb_noticeService_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MarkReadReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MarkReadReq) ProtoMessage() {}

func (x *MarkReadReq) ProtoReflect() protoreflect.Message {
	mi := &file_pb_noticeService_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MarkReadReq.ProtoReflect.Descriptor instead.
func (*MarkReadReq) Descriptor() ([]byte, []int) {
	return file_pb_noticeService_proto_rawDescGZIP(), []int{6}
}

func (x *MarkReadReq) GetUid() int64 {
	if x != nil {
		return x.Uid
	}
	return 0
}

func (x *MarkReadReq) GetNoticeType() int64 {
	if x != nil {
		return x.NoticeType
	}
	return 0
}

type MarkReadResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int64                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Msg           string                 `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MarkReadResp) Reset() {
	*x = MarkReadResp{}
	mi := &file_pb_noticeService_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MarkReadResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MarkReadResp) ProtoMessage() {}

func (x *MarkReadResp) ProtoReflect() protoreflect.Message {
	mi := &file_pb_noticeService_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MarkReadResp.ProtoReflect.Descriptor instead.
func (*MarkReadResp) Descriptor() ([]byte, []int) {
	return file_pb_noticeService_proto_rawDescGZIP(), []int{7}
}

func (x *MarkReadResp) GetCode() int64 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *MarkReadResp) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

var File_pb_noticeService_proto protoreflect.FileDescriptor

const file_pb_noticeService_proto_rawDesc = "" +
	"\n" +
	"\x16pb/noticeService.proto\x12\x02pb\"\xb6\x04\n" +
	"\x0eNoticeLikeInfo\x12\x19\n" +
	"\bsnow_nid\x18\x01 \x01(\x03R\asnowNid\x12\x1f\n" +
	"\vtarget_type\x18\x02 \x01(\x03R\n" +
	"targetType\x12\x1b\n" +
	"\ttarget_id\x18\x03 \x01(\x03R\btargetId\x12\x19\n" +
	"\bsnow_tid\x18\x04 \x01(\x03R\asnowTid\x12\x17\n" +
	"\aroot_id\x18\x05 \x01(\x03R\x06rootId\x12 \n" +
	"\frecent_uid_1\x18\x06 \x01(\x03R\n" +
	"recentUid1\x12 \n" +
	"\frecent_uid_2\x18\a \x01(\x03R\n" +
	"recentUid2\x12\x10\n" +
	"\x03uid\x18\b \x01(\x03R\x03uid\x12\x1f\n" +
	"\vtotal_count\x18\t \x01(\x03R\n" +
	"totalCount\x12!\n" +
	"\frecent_count\x18\x11 \x01(\x03R\vrecentCount\x12\x17\n" +
	"\ais_read\x18\n" +
	" \x01(\x03R\x06isRead\x12\x1d\n" +
	"\n" +
	"created_at\x18\v \x01(\x03R\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\f \x01(\x03R\tupdatedAt\x12*\n" +
	"\x11recent_nickname_1\x18\r \x01(\tR\x0frecentNickname1\x12&\n" +
	"\x0frecent_avatar_1\x18\x0e \x01(\tR\rrecentAvatar1\x12*\n" +
	"\x11recent_nickname_2\x18\x0f \x01(\tR\x0frecentNickname2\x12&\n" +
	"\x0frecent_avatar_2\x18\x10 \x01(\tR\rrecentAvatar2\"\xe6\x03\n" +
	"\x11NoticeCommentInfo\x12\x19\n" +
	"\bsnow_nid\x18\x01 \x01(\x03R\asnowNid\x12\x1f\n" +
	"\vtarget_type\x18\x02 \x01(\x03R\n" +
	"targetType\x12#\n" +
	"\rcommenter_uid\x18\x03 \x01(\x03R\fcommenterUid\x12\x10\n" +
	"\x03uid\x18\x04 \x01(\x03R\x03uid\x12\x19\n" +
	"\bsnow_tid\x18\x05 \x01(\x03R\asnowTid\x12\x19\n" +
	"\bsnow_cid\x18\x06 \x01(\x03R\asnowCid\x12\x17\n" +
	"\aroot_id\x18\a \x01(\x03R\x06rootId\x12\x1b\n" +
	"\tparent_id\x18\b \x01(\x03R\bparentId\x12\x18\n" +
	"\acontent\x18\t \x01(\tR\acontent\x12'\n" +
	"\x0freplied_content\x18\n" +
	" \x01(\tR\x0erepliedContent\x12\x17\n" +
	"\ais_read\x18\v \x01(\x03R\x06isRead\x12\x1d\n" +
	"\n" +
	"created_at\x18\f \x01(\x03R\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\r \x01(\x03R\tupdatedAt\x12-\n" +
	"\x12commenter_nickname\x18\x0e \x01(\tR\x11commenterNickname\x12)\n" +
	"\x10commenter_avatar\x18\x0f \x01(\tR\x0fcommenterAvatar\"O\n" +
	"\rGetNoticesReq\x12\x10\n" +
	"\x03uid\x18\x01 \x01(\x03R\x03uid\x12\x16\n" +
	"\x06cursor\x18\x02 \x01(\x03R\x06cursor\x12\x14\n" +
	"\x05limit\x18\x03 \x01(\x03R\x05limit\"\xd0\x01\n" +
	"\x0eGetNoticesResp\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x03R\x04code\x12\x10\n" +
	"\x03msg\x18\x02 \x01(\tR\x03msg\x125\n" +
	"\flike_notices\x18\x03 \x03(\v2\x12.pb.NoticeLikeInfoR\vlikeNotices\x12>\n" +
	"\x0fcomment_notices\x18\x04 \x03(\v2\x15.pb.NoticeCommentInfoR\x0ecommentNotices\x12!\n" +
	"\funread_count\x18\x05 \x01(\x03R\vunreadCount\"%\n" +
	"\x11GetUnreadCountReq\x12\x10\n" +
	"\x03uid\x18\x01 \x01(\x03R\x03uid\"\xa5\x01\n" +
	"\x12GetUnreadCountResp\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x03R\x04code\x12\x10\n" +
	"\x03msg\x18\x02 \x01(\tR\x03msg\x12\x1f\n" +
	"\vlike_unread\x18\x03 \x01(\x03R\n" +
	"likeUnread\x12%\n" +
	"\x0ecomment_unread\x18\x04 \x01(\x03R\rcommentUnread\x12!\n" +
	"\ftotal_unread\x18\x05 \x01(\x03R\vtotalUnread\"@\n" +
	"\vMarkReadReq\x12\x10\n" +
	"\x03uid\x18\x01 \x01(\x03R\x03uid\x12\x1f\n" +
	"\vnotice_type\x18\x02 \x01(\x03R\n" +
	"noticeType\"4\n" +
	"\fMarkReadResp\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x03R\x04code\x12\x10\n" +
	"\x03msg\x18\x02 \x01(\tR\x03msg2\xad\x01\n" +
	"\x06Notice\x123\n" +
	"\n" +
	"GetNotices\x12\x11.pb.GetNoticesReq\x1a\x12.pb.GetNoticesResp\x12?\n" +
	"\x0eGetUnreadCount\x12\x15.pb.GetUnreadCountReq\x1a\x16.pb.GetUnreadCountResp\x12-\n" +
	"\bMarkRead\x12\x0f.pb.MarkReadReq\x1a\x10.pb.MarkReadRespB\x06Z\x04./pbb\x06proto3"

var (
	file_pb_noticeService_proto_rawDescOnce sync.Once
	file_pb_noticeService_proto_rawDescData []byte
)

func file_pb_noticeService_proto_rawDescGZIP() []byte {
	file_pb_noticeService_proto_rawDescOnce.Do(func() {
		file_pb_noticeService_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pb_noticeService_proto_rawDesc), len(file_pb_noticeService_proto_rawDesc)))
	})
	return file_pb_noticeService_proto_rawDescData
}

var file_pb_noticeService_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_pb_noticeService_proto_goTypes = []any{
	(*NoticeLikeInfo)(nil),     // 0: pb.NoticeLikeInfo
	(*NoticeCommentInfo)(nil),  // 1: pb.NoticeCommentInfo
	(*GetNoticesReq)(nil),      // 2: pb.GetNoticesReq
	(*GetNoticesResp)(nil),     // 3: pb.GetNoticesResp
	(*GetUnreadCountReq)(nil),  // 4: pb.GetUnreadCountReq
	(*GetUnreadCountResp)(nil), // 5: pb.GetUnreadCountResp
	(*MarkReadReq)(nil),        // 6: pb.MarkReadReq
	(*MarkReadResp)(nil),       // 7: pb.MarkReadResp
}
var file_pb_noticeService_proto_depIdxs = []int32{
	0, // 0: pb.GetNoticesResp.like_notices:type_name -> pb.NoticeLikeInfo
	1, // 1: pb.GetNoticesResp.comment_notices:type_name -> pb.NoticeCommentInfo
	2, // 2: pb.Notice.GetNotices:input_type -> pb.GetNoticesReq
	4, // 3: pb.Notice.GetUnreadCount:input_type -> pb.GetUnreadCountReq
	6, // 4: pb.Notice.MarkRead:input_type -> pb.MarkReadReq
	3, // 5: pb.Notice.GetNotices:output_type -> pb.GetNoticesResp
	5, // 6: pb.Notice.GetUnreadCount:output_type -> pb.GetUnreadCountResp
	7, // 7: pb.Notice.MarkRead:output_type -> pb.MarkReadResp
	5, // [5:8] is the sub-list for method output_type
	2, // [2:5] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_pb_noticeService_proto_init() }
func file_pb_noticeService_proto_init() {
	if File_pb_noticeService_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pb_noticeService_proto_rawDesc), len(file_pb_noticeService_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pb_noticeService_proto_goTypes,
		DependencyIndexes: file_pb_noticeService_proto_depIdxs,
		MessageInfos:      file_pb_noticeService_proto_msgTypes,
	}.Build()
	File_pb_noticeService_proto = out.File
	file_pb_noticeService_proto_goTypes = nil
	file_pb_noticeService_proto_depIdxs = nil
}
