// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1

package types

type CreateTweetReq struct {
	Content   string   `json:"content"`
	MediaUrls []string `json:"mediaUrls"`
	Tags      []string `json:"tags"`
	IsPublic  bool     `json:"isPublic"`
}

type CreateTweetResp struct {
	Code int64  `json:"code"`
	Msg  string `json:"msg"`
	Data Tweet  `json:"data"`
}

type DeleteTweetReq struct {
	SnowTid int64 `form:"snowTid,string"` // 推文ID（雪花ID）
}

type DeleteTweetResp struct {
	Code int64  `json:"code"`
	Msg  string `json:"msg"`
}

type ListTweetsReq struct {
	QueryUid int64 `form:"queryUid,string"`  // 要查询的用户ID
	Cursor   int64 `form:"cursor,optional"`  // 游标：上次最后一条的createdAt，首次传0
	Limit    int64 `form:"limit,default=20"` // 每页条数
	Sort     int64 `form:"sort,default=0"`   // 0=最新优先(DESC)，1=最旧优先(ASC)
}

type ListTweetsResp struct {
	Code  int64   `json:"code"`
	Msg   string  `json:"msg"`
	Data  []Tweet `json:"data"`
	Total int64   `json:"total"`
}

type Tweet struct {
	SnowTid      int64    `json:"snowTid,string"` // 推文ID（雪花ID）
	Uid          int64    `json:"uid"`            // 发布用户ID
	Content      string   `json:"content"`        // 推文内容
	MediaUrls    []string `json:"mediaUrls"`      // 图片链接
	Tags         []string `json:"tags"`           // 标签
	IsPublic     bool     `json:"isPublic"`       // 是否公开
	CreatedAt    int64    `json:"createdAt"`      // 创建时间（毫秒级时间戳）
	LikeCount    int64    `json:"likeCount"`      // 点赞数
	CommentCount int64    `json:"commentCount"`   // 评论数
	Status       int64    `json:"status"`         // 推文状态：0正常，1删除，2审核
	Nickname     string   `json:"nickname"`       // 发布用户昵称
	Avatar       string   `json:"avatar"`         // 发布用户头像
}

type GetTweetReq struct {
	SnowTid int64 `form:"snowTid,string"` // 推文ID（雪花ID）
}

type GetTweetResp struct {
	Code int64  `json:"code"`
	Msg  string `json:"msg"`
	Data Tweet  `json:"data"`
}
