// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2

package types

type CreateTweetReq struct {
	Uid       int64    `json:"uid" validate:"required"`
	Content   string   `json:"content" validate:"max=280"`
	MediaUrls []string `json:"mediaUrls" validate:"max=9"`
	Tags      []string `json:"tags"`
	IsPublic  bool     `json:"isPublic" validate:"required"`
}

type CreateTweetResp struct {
	Code int64  `json:"code"`
	Msg  string `json:"msg"`
	Data Tweet  `json:"data"`
}

type DeleteTweetReq struct {
	Tid int64 `path:"tid" validate:"required"`
	Uid int64 `json:"uid" validate:"required"`
}

type DeleteTweetResp struct {
	Code int64  `json:"code"`
	Msg  string `json:"msg"`
}

type ListData struct {
	List       []Tweet    `json:"list"`
	Pagination Pagination `json:"pagination"`
}

type ListTweetsUidReq struct {
	Uid  int64  `form:"uid" validate:"required"`
	Page int64  `form:"page,default=1" validate:"min=1"`
	Size int64  `form:"size,default=10" validate:"min=1,max=50"`
	Sort string `form:"sort,default=created_at_desc" validate:"in=created_at_desc|created_at_asc"`
}

type ListTweetsUidResp struct {
	Code int64    `json:"code"`
	Msg  string   `json:"msg"`
	Data ListData `json:"data"` // 使用上面定义的 ListData
}

type Pagination struct {
	Page  int64 `json:"page"`
	Size  int64 `json:"size"`
	Total int64 `json:"total"`
}

type Tweet struct {
	Tid          int64    `json:"tid"`
	Uid          int64    `json:"uid"`
	Content      string   `json:"content"`
	MediaUrls    []string `json:"mediaUrls"`
	Tags         []string `json:"tags"`
	IsPublic     bool     `json:"isPublic"`
	CreatedAt    int64    `json:"createdAt"`
	IsDeleted    bool     `json:"is_deleted"`
	LikeCount    int64    `json:"likeCount"`
	CommentCount int64    `json:"commentCount"`
}
