// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2

package handler

import (
	"net/http"

	content "gozeroX/app/contentService/cmd/api/internal/handler/content"
	"gozeroX/app/contentService/cmd/api/internal/svc"
	"gozeroX/pkg/jwt"
	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {

	jwtMiddleware := jwt.NewJwtMiddleware(serverCtx.Config.JwtAuth.AccessSecret)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/createTweet",
				Handler: jwtMiddleware.Handle(content.CreateTweetHandler(serverCtx)),
			},
			{
				Method:  http.MethodDelete,
				Path:    "/deleteTweet",
				Handler: jwtMiddleware.Handle(content.DeleteTweetHandler(serverCtx)),
			},
			{
				Method:  http.MethodGet,
				Path:    "/listTweetsUid",
				Handler: jwtMiddleware.Handle(content.ListTweetsHandler(serverCtx)),
			},
		},
		rest.WithPrefix("/contentService/v1"),
	)
}
