// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1
// Source: noticeService.proto

package notice

import (
	"context"

	"gozeroX/app/noticeService/cmd/rpc/pb"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	GetNoticesReq      = pb.GetNoticesReq
	GetNoticesResp     = pb.GetNoticesResp
	GetUnreadCountReq  = pb.GetUnreadCountReq
	GetUnreadCountResp = pb.GetUnreadCountResp
	MarkReadReq        = pb.MarkReadReq
	MarkReadResp       = pb.MarkReadResp
	NoticeCommentInfo  = pb.NoticeCommentInfo
	NoticeLikeInfo     = pb.NoticeLikeInfo

	Notice interface {
		// 获取通知列表（点赞+评论混合）
		GetNotices(ctx context.Context, in *GetNoticesReq, opts ...grpc.CallOption) (*GetNoticesResp, error)
		// 获取未读通知数
		GetUnreadCount(ctx context.Context, in *GetUnreadCountReq, opts ...grpc.CallOption) (*GetUnreadCountResp, error)
		// 标记通知已读
		MarkRead(ctx context.Context, in *MarkReadReq, opts ...grpc.CallOption) (*MarkReadResp, error)
	}

	defaultNotice struct {
		cli zrpc.Client
	}
)

func NewNotice(cli zrpc.Client) Notice {
	return &defaultNotice{
		cli: cli,
	}
}

// 获取通知列表（点赞+评论混合）
func (m *defaultNotice) GetNotices(ctx context.Context, in *GetNoticesReq, opts ...grpc.CallOption) (*GetNoticesResp, error) {
	client := pb.NewNoticeClient(m.cli.Conn())
	return client.GetNotices(ctx, in, opts...)
}

// 获取未读通知数
func (m *defaultNotice) GetUnreadCount(ctx context.Context, in *GetUnreadCountReq, opts ...grpc.CallOption) (*GetUnreadCountResp, error) {
	client := pb.NewNoticeClient(m.cli.Conn())
	return client.GetUnreadCount(ctx, in, opts...)
}

// 标记通知已读
func (m *defaultNotice) MarkRead(ctx context.Context, in *MarkReadReq, opts ...grpc.CallOption) (*MarkReadResp, error) {
	client := pb.NewNoticeClient(m.cli.Conn())
	return client.MarkRead(ctx, in, opts...)
}
