// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2
// Source: userCenter.proto

package server

import (
	"context"

	"gozeroX/app/usercenter/cmd/rpc/internal/logic"
	"gozeroX/app/usercenter/cmd/rpc/internal/svc"
	"gozeroX/app/usercenter/cmd/rpc/pb"
)

type UserCenterServer struct {
	svcCtx *svc.ServiceContext
	pb.UnimplementedUserCenterServer
}

func NewUserCenterServer(svcCtx *svc.ServiceContext) *UserCenterServer {
	return &UserCenterServer{
		svcCtx: svcCtx,
	}
}

// 用户注册（返回token）
func (s *UserCenterServer) Register(ctx context.Context, in *pb.RegisterReq) (*pb.RegisterResp, error) {
	l := logic.NewRegisterLogic(ctx, s.svcCtx)
	return l.Register(in)
}

// 用户登录（返回user_info + token）
func (s *UserCenterServer) Login(ctx context.Context, in *pb.LoginReq) (*pb.LoginResp, error) {
	l := logic.NewLoginLogic(ctx, s.svcCtx)
	return l.Login(in)
}

// 获取用户信息
func (s *UserCenterServer) GetUserInfo(ctx context.Context, in *pb.GetUserInfoReq) (*pb.GetUserInfoResp, error) {
	l := logic.NewGetUserInfoLogic(ctx, s.svcCtx)
	return l.GetUserInfo(in)
}

// 批量获取用户简要信息（给互动微服务的）
func (s *UserCenterServer) BatchGetUserBrief(ctx context.Context, in *pb.BatchUserBriefReq) (*pb.BatchUserBriefResp, error) {
	l := logic.NewBatchGetUserBriefLogic(ctx, s.svcCtx)
	return l.BatchGetUserBrief(in)
}

// 更新用户统计（给内容微服务和互动微服务）
func (s *UserCenterServer) UpdateStatsUid(ctx context.Context, in *pb.UpdateStatsUidReq) (*pb.UpdateStatsUidResp, error) {
	l := logic.NewUpdateStatsUidLogic(ctx, s.svcCtx)
	return l.UpdateStatsUid(in)
}
