// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1
// Source: contentService.proto

package server

import (
	"context"

	"gozeroX/app/contentService/cmd/rpc/internal/logic"
	"gozeroX/app/contentService/cmd/rpc/internal/svc"
	"gozeroX/app/contentService/cmd/rpc/pb"
)

type ContentServer struct {
	svcCtx *svc.ServiceContext
	pb.UnimplementedContentServer
}

func NewContentServer(svcCtx *svc.ServiceContext) *ContentServer {
	return &ContentServer{
		svcCtx: svcCtx,
	}
}

// 用户主页推文列表（游标分页）
func (s *ContentServer) ListTweetsUid(ctx context.Context, in *pb.ListTweetsUidReq) (*pb.ListTweetsUidResp, error) {
	l := logic.NewListTweetsUidLogic(ctx, s.svcCtx)
	return l.ListTweetsUid(in)
}

// 单条推文查询
func (s *ContentServer) GetTweetBySnowTid(ctx context.Context, in *pb.GetTweetBySnowTidReq) (*pb.GetTweetBySnowTidResp, error) {
	l := logic.NewGetTweetBySnowTidLogic(ctx, s.svcCtx)
	return l.GetTweetBySnowTid(in)
}

// 批量推文查询
func (s *ContentServer) BatchGetTweets(ctx context.Context, in *pb.BatchGetTweetsReq) (*pb.BatchGetTweetsResp, error) {
	l := logic.NewBatchGetTweetsLogic(ctx, s.svcCtx)
	return l.BatchGetTweets(in)
}

// 创建推文
func (s *ContentServer) CreateTweet(ctx context.Context, in *pb.CreateTweetReq) (*pb.CreateTweetResp, error) {
	l := logic.NewCreateTweetLogic(ctx, s.svcCtx)
	return l.CreateTweet(in)
}

// 删除推文
func (s *ContentServer) DeleteTweet(ctx context.Context, in *pb.DeleteTweetReq) (*pb.DeleteTweetResp, error) {
	l := logic.NewDeleteTweetLogic(ctx, s.svcCtx)
	return l.DeleteTweet(in)
}

// 更新推文统计字段（like_count / comment_count）
func (s *ContentServer) UpdateTweetStats(ctx context.Context, in *pb.UpdateTweetStatsReq) (*pb.UpdateTweetStatsResp, error) {
	l := logic.NewUpdateTweetStatsLogic(ctx, s.svcCtx)
	return l.UpdateTweetStats(in)
}
