// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2
// Source: contentService.proto

package server

import (
	"context"

	"gozeroX/app/contentService/cmd/rpc/internal/logic"
	"gozeroX/app/contentService/cmd/rpc/internal/svc"
	"gozeroX/app/contentService/cmd/rpc/pb"
)

type ContentServer struct {
	svcCtx *svc.ServiceContext
	pb.UnimplementedContentServer
}

func NewContentServer(svcCtx *svc.ServiceContext) *ContentServer {
	return &ContentServer{
		svcCtx: svcCtx,
	}
}

// 1. 用户主页推文列表（带权限过滤）
func (s *ContentServer) ListTweetsUid(ctx context.Context, in *pb.ListTweetsUidReq) (*pb.ListTweetsUidResp, error) {
	l := logic.NewListTweetsUidLogic(ctx, s.svcCtx)
	return l.ListTweetsUid(in)
}

// 2. 单条推文查询
func (s *ContentServer) GetTweetByTid(ctx context.Context, in *pb.GetTweetByTidReq) (*pb.GetTweetByTidResp, error) {
	l := logic.NewGetTweetByTidLogic(ctx, s.svcCtx)
	return l.GetTweetByTid(in)
}

// 3. 批量推文查询（仅返回公开的）
func (s *ContentServer) BatchGetTweets(ctx context.Context, in *pb.BatchGetTweetsReq) (*pb.BatchGetTweetsResp, error) {
	l := logic.NewBatchGetTweetsLogic(ctx, s.svcCtx)
	return l.BatchGetTweets(in)
}

// 4. 创建推文（供API调用）
func (s *ContentServer) CreateTweet(ctx context.Context, in *pb.CreateTweetReq) (*pb.CreateTweetResp, error) {
	l := logic.NewCreateTweetLogic(ctx, s.svcCtx)
	return l.CreateTweet(in)
}

// 5. 删除推文（供API调用）
func (s *ContentServer) DeleteTweet(ctx context.Context, in *pb.DeleteTweetReq) (*pb.DeleteTweetResp, error) {
	l := logic.NewDeleteTweetLogic(ctx, s.svcCtx)
	return l.DeleteTweet(in)
}
