// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.10.1

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/cache"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	noticeLikeFieldNames          = builder.RawFieldNames(&NoticeLike{}, true)
	noticeLikeRows                = strings.Join(noticeLikeFieldNames, ",")
	noticeLikeRowsExpectAutoSet   = strings.Join(stringx.Remove(noticeLikeFieldNames, "create_at", "create_time", "created_at", "update_at", "update_time", "updated_at"), ",")
	noticeLikeRowsWithPlaceHolder = builder.PostgreSqlJoin(stringx.Remove(noticeLikeFieldNames, "snow_nid", "create_at", "create_time", "created_at", "update_at", "update_time", "updated_at"))

	cachePublicNoticeLikeSnowNidPrefix               = "cache:public:noticeLike:snowNid:"
	cachePublicNoticeLikeUidTargetTypeTargetIdPrefix = "cache:public:noticeLike:uid:targetType:targetId:"
)

type (
	noticeLikeModel interface {
		Insert(ctx context.Context, data *NoticeLike) (sql.Result, error)
		FindOne(ctx context.Context, snowNid int64) (*NoticeLike, error)
		FindOneByUidTargetTypeTargetId(ctx context.Context, uid int64, targetType int64, targetId int64) (*NoticeLike, error)
		Update(ctx context.Context, data *NoticeLike) error
		Delete(ctx context.Context, snowNid int64) error
	}

	defaultNoticeLikeModel struct {
		sqlc.CachedConn
		table string
	}

	NoticeLike struct {
		SnowNid     int64 `db:"snow_nid"`     // 通知ID（雪花算法）
		TargetType  int64 `db:"target_type"`  // 目标类型：0=推文点赞, 1=评论点赞
		TargetId    int64 `db:"target_id"`    // 目标ID：推文ID或评论ID
		SnowTid     int64 `db:"snow_tid"`     // 所在推文ID
		RootId      int64 `db:"root_id"`      // 根评论ID（推文点赞为0）
		RecentUid1  int64 `db:"recent_uid_1"` // 最近点赞者UID
		RecentUid2  int64 `db:"recent_uid_2"` // 倒数第二点赞者UID
		Uid         int64 `db:"uid"`          // 通知接收者UID
		TotalCount  int64 `db:"total_count"`  // 累计点赞数
		RecentCount int64 `db:"recent_count"` // 自上次查看以来的新增点赞数
		IsRead      int64 `db:"is_read"`      // 是否已读：0未读, 1已读
		CreatedAt   int64 `db:"created_at"`   // 创建时间（毫秒级时间戳）
		UpdatedAt   int64 `db:"updated_at"`   // 更新时间（毫秒级时间戳）
		Status      int64 `db:"status"`       // 状态：0正常, 1删除
	}
)

func newNoticeLikeModel(conn sqlx.SqlConn, c cache.CacheConf, opts ...cache.Option) *defaultNoticeLikeModel {
	return &defaultNoticeLikeModel{
		CachedConn: sqlc.NewConn(conn, c, opts...),
		table:      `"public"."notice_like"`,
	}
}

func (m *defaultNoticeLikeModel) Delete(ctx context.Context, snowNid int64) error {
	data, err := m.FindOne(ctx, snowNid)
	if err != nil {
		return err
	}

	publicNoticeLikeSnowNidKey := fmt.Sprintf("%s%v", cachePublicNoticeLikeSnowNidPrefix, snowNid)
	publicNoticeLikeUidTargetTypeTargetIdKey := fmt.Sprintf("%s%v:%v:%v", cachePublicNoticeLikeUidTargetTypeTargetIdPrefix, data.Uid, data.TargetType, data.TargetId)
	_, err = m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("delete from %s where snow_nid = $1", m.table)
		return conn.ExecCtx(ctx, query, snowNid)
	}, publicNoticeLikeSnowNidKey, publicNoticeLikeUidTargetTypeTargetIdKey)
	return err
}

func (m *defaultNoticeLikeModel) FindOne(ctx context.Context, snowNid int64) (*NoticeLike, error) {
	publicNoticeLikeSnowNidKey := fmt.Sprintf("%s%v", cachePublicNoticeLikeSnowNidPrefix, snowNid)
	var resp NoticeLike
	err := m.QueryRowCtx(ctx, &resp, publicNoticeLikeSnowNidKey, func(ctx context.Context, conn sqlx.SqlConn, v any) error {
		query := fmt.Sprintf("select %s from %s where snow_nid = $1 limit 1", noticeLikeRows, m.table)
		return conn.QueryRowCtx(ctx, v, query, snowNid)
	})
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultNoticeLikeModel) FindOneByUidTargetTypeTargetId(ctx context.Context, uid int64, targetType int64, targetId int64) (*NoticeLike, error) {
	publicNoticeLikeUidTargetTypeTargetIdKey := fmt.Sprintf("%s%v:%v:%v", cachePublicNoticeLikeUidTargetTypeTargetIdPrefix, uid, targetType, targetId)
	var resp NoticeLike
	err := m.QueryRowIndexCtx(ctx, &resp, publicNoticeLikeUidTargetTypeTargetIdKey, m.formatPrimary, func(ctx context.Context, conn sqlx.SqlConn, v any) (i any, e error) {
		query := fmt.Sprintf("select %s from %s where uid = $1 and target_type = $2 and target_id = $3 limit 1", noticeLikeRows, m.table)
		if err := conn.QueryRowCtx(ctx, &resp, query, uid, targetType, targetId); err != nil {
			return nil, err
		}
		return resp.SnowNid, nil
	}, m.queryPrimary)
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultNoticeLikeModel) Insert(ctx context.Context, data *NoticeLike) (sql.Result, error) {
	publicNoticeLikeSnowNidKey := fmt.Sprintf("%s%v", cachePublicNoticeLikeSnowNidPrefix, data.SnowNid)
	publicNoticeLikeUidTargetTypeTargetIdKey := fmt.Sprintf("%s%v:%v:%v", cachePublicNoticeLikeUidTargetTypeTargetIdPrefix, data.Uid, data.TargetType, data.TargetId)
	ret, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("insert into %s (%s) values ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12)", m.table, noticeLikeRowsExpectAutoSet)
		return conn.ExecCtx(ctx, query, data.SnowNid, data.TargetType, data.TargetId, data.SnowTid, data.RootId, data.RecentUid1, data.RecentUid2, data.Uid, data.TotalCount, data.RecentCount, data.IsRead, data.Status)
	}, publicNoticeLikeSnowNidKey, publicNoticeLikeUidTargetTypeTargetIdKey)
	return ret, err
}

func (m *defaultNoticeLikeModel) Update(ctx context.Context, newData *NoticeLike) error {
	data, err := m.FindOne(ctx, newData.SnowNid)
	if err != nil {
		return err
	}

	publicNoticeLikeSnowNidKey := fmt.Sprintf("%s%v", cachePublicNoticeLikeSnowNidPrefix, data.SnowNid)
	publicNoticeLikeUidTargetTypeTargetIdKey := fmt.Sprintf("%s%v:%v:%v", cachePublicNoticeLikeUidTargetTypeTargetIdPrefix, data.Uid, data.TargetType, data.TargetId)
	_, err = m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("update %s set %s where snow_nid = $1", m.table, noticeLikeRowsWithPlaceHolder)
		return conn.ExecCtx(ctx, query, newData.SnowNid, newData.TargetType, newData.TargetId, newData.SnowTid, newData.RootId, newData.RecentUid1, newData.RecentUid2, newData.Uid, newData.TotalCount, newData.RecentCount, newData.IsRead, newData.Status)
	}, publicNoticeLikeSnowNidKey, publicNoticeLikeUidTargetTypeTargetIdKey)
	return err
}

func (m *defaultNoticeLikeModel) formatPrimary(primary any) string {
	return fmt.Sprintf("%s%v", cachePublicNoticeLikeSnowNidPrefix, primary)
}

func (m *defaultNoticeLikeModel) queryPrimary(ctx context.Context, conn sqlx.SqlConn, v, primary any) error {
	query := fmt.Sprintf("select %s from %s where snow_nid = $1 limit 1", noticeLikeRows, m.table)
	return conn.QueryRowCtx(ctx, v, query, primary)
}

func (m *defaultNoticeLikeModel) tableName() string {
	return m.table
}
