// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: pb/contentService.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ========== 基础结构体 ==========
type Tweet struct {
	state        protoimpl.MessageState `protogen:"open.v1"`
	SnowTid      int64                  `protobuf:"varint,1,opt,name=snow_tid,json=snowTid,proto3" json:"snow_tid,omitempty"`                // 推文ID（雪花算法）
	Uid          int64                  `protobuf:"varint,2,opt,name=uid,proto3" json:"uid,omitempty"`                                       // 发布用户ID
	Content      string                 `protobuf:"bytes,3,opt,name=content,proto3" json:"content,omitempty"`                                // 推文内容
	MediaUrls    []string               `protobuf:"bytes,4,rep,name=media_urls,json=mediaUrls,proto3" json:"media_urls,omitempty"`           // 图片链接
	Tags         []string               `protobuf:"bytes,5,rep,name=tags,proto3" json:"tags,omitempty"`                                      // 标签
	IsPublic     bool                   `protobuf:"varint,6,opt,name=is_public,json=isPublic,proto3" json:"is_public,omitempty"`             // 是否公开
	CreatedAt    int64                  `protobuf:"varint,7,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`          // 创建时间（毫秒时间戳）
	LikeCount    int64                  `protobuf:"varint,8,opt,name=like_count,json=likeCount,proto3" json:"like_count,omitempty"`          // 点赞数
	CommentCount int64                  `protobuf:"varint,9,opt,name=comment_count,json=commentCount,proto3" json:"comment_count,omitempty"` // 评论数
	Status       int64                  `protobuf:"varint,10,opt,name=status,proto3" json:"status,omitempty"`                                // 推文状态（0正常，1删除，2审核）
	// 以下字段不存储在数据库中，通过关联查询获取
	Nickname      string `protobuf:"bytes,11,opt,name=nickname,proto3" json:"nickname,omitempty"` // 发布用户昵称
	Avatar        string `protobuf:"bytes,12,opt,name=avatar,proto3" json:"avatar,omitempty"`     // 发布用户头像
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Tweet) Reset() {
	*x = Tweet{}
	mi := &file_pb_contentService_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Tweet) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Tweet) ProtoMessage() {}

func (x *Tweet) ProtoReflect() protoreflect.Message {
	mi := &file_pb_contentService_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Tweet.ProtoReflect.Descriptor instead.
func (*Tweet) Descriptor() ([]byte, []int) {
	return file_pb_contentService_proto_rawDescGZIP(), []int{0}
}

func (x *Tweet) GetSnowTid() int64 {
	if x != nil {
		return x.SnowTid
	}
	return 0
}

func (x *Tweet) GetUid() int64 {
	if x != nil {
		return x.Uid
	}
	return 0
}

func (x *Tweet) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *Tweet) GetMediaUrls() []string {
	if x != nil {
		return x.MediaUrls
	}
	return nil
}

func (x *Tweet) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *Tweet) GetIsPublic() bool {
	if x != nil {
		return x.IsPublic
	}
	return false
}

func (x *Tweet) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *Tweet) GetLikeCount() int64 {
	if x != nil {
		return x.LikeCount
	}
	return 0
}

func (x *Tweet) GetCommentCount() int64 {
	if x != nil {
		return x.CommentCount
	}
	return 0
}

func (x *Tweet) GetStatus() int64 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *Tweet) GetNickname() string {
	if x != nil {
		return x.Nickname
	}
	return ""
}

func (x *Tweet) GetAvatar() string {
	if x != nil {
		return x.Avatar
	}
	return ""
}

// ========== 用户主页推文列表查询（游标分页） ==========
type ListTweetsUidReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	QueryUid      int64                  `protobuf:"varint,1,opt,name=query_uid,json=queryUid,proto3" json:"query_uid,omitempty"` // 要查询的用户ID
	IsPublic      bool                   `protobuf:"varint,2,opt,name=is_public,json=isPublic,proto3" json:"is_public,omitempty"` // 是否包含私密推文（true=包含，false=仅公开）
	Cursor        int64                  `protobuf:"varint,3,opt,name=cursor,proto3" json:"cursor,omitempty"`                     // 游标：上次最后一条的created_at，首次传0
	Limit         int64                  `protobuf:"varint,4,opt,name=limit,proto3" json:"limit,omitempty"`                       // 每页条数
	Sort          int64                  `protobuf:"varint,5,opt,name=sort,proto3" json:"sort,omitempty"`                         // 排序(0=DESC, 1=ASC)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListTweetsUidReq) Reset() {
	*x = ListTweetsUidReq{}
	mi := &file_pb_contentService_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListTweetsUidReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTweetsUidReq) ProtoMessage() {}

func (x *ListTweetsUidReq) ProtoReflect() protoreflect.Message {
	mi := &file_pb_contentService_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTweetsUidReq.ProtoReflect.Descriptor instead.
func (*ListTweetsUidReq) Descriptor() ([]byte, []int) {
	return file_pb_contentService_proto_rawDescGZIP(), []int{1}
}

func (x *ListTweetsUidReq) GetQueryUid() int64 {
	if x != nil {
		return x.QueryUid
	}
	return 0
}

func (x *ListTweetsUidReq) GetIsPublic() bool {
	if x != nil {
		return x.IsPublic
	}
	return false
}

func (x *ListTweetsUidReq) GetCursor() int64 {
	if x != nil {
		return x.Cursor
	}
	return 0
}

func (x *ListTweetsUidReq) GetLimit() int64 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *ListTweetsUidReq) GetSort() int64 {
	if x != nil {
		return x.Sort
	}
	return 0
}

type ListTweetsUidResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int64                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Msg           string                 `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	Tweets        []*Tweet               `protobuf:"bytes,3,rep,name=tweets,proto3" json:"tweets,omitempty"`
	Total         int64                  `protobuf:"varint,4,opt,name=total,proto3" json:"total,omitempty"` // 总数（用于判断是否还有下一页）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListTweetsUidResp) Reset() {
	*x = ListTweetsUidResp{}
	mi := &file_pb_contentService_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListTweetsUidResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTweetsUidResp) ProtoMessage() {}

func (x *ListTweetsUidResp) ProtoReflect() protoreflect.Message {
	mi := &file_pb_contentService_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTweetsUidResp.ProtoReflect.Descriptor instead.
func (*ListTweetsUidResp) Descriptor() ([]byte, []int) {
	return file_pb_contentService_proto_rawDescGZIP(), []int{2}
}

func (x *ListTweetsUidResp) GetCode() int64 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *ListTweetsUidResp) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

func (x *ListTweetsUidResp) GetTweets() []*Tweet {
	if x != nil {
		return x.Tweets
	}
	return nil
}

func (x *ListTweetsUidResp) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

// ========== 单条推文查询 ==========
type GetTweetBySnowTidReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SnowTid       int64                  `protobuf:"varint,1,opt,name=snow_tid,json=snowTid,proto3" json:"snow_tid,omitempty"` // 推文ID（雪花算法）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTweetBySnowTidReq) Reset() {
	*x = GetTweetBySnowTidReq{}
	mi := &file_pb_contentService_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTweetBySnowTidReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTweetBySnowTidReq) ProtoMessage() {}

func (x *GetTweetBySnowTidReq) ProtoReflect() protoreflect.Message {
	mi := &file_pb_contentService_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTweetBySnowTidReq.ProtoReflect.Descriptor instead.
func (*GetTweetBySnowTidReq) Descriptor() ([]byte, []int) {
	return file_pb_contentService_proto_rawDescGZIP(), []int{3}
}

func (x *GetTweetBySnowTidReq) GetSnowTid() int64 {
	if x != nil {
		return x.SnowTid
	}
	return 0
}

type GetTweetBySnowTidResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int64                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Msg           string                 `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	Tweet         *Tweet                 `protobuf:"bytes,3,opt,name=tweet,proto3" json:"tweet,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTweetBySnowTidResp) Reset() {
	*x = GetTweetBySnowTidResp{}
	mi := &file_pb_contentService_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTweetBySnowTidResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTweetBySnowTidResp) ProtoMessage() {}

func (x *GetTweetBySnowTidResp) ProtoReflect() protoreflect.Message {
	mi := &file_pb_contentService_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTweetBySnowTidResp.ProtoReflect.Descriptor instead.
func (*GetTweetBySnowTidResp) Descriptor() ([]byte, []int) {
	return file_pb_contentService_proto_rawDescGZIP(), []int{4}
}

func (x *GetTweetBySnowTidResp) GetCode() int64 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *GetTweetBySnowTidResp) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

func (x *GetTweetBySnowTidResp) GetTweet() *Tweet {
	if x != nil {
		return x.Tweet
	}
	return nil
}

// ========== 批量推文查询 ==========
type BatchGetTweetsReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SnowTids      []int64                `protobuf:"varint,1,rep,packed,name=snow_tids,json=snowTids,proto3" json:"snow_tids,omitempty"` // 推文ID列表
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatchGetTweetsReq) Reset() {
	*x = BatchGetTweetsReq{}
	mi := &file_pb_contentService_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchGetTweetsReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchGetTweetsReq) ProtoMessage() {}

func (x *BatchGetTweetsReq) ProtoReflect() protoreflect.Message {
	mi := &file_pb_contentService_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchGetTweetsReq.ProtoReflect.Descriptor instead.
func (*BatchGetTweetsReq) Descriptor() ([]byte, []int) {
	return file_pb_contentService_proto_rawDescGZIP(), []int{5}
}

func (x *BatchGetTweetsReq) GetSnowTids() []int64 {
	if x != nil {
		return x.SnowTids
	}
	return nil
}

type BatchGetTweetsResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int64                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Msg           string                 `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	Tweets        []*Tweet               `protobuf:"bytes,3,rep,name=tweets,proto3" json:"tweets,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatchGetTweetsResp) Reset() {
	*x = BatchGetTweetsResp{}
	mi := &file_pb_contentService_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchGetTweetsResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchGetTweetsResp) ProtoMessage() {}

func (x *BatchGetTweetsResp) ProtoReflect() protoreflect.Message {
	mi := &file_pb_contentService_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchGetTweetsResp.ProtoReflect.Descriptor instead.
func (*BatchGetTweetsResp) Descriptor() ([]byte, []int) {
	return file_pb_contentService_proto_rawDescGZIP(), []int{6}
}

func (x *BatchGetTweetsResp) GetCode() int64 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *BatchGetTweetsResp) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

func (x *BatchGetTweetsResp) GetTweets() []*Tweet {
	if x != nil {
		return x.Tweets
	}
	return nil
}

// ========== 创建推文 ==========
type CreateTweetReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uid           int64                  `protobuf:"varint,1,opt,name=uid,proto3" json:"uid,omitempty"`
	Content       string                 `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	MediaUrls     []string               `protobuf:"bytes,3,rep,name=media_urls,json=mediaUrls,proto3" json:"media_urls,omitempty"`
	Tags          []string               `protobuf:"bytes,4,rep,name=tags,proto3" json:"tags,omitempty"`
	IsPublic      bool                   `protobuf:"varint,5,opt,name=is_public,json=isPublic,proto3" json:"is_public,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateTweetReq) Reset() {
	*x = CreateTweetReq{}
	mi := &file_pb_contentService_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateTweetReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateTweetReq) ProtoMessage() {}

func (x *CreateTweetReq) ProtoReflect() protoreflect.Message {
	mi := &file_pb_contentService_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateTweetReq.ProtoReflect.Descriptor instead.
func (*CreateTweetReq) Descriptor() ([]byte, []int) {
	return file_pb_contentService_proto_rawDescGZIP(), []int{7}
}

func (x *CreateTweetReq) GetUid() int64 {
	if x != nil {
		return x.Uid
	}
	return 0
}

func (x *CreateTweetReq) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *CreateTweetReq) GetMediaUrls() []string {
	if x != nil {
		return x.MediaUrls
	}
	return nil
}

func (x *CreateTweetReq) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *CreateTweetReq) GetIsPublic() bool {
	if x != nil {
		return x.IsPublic
	}
	return false
}

type CreateTweetResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int64                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Msg           string                 `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	Tweet         *Tweet                 `protobuf:"bytes,3,opt,name=tweet,proto3" json:"tweet,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateTweetResp) Reset() {
	*x = CreateTweetResp{}
	mi := &file_pb_contentService_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateTweetResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateTweetResp) ProtoMessage() {}

func (x *CreateTweetResp) ProtoReflect() protoreflect.Message {
	mi := &file_pb_contentService_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateTweetResp.ProtoReflect.Descriptor instead.
func (*CreateTweetResp) Descriptor() ([]byte, []int) {
	return file_pb_contentService_proto_rawDescGZIP(), []int{8}
}

func (x *CreateTweetResp) GetCode() int64 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *CreateTweetResp) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

func (x *CreateTweetResp) GetTweet() *Tweet {
	if x != nil {
		return x.Tweet
	}
	return nil
}

// ========== 删除推文 ==========
type DeleteTweetReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SnowTid       int64                  `protobuf:"varint,1,opt,name=snow_tid,json=snowTid,proto3" json:"snow_tid,omitempty"` // 推文ID（雪花算法）
	Uid           int64                  `protobuf:"varint,2,opt,name=uid,proto3" json:"uid,omitempty"`                        // 操作用户ID（用于权限校验）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteTweetReq) Reset() {
	*x = DeleteTweetReq{}
	mi := &file_pb_contentService_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteTweetReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteTweetReq) ProtoMessage() {}

func (x *DeleteTweetReq) ProtoReflect() protoreflect.Message {
	mi := &file_pb_contentService_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteTweetReq.ProtoReflect.Descriptor instead.
func (*DeleteTweetReq) Descriptor() ([]byte, []int) {
	return file_pb_contentService_proto_rawDescGZIP(), []int{9}
}

func (x *DeleteTweetReq) GetSnowTid() int64 {
	if x != nil {
		return x.SnowTid
	}
	return 0
}

func (x *DeleteTweetReq) GetUid() int64 {
	if x != nil {
		return x.Uid
	}
	return 0
}

type DeleteTweetResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int64                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Msg           string                 `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteTweetResp) Reset() {
	*x = DeleteTweetResp{}
	mi := &file_pb_contentService_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteTweetResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteTweetResp) ProtoMessage() {}

func (x *DeleteTweetResp) ProtoReflect() protoreflect.Message {
	mi := &file_pb_contentService_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteTweetResp.ProtoReflect.Descriptor instead.
func (*DeleteTweetResp) Descriptor() ([]byte, []int) {
	return file_pb_contentService_proto_rawDescGZIP(), []int{10}
}

func (x *DeleteTweetResp) GetCode() int64 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *DeleteTweetResp) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

// ========== 更新推文统计 ==========
type UpdateTweetStatsReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SnowTid       int64                  `protobuf:"varint,1,opt,name=snow_tid,json=snowTid,proto3" json:"snow_tid,omitempty"`
	UpdateType    int64                  `protobuf:"varint,2,opt,name=update_type,json=updateType,proto3" json:"update_type,omitempty"` // 1=like_count, 2=comment_count
	Delta         int64                  `protobuf:"varint,3,opt,name=delta,proto3" json:"delta,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateTweetStatsReq) Reset() {
	*x = UpdateTweetStatsReq{}
	mi := &file_pb_contentService_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateTweetStatsReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateTweetStatsReq) ProtoMessage() {}

func (x *UpdateTweetStatsReq) ProtoReflect() protoreflect.Message {
	mi := &file_pb_contentService_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateTweetStatsReq.ProtoReflect.Descriptor instead.
func (*UpdateTweetStatsReq) Descriptor() ([]byte, []int) {
	return file_pb_contentService_proto_rawDescGZIP(), []int{11}
}

func (x *UpdateTweetStatsReq) GetSnowTid() int64 {
	if x != nil {
		return x.SnowTid
	}
	return 0
}

func (x *UpdateTweetStatsReq) GetUpdateType() int64 {
	if x != nil {
		return x.UpdateType
	}
	return 0
}

func (x *UpdateTweetStatsReq) GetDelta() int64 {
	if x != nil {
		return x.Delta
	}
	return 0
}

type UpdateTweetStatsResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int64                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Msg           string                 `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateTweetStatsResp) Reset() {
	*x = UpdateTweetStatsResp{}
	mi := &file_pb_contentService_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateTweetStatsResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateTweetStatsResp) ProtoMessage() {}

func (x *UpdateTweetStatsResp) ProtoReflect() protoreflect.Message {
	mi := &file_pb_contentService_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateTweetStatsResp.ProtoReflect.Descriptor instead.
func (*UpdateTweetStatsResp) Descriptor() ([]byte, []int) {
	return file_pb_contentService_proto_rawDescGZIP(), []int{12}
}

func (x *UpdateTweetStatsResp) GetCode() int64 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *UpdateTweetStatsResp) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

var File_pb_contentService_proto protoreflect.FileDescriptor

const file_pb_contentService_proto_rawDesc = "" +
	"\n" +
	"\x17pb/contentService.proto\x12\x02pb\"\xcd\x02\n" +
	"\x05Tweet\x12\x19\n" +
	"\bsnow_tid\x18\x01 \x01(\x03R\asnowTid\x12\x10\n" +
	"\x03uid\x18\x02 \x01(\x03R\x03uid\x12\x18\n" +
	"\acontent\x18\x03 \x01(\tR\acontent\x12\x1d\n" +
	"\n" +
	"media_urls\x18\x04 \x03(\tR\tmediaUrls\x12\x12\n" +
	"\x04tags\x18\x05 \x03(\tR\x04tags\x12\x1b\n" +
	"\tis_public\x18\x06 \x01(\bR\bisPublic\x12\x1d\n" +
	"\n" +
	"created_at\x18\a \x01(\x03R\tcreatedAt\x12\x1d\n" +
	"\n" +
	"like_count\x18\b \x01(\x03R\tlikeCount\x12#\n" +
	"\rcomment_count\x18\t \x01(\x03R\fcommentCount\x12\x16\n" +
	"\x06status\x18\n" +
	" \x01(\x03R\x06status\x12\x1a\n" +
	"\bnickname\x18\v \x01(\tR\bnickname\x12\x16\n" +
	"\x06avatar\x18\f \x01(\tR\x06avatar\"\x8e\x01\n" +
	"\x10ListTweetsUidReq\x12\x1b\n" +
	"\tquery_uid\x18\x01 \x01(\x03R\bqueryUid\x12\x1b\n" +
	"\tis_public\x18\x02 \x01(\bR\bisPublic\x12\x16\n" +
	"\x06cursor\x18\x03 \x01(\x03R\x06cursor\x12\x14\n" +
	"\x05limit\x18\x04 \x01(\x03R\x05limit\x12\x12\n" +
	"\x04sort\x18\x05 \x01(\x03R\x04sort\"r\n" +
	"\x11ListTweetsUidResp\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x03R\x04code\x12\x10\n" +
	"\x03msg\x18\x02 \x01(\tR\x03msg\x12!\n" +
	"\x06tweets\x18\x03 \x03(\v2\t.pb.TweetR\x06tweets\x12\x14\n" +
	"\x05total\x18\x04 \x01(\x03R\x05total\"1\n" +
	"\x14GetTweetBySnowTidReq\x12\x19\n" +
	"\bsnow_tid\x18\x01 \x01(\x03R\asnowTid\"^\n" +
	"\x15GetTweetBySnowTidResp\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x03R\x04code\x12\x10\n" +
	"\x03msg\x18\x02 \x01(\tR\x03msg\x12\x1f\n" +
	"\x05tweet\x18\x03 \x01(\v2\t.pb.TweetR\x05tweet\"0\n" +
	"\x11BatchGetTweetsReq\x12\x1b\n" +
	"\tsnow_tids\x18\x01 \x03(\x03R\bsnowTids\"]\n" +
	"\x12BatchGetTweetsResp\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x03R\x04code\x12\x10\n" +
	"\x03msg\x18\x02 \x01(\tR\x03msg\x12!\n" +
	"\x06tweets\x18\x03 \x03(\v2\t.pb.TweetR\x06tweets\"\x8c\x01\n" +
	"\x0eCreateTweetReq\x12\x10\n" +
	"\x03uid\x18\x01 \x01(\x03R\x03uid\x12\x18\n" +
	"\acontent\x18\x02 \x01(\tR\acontent\x12\x1d\n" +
	"\n" +
	"media_urls\x18\x03 \x03(\tR\tmediaUrls\x12\x12\n" +
	"\x04tags\x18\x04 \x03(\tR\x04tags\x12\x1b\n" +
	"\tis_public\x18\x05 \x01(\bR\bisPublic\"X\n" +
	"\x0fCreateTweetResp\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x03R\x04code\x12\x10\n" +
	"\x03msg\x18\x02 \x01(\tR\x03msg\x12\x1f\n" +
	"\x05tweet\x18\x03 \x01(\v2\t.pb.TweetR\x05tweet\"=\n" +
	"\x0eDeleteTweetReq\x12\x19\n" +
	"\bsnow_tid\x18\x01 \x01(\x03R\asnowTid\x12\x10\n" +
	"\x03uid\x18\x02 \x01(\x03R\x03uid\"7\n" +
	"\x0fDeleteTweetResp\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x03R\x04code\x12\x10\n" +
	"\x03msg\x18\x02 \x01(\tR\x03msg\"g\n" +
	"\x13UpdateTweetStatsReq\x12\x19\n" +
	"\bsnow_tid\x18\x01 \x01(\x03R\asnowTid\x12\x1f\n" +
	"\vupdate_type\x18\x02 \x01(\x03R\n" +
	"updateType\x12\x14\n" +
	"\x05delta\x18\x03 \x01(\x03R\x05delta\"<\n" +
	"\x14UpdateTweetStatsResp\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x03R\x04code\x12\x10\n" +
	"\x03msg\x18\x02 \x01(\tR\x03msg2\x89\x03\n" +
	"\aContent\x12<\n" +
	"\rListTweetsUid\x12\x14.pb.ListTweetsUidReq\x1a\x15.pb.ListTweetsUidResp\x12H\n" +
	"\x11GetTweetBySnowTid\x12\x18.pb.GetTweetBySnowTidReq\x1a\x19.pb.GetTweetBySnowTidResp\x12?\n" +
	"\x0eBatchGetTweets\x12\x15.pb.BatchGetTweetsReq\x1a\x16.pb.BatchGetTweetsResp\x126\n" +
	"\vCreateTweet\x12\x12.pb.CreateTweetReq\x1a\x13.pb.CreateTweetResp\x126\n" +
	"\vDeleteTweet\x12\x12.pb.DeleteTweetReq\x1a\x13.pb.DeleteTweetResp\x12E\n" +
	"\x10UpdateTweetStats\x12\x17.pb.UpdateTweetStatsReq\x1a\x18.pb.UpdateTweetStatsRespB\x06Z\x04./pbb\x06proto3"

var (
	file_pb_contentService_proto_rawDescOnce sync.Once
	file_pb_contentService_proto_rawDescData []byte
)

func file_pb_contentService_proto_rawDescGZIP() []byte {
	file_pb_contentService_proto_rawDescOnce.Do(func() {
		file_pb_contentService_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pb_contentService_proto_rawDesc), len(file_pb_contentService_proto_rawDesc)))
	})
	return file_pb_contentService_proto_rawDescData
}

var file_pb_contentService_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_pb_contentService_proto_goTypes = []any{
	(*Tweet)(nil),                 // 0: pb.Tweet
	(*ListTweetsUidReq)(nil),      // 1: pb.ListTweetsUidReq
	(*ListTweetsUidResp)(nil),     // 2: pb.ListTweetsUidResp
	(*GetTweetBySnowTidReq)(nil),  // 3: pb.GetTweetBySnowTidReq
	(*GetTweetBySnowTidResp)(nil), // 4: pb.GetTweetBySnowTidResp
	(*BatchGetTweetsReq)(nil),     // 5: pb.BatchGetTweetsReq
	(*BatchGetTweetsResp)(nil),    // 6: pb.BatchGetTweetsResp
	(*CreateTweetReq)(nil),        // 7: pb.CreateTweetReq
	(*CreateTweetResp)(nil),       // 8: pb.CreateTweetResp
	(*DeleteTweetReq)(nil),        // 9: pb.DeleteTweetReq
	(*DeleteTweetResp)(nil),       // 10: pb.DeleteTweetResp
	(*UpdateTweetStatsReq)(nil),   // 11: pb.UpdateTweetStatsReq
	(*UpdateTweetStatsResp)(nil),  // 12: pb.UpdateTweetStatsResp
}
var file_pb_contentService_proto_depIdxs = []int32{
	0,  // 0: pb.ListTweetsUidResp.tweets:type_name -> pb.Tweet
	0,  // 1: pb.GetTweetBySnowTidResp.tweet:type_name -> pb.Tweet
	0,  // 2: pb.BatchGetTweetsResp.tweets:type_name -> pb.Tweet
	0,  // 3: pb.CreateTweetResp.tweet:type_name -> pb.Tweet
	1,  // 4: pb.Content.ListTweetsUid:input_type -> pb.ListTweetsUidReq
	3,  // 5: pb.Content.GetTweetBySnowTid:input_type -> pb.GetTweetBySnowTidReq
	5,  // 6: pb.Content.BatchGetTweets:input_type -> pb.BatchGetTweetsReq
	7,  // 7: pb.Content.CreateTweet:input_type -> pb.CreateTweetReq
	9,  // 8: pb.Content.DeleteTweet:input_type -> pb.DeleteTweetReq
	11, // 9: pb.Content.UpdateTweetStats:input_type -> pb.UpdateTweetStatsReq
	2,  // 10: pb.Content.ListTweetsUid:output_type -> pb.ListTweetsUidResp
	4,  // 11: pb.Content.GetTweetBySnowTid:output_type -> pb.GetTweetBySnowTidResp
	6,  // 12: pb.Content.BatchGetTweets:output_type -> pb.BatchGetTweetsResp
	8,  // 13: pb.Content.CreateTweet:output_type -> pb.CreateTweetResp
	10, // 14: pb.Content.DeleteTweet:output_type -> pb.DeleteTweetResp
	12, // 15: pb.Content.UpdateTweetStats:output_type -> pb.UpdateTweetStatsResp
	10, // [10:16] is the sub-list for method output_type
	4,  // [4:10] is the sub-list for method input_type
	4,  // [4:4] is the sub-list for extension type_name
	4,  // [4:4] is the sub-list for extension extendee
	0,  // [0:4] is the sub-list for field type_name
}

func init() { file_pb_contentService_proto_init() }
func file_pb_contentService_proto_init() {
	if File_pb_contentService_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pb_contentService_proto_rawDesc), len(file_pb_contentService_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pb_contentService_proto_goTypes,
		DependencyIndexes: file_pb_contentService_proto_depIdxs,
		MessageInfos:      file_pb_contentService_proto_msgTypes,
	}.Build()
	File_pb_contentService_proto = out.File
	file_pb_contentService_proto_goTypes = nil
	file_pb_contentService_proto_depIdxs = nil
}
