// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v7.34.1
// source: pb/contentService.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Content_ListTweetsUid_FullMethodName     = "/pb.Content/ListTweetsUid"
	Content_GetTweetBySnowTid_FullMethodName = "/pb.Content/GetTweetBySnowTid"
	Content_BatchGetTweets_FullMethodName    = "/pb.Content/BatchGetTweets"
	Content_CreateTweet_FullMethodName       = "/pb.Content/CreateTweet"
	Content_DeleteTweet_FullMethodName       = "/pb.Content/DeleteTweet"
	Content_UpdateTweetStats_FullMethodName  = "/pb.Content/UpdateTweetStats"
)

// ContentClient is the client API for Content service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// ========== RPC 服务定义 ==========
type ContentClient interface {
	// 用户主页推文列表（游标分页）
	ListTweetsUid(ctx context.Context, in *ListTweetsUidReq, opts ...grpc.CallOption) (*ListTweetsUidResp, error)
	// 单条推文查询
	GetTweetBySnowTid(ctx context.Context, in *GetTweetBySnowTidReq, opts ...grpc.CallOption) (*GetTweetBySnowTidResp, error)
	// 批量推文查询
	BatchGetTweets(ctx context.Context, in *BatchGetTweetsReq, opts ...grpc.CallOption) (*BatchGetTweetsResp, error)
	// 创建推文
	CreateTweet(ctx context.Context, in *CreateTweetReq, opts ...grpc.CallOption) (*CreateTweetResp, error)
	// 删除推文
	DeleteTweet(ctx context.Context, in *DeleteTweetReq, opts ...grpc.CallOption) (*DeleteTweetResp, error)
	// 更新推文统计字段（like_count / comment_count）
	UpdateTweetStats(ctx context.Context, in *UpdateTweetStatsReq, opts ...grpc.CallOption) (*UpdateTweetStatsResp, error)
}

type contentClient struct {
	cc grpc.ClientConnInterface
}

func NewContentClient(cc grpc.ClientConnInterface) ContentClient {
	return &contentClient{cc}
}

func (c *contentClient) ListTweetsUid(ctx context.Context, in *ListTweetsUidReq, opts ...grpc.CallOption) (*ListTweetsUidResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListTweetsUidResp)
	err := c.cc.Invoke(ctx, Content_ListTweetsUid_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *contentClient) GetTweetBySnowTid(ctx context.Context, in *GetTweetBySnowTidReq, opts ...grpc.CallOption) (*GetTweetBySnowTidResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetTweetBySnowTidResp)
	err := c.cc.Invoke(ctx, Content_GetTweetBySnowTid_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *contentClient) BatchGetTweets(ctx context.Context, in *BatchGetTweetsReq, opts ...grpc.CallOption) (*BatchGetTweetsResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BatchGetTweetsResp)
	err := c.cc.Invoke(ctx, Content_BatchGetTweets_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *contentClient) CreateTweet(ctx context.Context, in *CreateTweetReq, opts ...grpc.CallOption) (*CreateTweetResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateTweetResp)
	err := c.cc.Invoke(ctx, Content_CreateTweet_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *contentClient) DeleteTweet(ctx context.Context, in *DeleteTweetReq, opts ...grpc.CallOption) (*DeleteTweetResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteTweetResp)
	err := c.cc.Invoke(ctx, Content_DeleteTweet_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *contentClient) UpdateTweetStats(ctx context.Context, in *UpdateTweetStatsReq, opts ...grpc.CallOption) (*UpdateTweetStatsResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateTweetStatsResp)
	err := c.cc.Invoke(ctx, Content_UpdateTweetStats_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ContentServer is the server API for Content service.
// All implementations must embed UnimplementedContentServer
// for forward compatibility.
//
// ========== RPC 服务定义 ==========
type ContentServer interface {
	// 用户主页推文列表（游标分页）
	ListTweetsUid(context.Context, *ListTweetsUidReq) (*ListTweetsUidResp, error)
	// 单条推文查询
	GetTweetBySnowTid(context.Context, *GetTweetBySnowTidReq) (*GetTweetBySnowTidResp, error)
	// 批量推文查询
	BatchGetTweets(context.Context, *BatchGetTweetsReq) (*BatchGetTweetsResp, error)
	// 创建推文
	CreateTweet(context.Context, *CreateTweetReq) (*CreateTweetResp, error)
	// 删除推文
	DeleteTweet(context.Context, *DeleteTweetReq) (*DeleteTweetResp, error)
	// 更新推文统计字段（like_count / comment_count）
	UpdateTweetStats(context.Context, *UpdateTweetStatsReq) (*UpdateTweetStatsResp, error)
	mustEmbedUnimplementedContentServer()
}

// UnimplementedContentServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedContentServer struct{}

func (UnimplementedContentServer) ListTweetsUid(context.Context, *ListTweetsUidReq) (*ListTweetsUidResp, error) {
	return nil, status.Error(codes.Unimplemented, "method ListTweetsUid not implemented")
}
func (UnimplementedContentServer) GetTweetBySnowTid(context.Context, *GetTweetBySnowTidReq) (*GetTweetBySnowTidResp, error) {
	return nil, status.Error(codes.Unimplemented, "method GetTweetBySnowTid not implemented")
}
func (UnimplementedContentServer) BatchGetTweets(context.Context, *BatchGetTweetsReq) (*BatchGetTweetsResp, error) {
	return nil, status.Error(codes.Unimplemented, "method BatchGetTweets not implemented")
}
func (UnimplementedContentServer) CreateTweet(context.Context, *CreateTweetReq) (*CreateTweetResp, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateTweet not implemented")
}
func (UnimplementedContentServer) DeleteTweet(context.Context, *DeleteTweetReq) (*DeleteTweetResp, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteTweet not implemented")
}
func (UnimplementedContentServer) UpdateTweetStats(context.Context, *UpdateTweetStatsReq) (*UpdateTweetStatsResp, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateTweetStats not implemented")
}
func (UnimplementedContentServer) mustEmbedUnimplementedContentServer() {}
func (UnimplementedContentServer) testEmbeddedByValue()                 {}

// UnsafeContentServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ContentServer will
// result in compilation errors.
type UnsafeContentServer interface {
	mustEmbedUnimplementedContentServer()
}

func RegisterContentServer(s grpc.ServiceRegistrar, srv ContentServer) {
	// If the following call panics, it indicates UnimplementedContentServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Content_ServiceDesc, srv)
}

func _Content_ListTweetsUid_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListTweetsUidReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ContentServer).ListTweetsUid(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Content_ListTweetsUid_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ContentServer).ListTweetsUid(ctx, req.(*ListTweetsUidReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Content_GetTweetBySnowTid_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTweetBySnowTidReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ContentServer).GetTweetBySnowTid(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Content_GetTweetBySnowTid_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ContentServer).GetTweetBySnowTid(ctx, req.(*GetTweetBySnowTidReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Content_BatchGetTweets_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BatchGetTweetsReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ContentServer).BatchGetTweets(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Content_BatchGetTweets_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ContentServer).BatchGetTweets(ctx, req.(*BatchGetTweetsReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Content_CreateTweet_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateTweetReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ContentServer).CreateTweet(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Content_CreateTweet_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ContentServer).CreateTweet(ctx, req.(*CreateTweetReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Content_DeleteTweet_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteTweetReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ContentServer).DeleteTweet(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Content_DeleteTweet_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ContentServer).DeleteTweet(ctx, req.(*DeleteTweetReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Content_UpdateTweetStats_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateTweetStatsReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ContentServer).UpdateTweetStats(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Content_UpdateTweetStats_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ContentServer).UpdateTweetStats(ctx, req.(*UpdateTweetStatsReq))
	}
	return interceptor(ctx, in, info, handler)
}

// Content_ServiceDesc is the grpc.ServiceDesc for Content service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Content_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "pb.Content",
	HandlerType: (*ContentServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListTweetsUid",
			Handler:    _Content_ListTweetsUid_Handler,
		},
		{
			MethodName: "GetTweetBySnowTid",
			Handler:    _Content_GetTweetBySnowTid_Handler,
		},
		{
			MethodName: "BatchGetTweets",
			Handler:    _Content_BatchGetTweets_Handler,
		},
		{
			MethodName: "CreateTweet",
			Handler:    _Content_CreateTweet_Handler,
		},
		{
			MethodName: "DeleteTweet",
			Handler:    _Content_DeleteTweet_Handler,
		},
		{
			MethodName: "UpdateTweetStats",
			Handler:    _Content_UpdateTweetStats_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "pb/contentService.proto",
}
