// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.31.0
// source: pb/contentService.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SortType int32

const (
	SortType_CREATED_AT_DESC SortType = 0 // 对应 API 层 "created_at_desc"
	SortType_CREATED_AT_ASC  SortType = 1 // 对应 API 层 "created_at_asc"
)

// Enum value maps for SortType.
var (
	SortType_name = map[int32]string{
		0: "CREATED_AT_DESC",
		1: "CREATED_AT_ASC",
	}
	SortType_value = map[string]int32{
		"CREATED_AT_DESC": 0,
		"CREATED_AT_ASC":  1,
	}
)

func (x SortType) Enum() *SortType {
	p := new(SortType)
	*p = x
	return p
}

func (x SortType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SortType) Descriptor() protoreflect.EnumDescriptor {
	return file_pb_contentService_proto_enumTypes[0].Descriptor()
}

func (SortType) Type() protoreflect.EnumType {
	return &file_pb_contentService_proto_enumTypes[0]
}

func (x SortType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SortType.Descriptor instead.
func (SortType) EnumDescriptor() ([]byte, []int) {
	return file_pb_contentService_proto_rawDescGZIP(), []int{0}
}

type UpdateTypeTid int32

const (
	UpdateTypeTid_UNKNOWN       UpdateTypeTid = 0
	UpdateTypeTid_Like_COUNT    UpdateTypeTid = 1
	UpdateTypeTid_Comment_COUNT UpdateTypeTid = 2
)

// Enum value maps for UpdateTypeTid.
var (
	UpdateTypeTid_name = map[int32]string{
		0: "UNKNOWN",
		1: "Like_COUNT",
		2: "Comment_COUNT",
	}
	UpdateTypeTid_value = map[string]int32{
		"UNKNOWN":       0,
		"Like_COUNT":    1,
		"Comment_COUNT": 2,
	}
)

func (x UpdateTypeTid) Enum() *UpdateTypeTid {
	p := new(UpdateTypeTid)
	*p = x
	return p
}

func (x UpdateTypeTid) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (UpdateTypeTid) Descriptor() protoreflect.EnumDescriptor {
	return file_pb_contentService_proto_enumTypes[1].Descriptor()
}

func (UpdateTypeTid) Type() protoreflect.EnumType {
	return &file_pb_contentService_proto_enumTypes[1]
}

func (x UpdateTypeTid) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use UpdateTypeTid.Descriptor instead.
func (UpdateTypeTid) EnumDescriptor() ([]byte, []int) {
	return file_pb_contentService_proto_rawDescGZIP(), []int{1}
}

type UpdateFrom int32

const (
	UpdateFrom_UserService           UpdateFrom = 0
	UpdateFrom_ContentService        UpdateFrom = 1
	UpdateFrom_InteractiveService    UpdateFrom = 2
	UpdateFrom_NotifyService         UpdateFrom = 3
	UpdateFrom_ReCmdAndSearchService UpdateFrom = 4
)

// Enum value maps for UpdateFrom.
var (
	UpdateFrom_name = map[int32]string{
		0: "UserService",
		1: "ContentService",
		2: "InteractiveService",
		3: "NotifyService",
		4: "ReCmdAndSearchService",
	}
	UpdateFrom_value = map[string]int32{
		"UserService":           0,
		"ContentService":        1,
		"InteractiveService":    2,
		"NotifyService":         3,
		"ReCmdAndSearchService": 4,
	}
)

func (x UpdateFrom) Enum() *UpdateFrom {
	p := new(UpdateFrom)
	*p = x
	return p
}

func (x UpdateFrom) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (UpdateFrom) Descriptor() protoreflect.EnumDescriptor {
	return file_pb_contentService_proto_enumTypes[2].Descriptor()
}

func (UpdateFrom) Type() protoreflect.EnumType {
	return &file_pb_contentService_proto_enumTypes[2]
}

func (x UpdateFrom) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use UpdateFrom.Descriptor instead.
func (UpdateFrom) EnumDescriptor() ([]byte, []int) {
	return file_pb_contentService_proto_rawDescGZIP(), []int{2}
}

// ========== 基础结构体 ==========
type Tweet struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tid           int64                  `protobuf:"varint,1,opt,name=tid,proto3" json:"tid,omitempty"`                                        // 推文ID
	Uid           int64                  `protobuf:"varint,2,opt,name=uid,proto3" json:"uid,omitempty"`                                        // 发布用户ID
	Content       string                 `protobuf:"bytes,3,opt,name=content,proto3" json:"content,omitempty"`                                 // 推文内容
	MediaUrls     []string               `protobuf:"bytes,4,rep,name=media_urls,json=mediaUrls,proto3" json:"media_urls,omitempty"`            // 图片链接
	Tags          []string               `protobuf:"bytes,5,rep,name=tags,proto3" json:"tags,omitempty"`                                       // 标签
	IsPublic      bool                   `protobuf:"varint,6,opt,name=is_public,json=isPublic,proto3" json:"is_public,omitempty"`              // 是否公开
	CreatedAt     int64                  `protobuf:"varint,7,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`           // 创建时间
	IsDeleted     bool                   `protobuf:"varint,8,opt,name=is_deleted,json=isDeleted,proto3" json:"is_deleted,omitempty"`           // 是否删除
	LikeCount     int64                  `protobuf:"varint,9,opt,name=like_count,json=likeCount,proto3" json:"like_count,omitempty"`           // 点赞数
	CommentCount  int64                  `protobuf:"varint,10,opt,name=comment_count,json=commentCount,proto3" json:"comment_count,omitempty"` // 评论数
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Tweet) Reset() {
	*x = Tweet{}
	mi := &file_pb_contentService_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Tweet) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Tweet) ProtoMessage() {}

func (x *Tweet) ProtoReflect() protoreflect.Message {
	mi := &file_pb_contentService_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Tweet.ProtoReflect.Descriptor instead.
func (*Tweet) Descriptor() ([]byte, []int) {
	return file_pb_contentService_proto_rawDescGZIP(), []int{0}
}

func (x *Tweet) GetTid() int64 {
	if x != nil {
		return x.Tid
	}
	return 0
}

func (x *Tweet) GetUid() int64 {
	if x != nil {
		return x.Uid
	}
	return 0
}

func (x *Tweet) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *Tweet) GetMediaUrls() []string {
	if x != nil {
		return x.MediaUrls
	}
	return nil
}

func (x *Tweet) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *Tweet) GetIsPublic() bool {
	if x != nil {
		return x.IsPublic
	}
	return false
}

func (x *Tweet) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *Tweet) GetIsDeleted() bool {
	if x != nil {
		return x.IsDeleted
	}
	return false
}

func (x *Tweet) GetLikeCount() int64 {
	if x != nil {
		return x.LikeCount
	}
	return 0
}

func (x *Tweet) GetCommentCount() int64 {
	if x != nil {
		return x.CommentCount
	}
	return 0
}

// ========== 用户主页推文列表查询 ==========
type ListTweetsUidReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	QueryUid      int64                  `protobuf:"varint,1,opt,name=query_uid,json=queryUid,proto3" json:"query_uid,omitempty"` // 要查询的用户ID（主页所属用户）
	IsPublic      bool                   `protobuf:"varint,2,opt,name=is_public,json=isPublic,proto3" json:"is_public,omitempty"` // 是否也要查询不公开的
	Page          int64                  `protobuf:"varint,3,opt,name=page,proto3" json:"page,omitempty"`                         // 页码
	Size          int64                  `protobuf:"varint,4,opt,name=size,proto3" json:"size,omitempty"`                         // 每页条数
	Sort          SortType               `protobuf:"varint,5,opt,name=sort,proto3,enum=pb.SortType" json:"sort,omitempty"`        // 排序
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListTweetsUidReq) Reset() {
	*x = ListTweetsUidReq{}
	mi := &file_pb_contentService_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListTweetsUidReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTweetsUidReq) ProtoMessage() {}

func (x *ListTweetsUidReq) ProtoReflect() protoreflect.Message {
	mi := &file_pb_contentService_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTweetsUidReq.ProtoReflect.Descriptor instead.
func (*ListTweetsUidReq) Descriptor() ([]byte, []int) {
	return file_pb_contentService_proto_rawDescGZIP(), []int{1}
}

func (x *ListTweetsUidReq) GetQueryUid() int64 {
	if x != nil {
		return x.QueryUid
	}
	return 0
}

func (x *ListTweetsUidReq) GetIsPublic() bool {
	if x != nil {
		return x.IsPublic
	}
	return false
}

func (x *ListTweetsUidReq) GetPage() int64 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListTweetsUidReq) GetSize() int64 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *ListTweetsUidReq) GetSort() SortType {
	if x != nil {
		return x.Sort
	}
	return SortType_CREATED_AT_DESC
}

// 响应：和之前一致
type ListTweetsUidResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int64                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Msg           string                 `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	Tweets        []*Tweet               `protobuf:"bytes,3,rep,name=tweets,proto3" json:"tweets,omitempty"`         // 过滤后的推文列表
	Pagination    *Pagination            `protobuf:"bytes,4,opt,name=pagination,proto3" json:"pagination,omitempty"` // 分页信息
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListTweetsUidResp) Reset() {
	*x = ListTweetsUidResp{}
	mi := &file_pb_contentService_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListTweetsUidResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTweetsUidResp) ProtoMessage() {}

func (x *ListTweetsUidResp) ProtoReflect() protoreflect.Message {
	mi := &file_pb_contentService_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTweetsUidResp.ProtoReflect.Descriptor instead.
func (*ListTweetsUidResp) Descriptor() ([]byte, []int) {
	return file_pb_contentService_proto_rawDescGZIP(), []int{2}
}

func (x *ListTweetsUidResp) GetCode() int64 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *ListTweetsUidResp) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

func (x *ListTweetsUidResp) GetTweets() []*Tweet {
	if x != nil {
		return x.Tweets
	}
	return nil
}

func (x *ListTweetsUidResp) GetPagination() *Pagination {
	if x != nil {
		return x.Pagination
	}
	return nil
}

type Pagination struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Page          int64                  `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	Size          int64                  `protobuf:"varint,2,opt,name=size,proto3" json:"size,omitempty"`
	Total         int64                  `protobuf:"varint,3,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Pagination) Reset() {
	*x = Pagination{}
	mi := &file_pb_contentService_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Pagination) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Pagination) ProtoMessage() {}

func (x *Pagination) ProtoReflect() protoreflect.Message {
	mi := &file_pb_contentService_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Pagination.ProtoReflect.Descriptor instead.
func (*Pagination) Descriptor() ([]byte, []int) {
	return file_pb_contentService_proto_rawDescGZIP(), []int{3}
}

func (x *Pagination) GetPage() int64 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *Pagination) GetSize() int64 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *Pagination) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

// ========== 单条推文查询==========
type GetTweetByTidReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tid           int64                  `protobuf:"varint,1,opt,name=tid,proto3" json:"tid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTweetByTidReq) Reset() {
	*x = GetTweetByTidReq{}
	mi := &file_pb_contentService_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTweetByTidReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTweetByTidReq) ProtoMessage() {}

func (x *GetTweetByTidReq) ProtoReflect() protoreflect.Message {
	mi := &file_pb_contentService_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTweetByTidReq.ProtoReflect.Descriptor instead.
func (*GetTweetByTidReq) Descriptor() ([]byte, []int) {
	return file_pb_contentService_proto_rawDescGZIP(), []int{4}
}

func (x *GetTweetByTidReq) GetTid() int64 {
	if x != nil {
		return x.Tid
	}
	return 0
}

type GetTweetByTidResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int64                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Msg           string                 `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	Tweet         *Tweet                 `protobuf:"bytes,3,opt,name=tweet,proto3" json:"tweet,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTweetByTidResp) Reset() {
	*x = GetTweetByTidResp{}
	mi := &file_pb_contentService_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTweetByTidResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTweetByTidResp) ProtoMessage() {}

func (x *GetTweetByTidResp) ProtoReflect() protoreflect.Message {
	mi := &file_pb_contentService_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTweetByTidResp.ProtoReflect.Descriptor instead.
func (*GetTweetByTidResp) Descriptor() ([]byte, []int) {
	return file_pb_contentService_proto_rawDescGZIP(), []int{5}
}

func (x *GetTweetByTidResp) GetCode() int64 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *GetTweetByTidResp) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

func (x *GetTweetByTidResp) GetTweet() *Tweet {
	if x != nil {
		return x.Tweet
	}
	return nil
}

// ========== 批量推文查询（供推荐与搜索微服务调用） ==========
type BatchGetTweetsReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tids          []int64                `protobuf:"varint,1,rep,packed,name=tids,proto3" json:"tids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatchGetTweetsReq) Reset() {
	*x = BatchGetTweetsReq{}
	mi := &file_pb_contentService_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchGetTweetsReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchGetTweetsReq) ProtoMessage() {}

func (x *BatchGetTweetsReq) ProtoReflect() protoreflect.Message {
	mi := &file_pb_contentService_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchGetTweetsReq.ProtoReflect.Descriptor instead.
func (*BatchGetTweetsReq) Descriptor() ([]byte, []int) {
	return file_pb_contentService_proto_rawDescGZIP(), []int{6}
}

func (x *BatchGetTweetsReq) GetTids() []int64 {
	if x != nil {
		return x.Tids
	}
	return nil
}

type BatchGetTweetsResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int64                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Msg           string                 `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	Tweets        []*Tweet               `protobuf:"bytes,3,rep,name=tweets,proto3" json:"tweets,omitempty"` // 仅返回公开推文
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatchGetTweetsResp) Reset() {
	*x = BatchGetTweetsResp{}
	mi := &file_pb_contentService_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchGetTweetsResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchGetTweetsResp) ProtoMessage() {}

func (x *BatchGetTweetsResp) ProtoReflect() protoreflect.Message {
	mi := &file_pb_contentService_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchGetTweetsResp.ProtoReflect.Descriptor instead.
func (*BatchGetTweetsResp) Descriptor() ([]byte, []int) {
	return file_pb_contentService_proto_rawDescGZIP(), []int{7}
}

func (x *BatchGetTweetsResp) GetCode() int64 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *BatchGetTweetsResp) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

func (x *BatchGetTweetsResp) GetTweets() []*Tweet {
	if x != nil {
		return x.Tweets
	}
	return nil
}

// 创建推文
type CreateTweetReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uid           int64                  `protobuf:"varint,1,opt,name=uid,proto3" json:"uid,omitempty"`
	Content       string                 `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	MediaUrls     []string               `protobuf:"bytes,3,rep,name=media_urls,json=mediaUrls,proto3" json:"media_urls,omitempty"`
	Tags          []string               `protobuf:"bytes,4,rep,name=tags,proto3" json:"tags,omitempty"`
	IsPublic      bool                   `protobuf:"varint,5,opt,name=is_public,json=isPublic,proto3" json:"is_public,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateTweetReq) Reset() {
	*x = CreateTweetReq{}
	mi := &file_pb_contentService_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateTweetReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateTweetReq) ProtoMessage() {}

func (x *CreateTweetReq) ProtoReflect() protoreflect.Message {
	mi := &file_pb_contentService_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateTweetReq.ProtoReflect.Descriptor instead.
func (*CreateTweetReq) Descriptor() ([]byte, []int) {
	return file_pb_contentService_proto_rawDescGZIP(), []int{8}
}

func (x *CreateTweetReq) GetUid() int64 {
	if x != nil {
		return x.Uid
	}
	return 0
}

func (x *CreateTweetReq) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *CreateTweetReq) GetMediaUrls() []string {
	if x != nil {
		return x.MediaUrls
	}
	return nil
}

func (x *CreateTweetReq) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *CreateTweetReq) GetIsPublic() bool {
	if x != nil {
		return x.IsPublic
	}
	return false
}

type CreateTweetResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int64                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Msg           string                 `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	Tweet         *Tweet                 `protobuf:"bytes,3,opt,name=tweet,proto3" json:"tweet,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateTweetResp) Reset() {
	*x = CreateTweetResp{}
	mi := &file_pb_contentService_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateTweetResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateTweetResp) ProtoMessage() {}

func (x *CreateTweetResp) ProtoReflect() protoreflect.Message {
	mi := &file_pb_contentService_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateTweetResp.ProtoReflect.Descriptor instead.
func (*CreateTweetResp) Descriptor() ([]byte, []int) {
	return file_pb_contentService_proto_rawDescGZIP(), []int{9}
}

func (x *CreateTweetResp) GetCode() int64 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *CreateTweetResp) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

func (x *CreateTweetResp) GetTweet() *Tweet {
	if x != nil {
		return x.Tweet
	}
	return nil
}

// 删除推文
type DeleteTweetReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tid           int64                  `protobuf:"varint,1,opt,name=tid,proto3" json:"tid,omitempty"`
	Uid           int64                  `protobuf:"varint,2,opt,name=uid,proto3" json:"uid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteTweetReq) Reset() {
	*x = DeleteTweetReq{}
	mi := &file_pb_contentService_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteTweetReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteTweetReq) ProtoMessage() {}

func (x *DeleteTweetReq) ProtoReflect() protoreflect.Message {
	mi := &file_pb_contentService_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteTweetReq.ProtoReflect.Descriptor instead.
func (*DeleteTweetReq) Descriptor() ([]byte, []int) {
	return file_pb_contentService_proto_rawDescGZIP(), []int{10}
}

func (x *DeleteTweetReq) GetTid() int64 {
	if x != nil {
		return x.Tid
	}
	return 0
}

func (x *DeleteTweetReq) GetUid() int64 {
	if x != nil {
		return x.Uid
	}
	return 0
}

type DeleteTweetResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int64                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Msg           string                 `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteTweetResp) Reset() {
	*x = DeleteTweetResp{}
	mi := &file_pb_contentService_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteTweetResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteTweetResp) ProtoMessage() {}

func (x *DeleteTweetResp) ProtoReflect() protoreflect.Message {
	mi := &file_pb_contentService_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteTweetResp.ProtoReflect.Descriptor instead.
func (*DeleteTweetResp) Descriptor() ([]byte, []int) {
	return file_pb_contentService_proto_rawDescGZIP(), []int{11}
}

func (x *DeleteTweetResp) GetCode() int64 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *DeleteTweetResp) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

// ==================== 统计更新 ====================
type UpdateStatsTidReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tid           int64                  `protobuf:"varint,1,opt,name=tid,proto3" json:"tid,omitempty"`
	UpdateTypeTid UpdateTypeTid          `protobuf:"varint,2,opt,name=update_type_tid,json=updateTypeTid,proto3,enum=pb.UpdateTypeTid" json:"update_type_tid,omitempty"`
	Delta         int64                  `protobuf:"varint,3,opt,name=delta,proto3" json:"delta,omitempty"`
	UpdateFrom    UpdateFrom             `protobuf:"varint,4,opt,name=update_from,json=updateFrom,proto3,enum=pb.UpdateFrom" json:"update_from,omitempty"`
	UpdateTime    int64                  `protobuf:"varint,5,opt,name=update_time,json=updateTime,proto3" json:"update_time,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateStatsTidReq) Reset() {
	*x = UpdateStatsTidReq{}
	mi := &file_pb_contentService_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateStatsTidReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateStatsTidReq) ProtoMessage() {}

func (x *UpdateStatsTidReq) ProtoReflect() protoreflect.Message {
	mi := &file_pb_contentService_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateStatsTidReq.ProtoReflect.Descriptor instead.
func (*UpdateStatsTidReq) Descriptor() ([]byte, []int) {
	return file_pb_contentService_proto_rawDescGZIP(), []int{12}
}

func (x *UpdateStatsTidReq) GetTid() int64 {
	if x != nil {
		return x.Tid
	}
	return 0
}

func (x *UpdateStatsTidReq) GetUpdateTypeTid() UpdateTypeTid {
	if x != nil {
		return x.UpdateTypeTid
	}
	return UpdateTypeTid_UNKNOWN
}

func (x *UpdateStatsTidReq) GetDelta() int64 {
	if x != nil {
		return x.Delta
	}
	return 0
}

func (x *UpdateStatsTidReq) GetUpdateFrom() UpdateFrom {
	if x != nil {
		return x.UpdateFrom
	}
	return UpdateFrom_UserService
}

func (x *UpdateStatsTidReq) GetUpdateTime() int64 {
	if x != nil {
		return x.UpdateTime
	}
	return 0
}

type UpdateStatsTidResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateStatsTidResp) Reset() {
	*x = UpdateStatsTidResp{}
	mi := &file_pb_contentService_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateStatsTidResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateStatsTidResp) ProtoMessage() {}

func (x *UpdateStatsTidResp) ProtoReflect() protoreflect.Message {
	mi := &file_pb_contentService_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateStatsTidResp.ProtoReflect.Descriptor instead.
func (*UpdateStatsTidResp) Descriptor() ([]byte, []int) {
	return file_pb_contentService_proto_rawDescGZIP(), []int{13}
}

func (x *UpdateStatsTidResp) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

var File_pb_contentService_proto protoreflect.FileDescriptor

const file_pb_contentService_proto_rawDesc = "" +
	"\n" +
	"\x17pb/contentService.proto\x12\x02pb\"\x97\x02\n" +
	"\x05Tweet\x12\x10\n" +
	"\x03tid\x18\x01 \x01(\x03R\x03tid\x12\x10\n" +
	"\x03uid\x18\x02 \x01(\x03R\x03uid\x12\x18\n" +
	"\acontent\x18\x03 \x01(\tR\acontent\x12\x1d\n" +
	"\n" +
	"media_urls\x18\x04 \x03(\tR\tmediaUrls\x12\x12\n" +
	"\x04tags\x18\x05 \x03(\tR\x04tags\x12\x1b\n" +
	"\tis_public\x18\x06 \x01(\bR\bisPublic\x12\x1d\n" +
	"\n" +
	"created_at\x18\a \x01(\x03R\tcreatedAt\x12\x1d\n" +
	"\n" +
	"is_deleted\x18\b \x01(\bR\tisDeleted\x12\x1d\n" +
	"\n" +
	"like_count\x18\t \x01(\x03R\tlikeCount\x12#\n" +
	"\rcomment_count\x18\n" +
	" \x01(\x03R\fcommentCount\"\x96\x01\n" +
	"\x10ListTweetsUidReq\x12\x1b\n" +
	"\tquery_uid\x18\x01 \x01(\x03R\bqueryUid\x12\x1b\n" +
	"\tis_public\x18\x02 \x01(\bR\bisPublic\x12\x12\n" +
	"\x04page\x18\x03 \x01(\x03R\x04page\x12\x12\n" +
	"\x04size\x18\x04 \x01(\x03R\x04size\x12 \n" +
	"\x04sort\x18\x05 \x01(\x0e2\f.pb.SortTypeR\x04sort\"\x8c\x01\n" +
	"\x11ListTweetsUidResp\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x03R\x04code\x12\x10\n" +
	"\x03msg\x18\x02 \x01(\tR\x03msg\x12!\n" +
	"\x06tweets\x18\x03 \x03(\v2\t.pb.TweetR\x06tweets\x12.\n" +
	"\n" +
	"pagination\x18\x04 \x01(\v2\x0e.pb.PaginationR\n" +
	"pagination\"J\n" +
	"\n" +
	"Pagination\x12\x12\n" +
	"\x04page\x18\x01 \x01(\x03R\x04page\x12\x12\n" +
	"\x04size\x18\x02 \x01(\x03R\x04size\x12\x14\n" +
	"\x05total\x18\x03 \x01(\x03R\x05total\"$\n" +
	"\x10GetTweetByTidReq\x12\x10\n" +
	"\x03tid\x18\x01 \x01(\x03R\x03tid\"Z\n" +
	"\x11GetTweetByTidResp\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x03R\x04code\x12\x10\n" +
	"\x03msg\x18\x02 \x01(\tR\x03msg\x12\x1f\n" +
	"\x05tweet\x18\x03 \x01(\v2\t.pb.TweetR\x05tweet\"'\n" +
	"\x11BatchGetTweetsReq\x12\x12\n" +
	"\x04tids\x18\x01 \x03(\x03R\x04tids\"]\n" +
	"\x12BatchGetTweetsResp\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x03R\x04code\x12\x10\n" +
	"\x03msg\x18\x02 \x01(\tR\x03msg\x12!\n" +
	"\x06tweets\x18\x03 \x03(\v2\t.pb.TweetR\x06tweets\"\x8c\x01\n" +
	"\x0eCreateTweetReq\x12\x10\n" +
	"\x03uid\x18\x01 \x01(\x03R\x03uid\x12\x18\n" +
	"\acontent\x18\x02 \x01(\tR\acontent\x12\x1d\n" +
	"\n" +
	"media_urls\x18\x03 \x03(\tR\tmediaUrls\x12\x12\n" +
	"\x04tags\x18\x04 \x03(\tR\x04tags\x12\x1b\n" +
	"\tis_public\x18\x05 \x01(\bR\bisPublic\"X\n" +
	"\x0fCreateTweetResp\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x03R\x04code\x12\x10\n" +
	"\x03msg\x18\x02 \x01(\tR\x03msg\x12\x1f\n" +
	"\x05tweet\x18\x03 \x01(\v2\t.pb.TweetR\x05tweet\"4\n" +
	"\x0eDeleteTweetReq\x12\x10\n" +
	"\x03tid\x18\x01 \x01(\x03R\x03tid\x12\x10\n" +
	"\x03uid\x18\x02 \x01(\x03R\x03uid\"7\n" +
	"\x0fDeleteTweetResp\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x03R\x04code\x12\x10\n" +
	"\x03msg\x18\x02 \x01(\tR\x03msg\"\xc8\x01\n" +
	"\x11UpdateStatsTidReq\x12\x10\n" +
	"\x03tid\x18\x01 \x01(\x03R\x03tid\x129\n" +
	"\x0fupdate_type_tid\x18\x02 \x01(\x0e2\x11.pb.UpdateTypeTidR\rupdateTypeTid\x12\x14\n" +
	"\x05delta\x18\x03 \x01(\x03R\x05delta\x12/\n" +
	"\vupdate_from\x18\x04 \x01(\x0e2\x0e.pb.UpdateFromR\n" +
	"updateFrom\x12\x1f\n" +
	"\vupdate_time\x18\x05 \x01(\x03R\n" +
	"updateTime\".\n" +
	"\x12UpdateStatsTidResp\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess*3\n" +
	"\bSortType\x12\x13\n" +
	"\x0fCREATED_AT_DESC\x10\x00\x12\x12\n" +
	"\x0eCREATED_AT_ASC\x10\x01*?\n" +
	"\rUpdateTypeTid\x12\v\n" +
	"\aUNKNOWN\x10\x00\x12\x0e\n" +
	"\n" +
	"Like_COUNT\x10\x01\x12\x11\n" +
	"\rComment_COUNT\x10\x02*w\n" +
	"\n" +
	"UpdateFrom\x12\x0f\n" +
	"\vUserService\x10\x00\x12\x12\n" +
	"\x0eContentService\x10\x01\x12\x16\n" +
	"\x12InteractiveService\x10\x02\x12\x11\n" +
	"\rNotifyService\x10\x03\x12\x19\n" +
	"\x15ReCmdAndSearchService\x10\x042\xf7\x02\n" +
	"\aContent\x12<\n" +
	"\rListTweetsUid\x12\x14.pb.ListTweetsUidReq\x1a\x15.pb.ListTweetsUidResp\x12<\n" +
	"\rGetTweetByTid\x12\x14.pb.GetTweetByTidReq\x1a\x15.pb.GetTweetByTidResp\x12?\n" +
	"\x0eBatchGetTweets\x12\x15.pb.BatchGetTweetsReq\x1a\x16.pb.BatchGetTweetsResp\x126\n" +
	"\vCreateTweet\x12\x12.pb.CreateTweetReq\x1a\x13.pb.CreateTweetResp\x126\n" +
	"\vDeleteTweet\x12\x12.pb.DeleteTweetReq\x1a\x13.pb.DeleteTweetResp\x12?\n" +
	"\x0eUpdateStatsTid\x12\x15.pb.UpdateStatsTidReq\x1a\x16.pb.UpdateStatsTidRespB\x06Z\x04./pbb\x06proto3"

var (
	file_pb_contentService_proto_rawDescOnce sync.Once
	file_pb_contentService_proto_rawDescData []byte
)

func file_pb_contentService_proto_rawDescGZIP() []byte {
	file_pb_contentService_proto_rawDescOnce.Do(func() {
		file_pb_contentService_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pb_contentService_proto_rawDesc), len(file_pb_contentService_proto_rawDesc)))
	})
	return file_pb_contentService_proto_rawDescData
}

var file_pb_contentService_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_pb_contentService_proto_msgTypes = make([]protoimpl.MessageInfo, 14)
var file_pb_contentService_proto_goTypes = []any{
	(SortType)(0),              // 0: pb.SortType
	(UpdateTypeTid)(0),         // 1: pb.UpdateTypeTid
	(UpdateFrom)(0),            // 2: pb.UpdateFrom
	(*Tweet)(nil),              // 3: pb.Tweet
	(*ListTweetsUidReq)(nil),   // 4: pb.ListTweetsUidReq
	(*ListTweetsUidResp)(nil),  // 5: pb.ListTweetsUidResp
	(*Pagination)(nil),         // 6: pb.Pagination
	(*GetTweetByTidReq)(nil),   // 7: pb.GetTweetByTidReq
	(*GetTweetByTidResp)(nil),  // 8: pb.GetTweetByTidResp
	(*BatchGetTweetsReq)(nil),  // 9: pb.BatchGetTweetsReq
	(*BatchGetTweetsResp)(nil), // 10: pb.BatchGetTweetsResp
	(*CreateTweetReq)(nil),     // 11: pb.CreateTweetReq
	(*CreateTweetResp)(nil),    // 12: pb.CreateTweetResp
	(*DeleteTweetReq)(nil),     // 13: pb.DeleteTweetReq
	(*DeleteTweetResp)(nil),    // 14: pb.DeleteTweetResp
	(*UpdateStatsTidReq)(nil),  // 15: pb.UpdateStatsTidReq
	(*UpdateStatsTidResp)(nil), // 16: pb.UpdateStatsTidResp
}
var file_pb_contentService_proto_depIdxs = []int32{
	0,  // 0: pb.ListTweetsUidReq.sort:type_name -> pb.SortType
	3,  // 1: pb.ListTweetsUidResp.tweets:type_name -> pb.Tweet
	6,  // 2: pb.ListTweetsUidResp.pagination:type_name -> pb.Pagination
	3,  // 3: pb.GetTweetByTidResp.tweet:type_name -> pb.Tweet
	3,  // 4: pb.BatchGetTweetsResp.tweets:type_name -> pb.Tweet
	3,  // 5: pb.CreateTweetResp.tweet:type_name -> pb.Tweet
	1,  // 6: pb.UpdateStatsTidReq.update_type_tid:type_name -> pb.UpdateTypeTid
	2,  // 7: pb.UpdateStatsTidReq.update_from:type_name -> pb.UpdateFrom
	4,  // 8: pb.Content.ListTweetsUid:input_type -> pb.ListTweetsUidReq
	7,  // 9: pb.Content.GetTweetByTid:input_type -> pb.GetTweetByTidReq
	9,  // 10: pb.Content.BatchGetTweets:input_type -> pb.BatchGetTweetsReq
	11, // 11: pb.Content.CreateTweet:input_type -> pb.CreateTweetReq
	13, // 12: pb.Content.DeleteTweet:input_type -> pb.DeleteTweetReq
	15, // 13: pb.Content.UpdateStatsTid:input_type -> pb.UpdateStatsTidReq
	5,  // 14: pb.Content.ListTweetsUid:output_type -> pb.ListTweetsUidResp
	8,  // 15: pb.Content.GetTweetByTid:output_type -> pb.GetTweetByTidResp
	10, // 16: pb.Content.BatchGetTweets:output_type -> pb.BatchGetTweetsResp
	12, // 17: pb.Content.CreateTweet:output_type -> pb.CreateTweetResp
	14, // 18: pb.Content.DeleteTweet:output_type -> pb.DeleteTweetResp
	16, // 19: pb.Content.UpdateStatsTid:output_type -> pb.UpdateStatsTidResp
	14, // [14:20] is the sub-list for method output_type
	8,  // [8:14] is the sub-list for method input_type
	8,  // [8:8] is the sub-list for extension type_name
	8,  // [8:8] is the sub-list for extension extendee
	0,  // [0:8] is the sub-list for field type_name
}

func init() { file_pb_contentService_proto_init() }
func file_pb_contentService_proto_init() {
	if File_pb_contentService_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pb_contentService_proto_rawDesc), len(file_pb_contentService_proto_rawDesc)),
			NumEnums:      3,
			NumMessages:   14,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pb_contentService_proto_goTypes,
		DependencyIndexes: file_pb_contentService_proto_depIdxs,
		EnumInfos:         file_pb_contentService_proto_enumTypes,
		MessageInfos:      file_pb_contentService_proto_msgTypes,
	}.Build()
	File_pb_contentService_proto = out.File
	file_pb_contentService_proto_goTypes = nil
	file_pb_contentService_proto_depIdxs = nil
}
