// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.9.2

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/cache"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	userStatsLogFieldNames          = builder.RawFieldNames(&UserStatsLog{}, true)
	userStatsLogRows                = strings.Join(userStatsLogFieldNames, ",")
	userStatsLogRowsExpectAutoSet   = strings.Join(stringx.Remove(userStatsLogFieldNames, "log_id", "create_at", "create_time", "created_at", "update_at", "update_time", "updated_at"), ",")
	userStatsLogRowsWithPlaceHolder = builder.PostgreSqlJoin(stringx.Remove(userStatsLogFieldNames, "log_id", "create_at", "create_time", "created_at", "update_at", "update_time", "updated_at"))
	cachePublicUserStatsLogLogIdPrefix = "cache:public:userStatsLog:logId:"
)

type (
	userStatsLogModel interface {
		Insert(ctx context.Context, data *UserStatsLog) (sql.Result, error)
		FindOne(ctx context.Context, logId int64) (*UserStatsLog, error)
		Update(ctx context.Context, data *UserStatsLog) error
		Delete(ctx context.Context, logId int64) error
	}

	defaultUserStatsLogModel struct {
		sqlc.CachedConn
		table string
	}

	UserStatsLog struct {
		LogId       int64     `db:"log_id"`       // 日志ID，自增主键
		Uid         int64     `db:"uid"`          // 用户ID，关联user表
		UpdateType  int64     `db:"update_type"`  // 变更类型：1关注数 2粉丝数 3发帖数
		Delta       int64     `db:"delta"`        // 变化量（正负）
		UpdateFrom  int64     `db:"update_from"`  // 来源服务：0用户,1内容,2互动,3通知,4推荐搜索
		BeforeValue int64     `db:"before_value"` // 变更前值
		AfterValue  int64     `db:"after_value"`  // 变更后值
		CreatedAt   time.Time `db:"created_at"`   // 日志创建时间
	}
)

func newUserStatsLogModel(conn sqlx.SqlConn, c cache.CacheConf, opts ...cache.Option) *defaultUserStatsLogModel {
	return &defaultUserStatsLogModel{
		CachedConn: sqlc.NewConn(conn, c, opts...),
		table:      `"public"."user_stats_log"`,
	}
}

func (m *defaultUserStatsLogModel) Delete(ctx context.Context, logId int64) error {
	publicUserStatsLogLogIdKey := fmt.Sprintf("%s%v", cachePublicUserStatsLogLogIdPrefix, logId)
	_, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("delete from %s where log_id = $1", m.table)
		return conn.ExecCtx(ctx, query, logId)
	}, publicUserStatsLogLogIdKey)
	return err
}

func (m *defaultUserStatsLogModel) FindOne(ctx context.Context, logId int64) (*UserStatsLog, error) {
	publicUserStatsLogLogIdKey := fmt.Sprintf("%s%v", cachePublicUserStatsLogLogIdPrefix, logId)
	var resp UserStatsLog
	err := m.QueryRowCtx(ctx, &resp, publicUserStatsLogLogIdKey, func(ctx context.Context, conn sqlx.SqlConn, v any) error {
		query := fmt.Sprintf("select %s from %s where log_id = $1 limit 1", userStatsLogRows, m.table)
		return conn.QueryRowCtx(ctx, v, query, logId)
	})
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultUserStatsLogModel) Insert(ctx context.Context, data *UserStatsLog) (sql.Result, error) {
	publicUserStatsLogLogIdKey := fmt.Sprintf("%s%v", cachePublicUserStatsLogLogIdPrefix, data.LogId)
	ret, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("insert into %s (%s) values ($1, $2, $3, $4, $5, $6)", m.table, userStatsLogRowsExpectAutoSet)
		return conn.ExecCtx(ctx, query, data.Uid, data.UpdateType, data.Delta, data.UpdateFrom, data.BeforeValue, data.AfterValue)
	}, publicUserStatsLogLogIdKey)
	return ret, err
}

func (m *defaultUserStatsLogModel) Update(ctx context.Context, data *UserStatsLog) error {
	publicUserStatsLogLogIdKey := fmt.Sprintf("%s%v", cachePublicUserStatsLogLogIdPrefix, data.LogId)
	_, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("update %s set %s where log_id = $1", m.table, userStatsLogRowsWithPlaceHolder)
		return conn.ExecCtx(ctx, query, data.LogId, data.Uid, data.UpdateType, data.Delta, data.UpdateFrom, data.BeforeValue, data.AfterValue)
	}, publicUserStatsLogLogIdKey)
	return err
}

func (m *defaultUserStatsLogModel) formatPrimary(primary any) string {
	return fmt.Sprintf("%s%v", cachePublicUserStatsLogLogIdPrefix, primary)
}

func (m *defaultUserStatsLogModel) queryPrimary(ctx context.Context, conn sqlx.SqlConn, v, primary any) error {
	query := fmt.Sprintf("select %s from %s where log_id = $1 limit 1", userStatsLogRows, m.table)
	return conn.QueryRowCtx(ctx, v, query, primary)
}

func (m *defaultUserStatsLogModel) tableName() string {
	return m.table
}
