// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.9.2

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/cache"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	userFieldNames          = builder.RawFieldNames(&User{}, true)
	userRows                = strings.Join(userFieldNames, ",")
	userRowsExpectAutoSet   = strings.Join(stringx.Remove(userFieldNames, "uid", "create_at", "create_time", "created_at", "update_at", "update_time", "updated_at"), ",")
	userRowsWithPlaceHolder = builder.PostgreSqlJoin(stringx.Remove(userFieldNames, "uid", "create_at", "create_time", "created_at", "update_at", "update_time", "updated_at"))

	cachePublicUserUidPrefix      = "cache:public:user:uid:"
	cachePublicUserMobilePrefix   = "cache:public:user:mobile:"
	cachePublicUserNicknamePrefix = "cache:public:user:nickname:"
)

type (
	userModel interface {
		Insert(ctx context.Context, data *User) (sql.Result, error)
		FindOne(ctx context.Context, uid int64) (*User, error)
		FindOneByMobile(ctx context.Context, mobile string) (*User, error)
		FindOneByNickname(ctx context.Context, nickname string) (*User, error)
		Update(ctx context.Context, data *User) error
		Delete(ctx context.Context, uid int64) error
	}

	defaultUserModel struct {
		sqlc.CachedConn
		table string
	}

	User struct {
		Uid         int64  `db:"uid"`           // 用户ID，自增主键
		Mobile      string `db:"mobile"`        // 手机号（登录账号）
		Password    string `db:"password"`      // 加密后的密码
		Nickname    string `db:"nickname"`      // 用户昵称（初始值为uid，唯一）
		Avatar      string `db:"avatar"`        // 头像URL
		Bio         string `db:"bio"`           // 个人简介
		FollowCount int64  `db:"follow_count"`  // 关注数
		FansCount   int64  `db:"fans_count"`    // 粉丝数
		PostCount   int64  `db:"post_count"`    // 发帖/动态数
		Status      int64  `db:"status"`        // 账号状态：1正常，0禁用
		LastLoginAt int64  `db:"last_login_at"` // 最后登录时间（毫秒级时间戳）
		CreatedAt   int64  `db:"created_at"`    // 创建时间（毫秒级时间戳）
		UpdatedAt   int64  `db:"updated_at"`    // 更新时间（毫秒级时间戳）
	}
)

func newUserModel(conn sqlx.SqlConn, c cache.CacheConf, opts ...cache.Option) *defaultUserModel {
	return &defaultUserModel{
		CachedConn: sqlc.NewConn(conn, c, opts...),
		table:      `"public"."user"`,
	}
}

func (m *defaultUserModel) Delete(ctx context.Context, uid int64) error {
	data, err := m.FindOne(ctx, uid)
	if err != nil {
		return err
	}

	publicUserMobileKey := fmt.Sprintf("%s%v", cachePublicUserMobilePrefix, data.Mobile)
	publicUserNicknameKey := fmt.Sprintf("%s%v", cachePublicUserNicknamePrefix, data.Nickname)
	publicUserUidKey := fmt.Sprintf("%s%v", cachePublicUserUidPrefix, uid)
	_, err = m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("delete from %s where uid = $1", m.table)
		return conn.ExecCtx(ctx, query, uid)
	}, publicUserMobileKey, publicUserNicknameKey, publicUserUidKey)
	return err
}

func (m *defaultUserModel) FindOne(ctx context.Context, uid int64) (*User, error) {
	publicUserUidKey := fmt.Sprintf("%s%v", cachePublicUserUidPrefix, uid)
	var resp User
	err := m.QueryRowCtx(ctx, &resp, publicUserUidKey, func(ctx context.Context, conn sqlx.SqlConn, v any) error {
		query := fmt.Sprintf("select %s from %s where uid = $1 limit 1", userRows, m.table)
		return conn.QueryRowCtx(ctx, v, query, uid)
	})
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultUserModel) FindOneByMobile(ctx context.Context, mobile string) (*User, error) {
	publicUserMobileKey := fmt.Sprintf("%s%v", cachePublicUserMobilePrefix, mobile)
	var resp User
	err := m.QueryRowIndexCtx(ctx, &resp, publicUserMobileKey, m.formatPrimary, func(ctx context.Context, conn sqlx.SqlConn, v any) (i any, e error) {
		query := fmt.Sprintf("select %s from %s where mobile = $1 limit 1", userRows, m.table)
		if err := conn.QueryRowCtx(ctx, &resp, query, mobile); err != nil {
			return nil, err
		}
		return resp.Uid, nil
	}, m.queryPrimary)
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultUserModel) FindOneByNickname(ctx context.Context, nickname string) (*User, error) {
	publicUserNicknameKey := fmt.Sprintf("%s%v", cachePublicUserNicknamePrefix, nickname)
	var resp User
	err := m.QueryRowIndexCtx(ctx, &resp, publicUserNicknameKey, m.formatPrimary, func(ctx context.Context, conn sqlx.SqlConn, v any) (i any, e error) {
		query := fmt.Sprintf("select %s from %s where nickname = $1 limit 1", userRows, m.table)
		if err := conn.QueryRowCtx(ctx, &resp, query, nickname); err != nil {
			return nil, err
		}
		return resp.Uid, nil
	}, m.queryPrimary)
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultUserModel) Insert(ctx context.Context, data *User) (sql.Result, error) {
	publicUserMobileKey := fmt.Sprintf("%s%v", cachePublicUserMobilePrefix, data.Mobile)
	publicUserNicknameKey := fmt.Sprintf("%s%v", cachePublicUserNicknamePrefix, data.Nickname)
	publicUserUidKey := fmt.Sprintf("%s%v", cachePublicUserUidPrefix, 0)
	ret, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("insert into %s (%s) values ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10)", m.table, userRowsExpectAutoSet)
		return conn.ExecCtx(ctx, query, data.Mobile, data.Password, data.Nickname, data.Avatar, data.Bio, data.FollowCount, data.FansCount, data.PostCount, data.Status, data.LastLoginAt)
	}, publicUserMobileKey, publicUserNicknameKey, publicUserUidKey)

	// PostgreSQL lib/pq 不支持 LastInsertId，单独查询获取 uid
	if err == nil {
		var uid int64
		query := fmt.Sprintf("select uid from %s where mobile = $1 order by uid desc limit 1", m.table)
		err = m.QueryRowNoCacheCtx(ctx, &uid, query, data.Mobile)
		if err == nil {
			data.Uid = uid
		}
	}

	return ret, err
}

func (m *defaultUserModel) Update(ctx context.Context, newData *User) error {
	data, err := m.FindOne(ctx, newData.Uid)
	if err != nil {
		return err
	}

	publicUserMobileKey := fmt.Sprintf("%s%v", cachePublicUserMobilePrefix, data.Mobile)
	publicUserNicknameKey := fmt.Sprintf("%s%v", cachePublicUserNicknamePrefix, data.Nickname)
	publicUserUidKey := fmt.Sprintf("%s%v", cachePublicUserUidPrefix, data.Uid)
	_, err = m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("update %s set %s where uid = $1", m.table, userRowsWithPlaceHolder)
		return conn.ExecCtx(ctx, query, newData.Uid, newData.Mobile, newData.Password, newData.Nickname, newData.Avatar, newData.Bio, newData.FollowCount, newData.FansCount, newData.PostCount, newData.Status, newData.LastLoginAt)
	}, publicUserMobileKey, publicUserNicknameKey, publicUserUidKey)
	return err
}

func (m *defaultUserModel) formatPrimary(primary any) string {
	return fmt.Sprintf("%s%v", cachePublicUserUidPrefix, primary)
}

func (m *defaultUserModel) queryPrimary(ctx context.Context, conn sqlx.SqlConn, v, primary any) error {
	query := fmt.Sprintf("select %s from %s where uid = $1 limit 1", userRows, m.table)
	return conn.QueryRowCtx(ctx, v, query, primary)
}

func (m *defaultUserModel) tableName() string {
	return m.table
}
