// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2

package types

type LoginReq struct {
	Mobile   string `json:"mobile"`
	Password string `json:"password"`
}

type LoginResp struct {
	Code         int64    `json:"code"`
	Msg          string   `json:"msg"`
	AccessToken  string   `json:"accessToken"`
	AccessExpire int64    `json:"accessExpire"`
	UserInfo     UserInfo `json:"userInfo"`
}

type RegisterReq struct {
	Mobile   string `json:"mobile"`
	Password string `json:"password"`
}

type RegisterResp struct {
	Code         int      `json:"code"`
	Message      string   `json:"message"`
	AccessToken  string   `json:"accessToken"`
	AccessExpire int64    `json:"accessExpire"`
	UserInfo     UserInfo `json:"userInfo"`
}

type UserInfo struct {
	Uid         int64  `json:"uid"`
	Nickname    string `json:"nickname"`
	Avatar      string `json:"avatar"`
	Bio         string `json:"bio,optional"`
	FollowCount int64  `json:"followCount"`
	FansCount   int64  `json:"fansCount"`
	PostCount   int64  `json:"postCount"`
}

type UserInfoReq struct {
	Uid int64 `json:"uid"`
}

type UserInfoResp struct {
	UserInfo UserInfo `json:"userInfo"`
}
