// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v7.34.1
// source: pb/recommendService.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Recommend_RecommendFeed_FullMethodName   = "/pb.Recommend/RecommendFeed"
	Recommend_SearchRecommend_FullMethodName = "/pb.Recommend/SearchRecommend"
)

// RecommendClient is the client API for Recommend service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// ========== RPC 服务定义 ==========
type RecommendClient interface {
	// 推荐首页 Feed
	RecommendFeed(ctx context.Context, in *RecommendFeedReq, opts ...grpc.CallOption) (*RecommendFeedResp, error)
	// 搜索推荐（预留）
	SearchRecommend(ctx context.Context, in *SearchRecommendReq, opts ...grpc.CallOption) (*SearchRecommendResp, error)
}

type recommendClient struct {
	cc grpc.ClientConnInterface
}

func NewRecommendClient(cc grpc.ClientConnInterface) RecommendClient {
	return &recommendClient{cc}
}

func (c *recommendClient) RecommendFeed(ctx context.Context, in *RecommendFeedReq, opts ...grpc.CallOption) (*RecommendFeedResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RecommendFeedResp)
	err := c.cc.Invoke(ctx, Recommend_RecommendFeed_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *recommendClient) SearchRecommend(ctx context.Context, in *SearchRecommendReq, opts ...grpc.CallOption) (*SearchRecommendResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SearchRecommendResp)
	err := c.cc.Invoke(ctx, Recommend_SearchRecommend_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RecommendServer is the server API for Recommend service.
// All implementations must embed UnimplementedRecommendServer
// for forward compatibility.
//
// ========== RPC 服务定义 ==========
type RecommendServer interface {
	// 推荐首页 Feed
	RecommendFeed(context.Context, *RecommendFeedReq) (*RecommendFeedResp, error)
	// 搜索推荐（预留）
	SearchRecommend(context.Context, *SearchRecommendReq) (*SearchRecommendResp, error)
	mustEmbedUnimplementedRecommendServer()
}

// UnimplementedRecommendServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedRecommendServer struct{}

func (UnimplementedRecommendServer) RecommendFeed(context.Context, *RecommendFeedReq) (*RecommendFeedResp, error) {
	return nil, status.Error(codes.Unimplemented, "method RecommendFeed not implemented")
}
func (UnimplementedRecommendServer) SearchRecommend(context.Context, *SearchRecommendReq) (*SearchRecommendResp, error) {
	return nil, status.Error(codes.Unimplemented, "method SearchRecommend not implemented")
}
func (UnimplementedRecommendServer) mustEmbedUnimplementedRecommendServer() {}
func (UnimplementedRecommendServer) testEmbeddedByValue()                   {}

// UnsafeRecommendServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to RecommendServer will
// result in compilation errors.
type UnsafeRecommendServer interface {
	mustEmbedUnimplementedRecommendServer()
}

func RegisterRecommendServer(s grpc.ServiceRegistrar, srv RecommendServer) {
	// If the following call panics, it indicates UnimplementedRecommendServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Recommend_ServiceDesc, srv)
}

func _Recommend_RecommendFeed_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RecommendFeedReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RecommendServer).RecommendFeed(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Recommend_RecommendFeed_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RecommendServer).RecommendFeed(ctx, req.(*RecommendFeedReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Recommend_SearchRecommend_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SearchRecommendReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RecommendServer).SearchRecommend(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Recommend_SearchRecommend_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RecommendServer).SearchRecommend(ctx, req.(*SearchRecommendReq))
	}
	return interceptor(ctx, in, info, handler)
}

// Recommend_ServiceDesc is the grpc.ServiceDesc for Recommend service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Recommend_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "pb.Recommend",
	HandlerType: (*RecommendServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "RecommendFeed",
			Handler:    _Recommend_RecommendFeed_Handler,
		},
		{
			MethodName: "SearchRecommend",
			Handler:    _Recommend_SearchRecommend_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "pb/recommendService.proto",
}
