// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2
// Source: contentService.proto

package content

import (
	"context"

	"gozeroX/app/contentService/cmd/rpc/pb"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	BatchGetTweetsReq  = pb.BatchGetTweetsReq
	BatchGetTweetsResp = pb.BatchGetTweetsResp
	CreateTweetReq     = pb.CreateTweetReq
	CreateTweetResp    = pb.CreateTweetResp
	DeleteTweetReq     = pb.DeleteTweetReq
	DeleteTweetResp    = pb.DeleteTweetResp
	GetTweetByTidReq   = pb.GetTweetByTidReq
	GetTweetByTidResp  = pb.GetTweetByTidResp
	ListTweetsUidReq   = pb.ListTweetsUidReq
	ListTweetsUidResp  = pb.ListTweetsUidResp
	Pagination         = pb.Pagination
	Tweet              = pb.Tweet
	UpdateStatsTidReq  = pb.UpdateStatsTidReq
	UpdateStatsTidResp = pb.UpdateStatsTidResp

	Content interface {
		// 1. 用户主页推文列表（带权限过滤）
		ListTweetsUid(ctx context.Context, in *ListTweetsUidReq, opts ...grpc.CallOption) (*ListTweetsUidResp, error)
		// 2. 单条推文查询
		GetTweetByTid(ctx context.Context, in *GetTweetByTidReq, opts ...grpc.CallOption) (*GetTweetByTidResp, error)
		// 3. 批量推文查询（仅返回公开的）
		BatchGetTweets(ctx context.Context, in *BatchGetTweetsReq, opts ...grpc.CallOption) (*BatchGetTweetsResp, error)
		// 4. 创建推文（供API调用）
		CreateTweet(ctx context.Context, in *CreateTweetReq, opts ...grpc.CallOption) (*CreateTweetResp, error)
		// 5. 删除推文（供API调用）
		DeleteTweet(ctx context.Context, in *DeleteTweetReq, opts ...grpc.CallOption) (*DeleteTweetResp, error)
		// 6. 更新统计数（供互动微服务调用）
		UpdateStatsTid(ctx context.Context, in *UpdateStatsTidReq, opts ...grpc.CallOption) (*UpdateStatsTidResp, error)
	}

	defaultContent struct {
		cli zrpc.Client
	}
)

func NewContent(cli zrpc.Client) Content {
	return &defaultContent{
		cli: cli,
	}
}

// 1. 用户主页推文列表（带权限过滤）
func (m *defaultContent) ListTweetsUid(ctx context.Context, in *ListTweetsUidReq, opts ...grpc.CallOption) (*ListTweetsUidResp, error) {
	client := pb.NewContentClient(m.cli.Conn())
	return client.ListTweetsUid(ctx, in, opts...)
}

// 2. 单条推文查询
func (m *defaultContent) GetTweetByTid(ctx context.Context, in *GetTweetByTidReq, opts ...grpc.CallOption) (*GetTweetByTidResp, error) {
	client := pb.NewContentClient(m.cli.Conn())
	return client.GetTweetByTid(ctx, in, opts...)
}

// 3. 批量推文查询（仅返回公开的）
func (m *defaultContent) BatchGetTweets(ctx context.Context, in *BatchGetTweetsReq, opts ...grpc.CallOption) (*BatchGetTweetsResp, error) {
	client := pb.NewContentClient(m.cli.Conn())
	return client.BatchGetTweets(ctx, in, opts...)
}

// 4. 创建推文（供API调用）
func (m *defaultContent) CreateTweet(ctx context.Context, in *CreateTweetReq, opts ...grpc.CallOption) (*CreateTweetResp, error) {
	client := pb.NewContentClient(m.cli.Conn())
	return client.CreateTweet(ctx, in, opts...)
}

// 5. 删除推文（供API调用）
func (m *defaultContent) DeleteTweet(ctx context.Context, in *DeleteTweetReq, opts ...grpc.CallOption) (*DeleteTweetResp, error) {
	client := pb.NewContentClient(m.cli.Conn())
	return client.DeleteTweet(ctx, in, opts...)
}

// 6. 更新统计数（供互动微服务调用）
func (m *defaultContent) UpdateStatsTid(ctx context.Context, in *UpdateStatsTidReq, opts ...grpc.CallOption) (*UpdateStatsTidResp, error) {
	client := pb.NewContentClient(m.cli.Conn())
	return client.UpdateStatsTid(ctx, in, opts...)
}
