// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1
// Source: contentService.proto

package content

import (
	"context"

	"gozeroX/app/contentService/cmd/rpc/pb"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	BatchGetTweetsReq     = pb.BatchGetTweetsReq
	BatchGetTweetsResp    = pb.BatchGetTweetsResp
	CreateTweetReq        = pb.CreateTweetReq
	CreateTweetResp       = pb.CreateTweetResp
	DeleteTweetReq        = pb.DeleteTweetReq
	DeleteTweetResp       = pb.DeleteTweetResp
	GetTweetBySnowTidReq  = pb.GetTweetBySnowTidReq
	GetTweetBySnowTidResp = pb.GetTweetBySnowTidResp
	ListTweetsUidReq      = pb.ListTweetsUidReq
	ListTweetsUidResp     = pb.ListTweetsUidResp
	Tweet                 = pb.Tweet
	UpdateTweetStatsReq   = pb.UpdateTweetStatsReq
	UpdateTweetStatsResp  = pb.UpdateTweetStatsResp

	Content interface {
		// 用户主页推文列表（游标分页）
		ListTweetsUid(ctx context.Context, in *ListTweetsUidReq, opts ...grpc.CallOption) (*ListTweetsUidResp, error)
		// 单条推文查询
		GetTweetBySnowTid(ctx context.Context, in *GetTweetBySnowTidReq, opts ...grpc.CallOption) (*GetTweetBySnowTidResp, error)
		// 批量推文查询
		BatchGetTweets(ctx context.Context, in *BatchGetTweetsReq, opts ...grpc.CallOption) (*BatchGetTweetsResp, error)
		// 创建推文
		CreateTweet(ctx context.Context, in *CreateTweetReq, opts ...grpc.CallOption) (*CreateTweetResp, error)
		// 删除推文
		DeleteTweet(ctx context.Context, in *DeleteTweetReq, opts ...grpc.CallOption) (*DeleteTweetResp, error)
		// 更新推文统计字段（like_count / comment_count）
		UpdateTweetStats(ctx context.Context, in *UpdateTweetStatsReq, opts ...grpc.CallOption) (*UpdateTweetStatsResp, error)
	}

	defaultContent struct {
		cli zrpc.Client
	}
)

func NewContent(cli zrpc.Client) Content {
	return &defaultContent{
		cli: cli,
	}
}

// 用户主页推文列表（游标分页）
func (m *defaultContent) ListTweetsUid(ctx context.Context, in *ListTweetsUidReq, opts ...grpc.CallOption) (*ListTweetsUidResp, error) {
	client := pb.NewContentClient(m.cli.Conn())
	return client.ListTweetsUid(ctx, in, opts...)
}

// 单条推文查询
func (m *defaultContent) GetTweetBySnowTid(ctx context.Context, in *GetTweetBySnowTidReq, opts ...grpc.CallOption) (*GetTweetBySnowTidResp, error) {
	client := pb.NewContentClient(m.cli.Conn())
	return client.GetTweetBySnowTid(ctx, in, opts...)
}

// 批量推文查询
func (m *defaultContent) BatchGetTweets(ctx context.Context, in *BatchGetTweetsReq, opts ...grpc.CallOption) (*BatchGetTweetsResp, error) {
	client := pb.NewContentClient(m.cli.Conn())
	return client.BatchGetTweets(ctx, in, opts...)
}

// 创建推文
func (m *defaultContent) CreateTweet(ctx context.Context, in *CreateTweetReq, opts ...grpc.CallOption) (*CreateTweetResp, error) {
	client := pb.NewContentClient(m.cli.Conn())
	return client.CreateTweet(ctx, in, opts...)
}

// 删除推文
func (m *defaultContent) DeleteTweet(ctx context.Context, in *DeleteTweetReq, opts ...grpc.CallOption) (*DeleteTweetResp, error) {
	client := pb.NewContentClient(m.cli.Conn())
	return client.DeleteTweet(ctx, in, opts...)
}

// 更新推文统计字段（like_count / comment_count）
func (m *defaultContent) UpdateTweetStats(ctx context.Context, in *UpdateTweetStatsReq, opts ...grpc.CallOption) (*UpdateTweetStatsResp, error) {
	client := pb.NewContentClient(m.cli.Conn())
	return client.UpdateTweetStats(ctx, in, opts...)
}
