// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.9.2

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/lib/pq"
	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/cache"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	tweetFieldNames          = builder.RawFieldNames(&Tweet{}, true)
	tweetRows                = strings.Join(tweetFieldNames, ",")
	tweetRowsExpectAutoSet   = strings.Join(stringx.Remove(tweetFieldNames, "tid", "create_at", "create_time", "created_at", "update_at", "update_time", "updated_at"), ",")
	tweetRowsWithPlaceHolder = builder.PostgreSqlJoin(stringx.Remove(tweetFieldNames, "tid", "create_at", "create_time", "created_at", "update_at", "update_time", "updated_at"))

	cachePublicTweetTidPrefix = "cache:public:tweet:tid:"
)

type (
	tweetModel interface {
		Insert(ctx context.Context, data *Tweet) (sql.Result, error)
		FindOne(ctx context.Context, tid int64) (*Tweet, error)
		Update(ctx context.Context, data *Tweet) error
		Delete(ctx context.Context, tid int64) error
	}

	defaultTweetModel struct {
		sqlc.CachedConn
		table string
	}

	Tweet struct {
		Tid          int64          `db:"tid"`           // 推文ID，自增主键
		Uid          int64          `db:"uid"`           // 发布用户ID，关联user表
		Content      string         `db:"content"`       // 推文内容
		MediaUrls    pq.StringArray `db:"media_urls"`    // 图片链接列表（数组）
		Tags         pq.StringArray `db:"tags"`          // 标签列表（数组）
		IsPublic     bool           `db:"is_public"`     // 是否公开：true公开，false私密
		LikeCount    int64          `db:"like_count"`    // 点赞数
		CommentCount int64          `db:"comment_count"` // 评论数
		CreatedAt    time.Time      `db:"created_at"`    // 创建时间（带时区）
		IsDeleted    bool           `db:"is_deleted"`    // 是否已删除：true已删除，false未删除
	}
)

func newTweetModel(conn sqlx.SqlConn, c cache.CacheConf, opts ...cache.Option) *defaultTweetModel {
	return &defaultTweetModel{
		CachedConn: sqlc.NewConn(conn, c, opts...),
		table:      `"public"."tweet"`,
	}
}

func (m *defaultTweetModel) Delete(ctx context.Context, tid int64) error {
	publicTweetTidKey := fmt.Sprintf("%s%v", cachePublicTweetTidPrefix, tid)
	_, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("delete from %s where tid = $1", m.table)
		return conn.ExecCtx(ctx, query, tid)
	}, publicTweetTidKey)
	return err
}

func (m *defaultTweetModel) FindOne(ctx context.Context, tid int64) (*Tweet, error) {
	publicTweetTidKey := fmt.Sprintf("%s%v", cachePublicTweetTidPrefix, tid)
	var resp Tweet
	err := m.QueryRowCtx(ctx, &resp, publicTweetTidKey, func(ctx context.Context, conn sqlx.SqlConn, v any) error {
		query := fmt.Sprintf("select %s from %s where tid = $1 limit 1", tweetRows, m.table)
		return conn.QueryRowCtx(ctx, v, query, tid)
	})
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultTweetModel) Insert(ctx context.Context, data *Tweet) (sql.Result, error) {
	publicTweetTidKey := fmt.Sprintf("%s%v", cachePublicTweetTidPrefix, data.Tid)
	ret, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("insert into %s (%s) values ($1, $2, $3, $4, $5, $6, $7, $8)", m.table, tweetRowsExpectAutoSet)
		return conn.ExecCtx(ctx, query, data.Uid, data.Content, data.MediaUrls, data.Tags, data.IsPublic, data.LikeCount, data.CommentCount, data.IsDeleted)
	}, publicTweetTidKey)
	return ret, err
}

func (m *defaultTweetModel) Update(ctx context.Context, data *Tweet) error {
	publicTweetTidKey := fmt.Sprintf("%s%v", cachePublicTweetTidPrefix, data.Tid)
	_, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("update %s set %s where tid = $1", m.table, tweetRowsWithPlaceHolder)
		return conn.ExecCtx(ctx, query, data.Tid, data.Uid, data.Content, data.MediaUrls, data.Tags, data.IsPublic, data.LikeCount, data.CommentCount, data.IsDeleted)
	}, publicTweetTidKey)
	return err
}

func (m *defaultTweetModel) formatPrimary(primary any) string {
	return fmt.Sprintf("%s%v", cachePublicTweetTidPrefix, primary)
}

func (m *defaultTweetModel) queryPrimary(ctx context.Context, conn sqlx.SqlConn, v, primary any) error {
	query := fmt.Sprintf("select %s from %s where tid = $1 limit 1", tweetRows, m.table)
	return conn.QueryRowCtx(ctx, v, query, primary)
}

func (m *defaultTweetModel) tableName() string {
	return m.table
}
