// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.9.2

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/cache"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	tweetStatsLogFieldNames          = builder.RawFieldNames(&TweetStatsLog{}, true)
	tweetStatsLogRows                = strings.Join(tweetStatsLogFieldNames, ",")
	tweetStatsLogRowsExpectAutoSet   = strings.Join(stringx.Remove(tweetStatsLogFieldNames, "log_id", "create_at", "create_time", "created_at", "update_at", "update_time", "updated_at"), ",")
	tweetStatsLogRowsWithPlaceHolder = builder.PostgreSqlJoin(stringx.Remove(tweetStatsLogFieldNames, "log_id", "create_at", "create_time", "created_at", "update_at", "update_time", "updated_at"))

	cachePublicTweetStatsLogLogIdPrefix = "cache:public:tweetStatsLog:logId:"
)

type (
	tweetStatsLogModel interface {
		Insert(ctx context.Context, data *TweetStatsLog) (sql.Result, error)
		FindOne(ctx context.Context, logId int64) (*TweetStatsLog, error)
		Update(ctx context.Context, data *TweetStatsLog) error
		Delete(ctx context.Context, logId int64) error
	}

	defaultTweetStatsLogModel struct {
		sqlc.CachedConn
		table string
	}

	TweetStatsLog struct {
		LogId       int64     `db:"log_id"`       // 日志ID，自增主键
		Tid         int64     `db:"tid"`          // 推文ID，关联tweet表
		UpdateType  int64     `db:"update_type"`  // 变更类型：0未知(保留)，1点赞数，2评论数
		Delta       int64     `db:"delta"`        // 变化量（正负）
		UpdateFrom  int64     `db:"update_from"`  // 来源服务：0用户,1内容,2互动,3通知,4推荐搜索
		BeforeValue int64     `db:"before_value"` // 变更前值
		AfterValue  int64     `db:"after_value"`  // 变更后值
		CreatedAt   time.Time `db:"created_at"`   // 日志创建时间
	}
)

func newTweetStatsLogModel(conn sqlx.SqlConn, c cache.CacheConf, opts ...cache.Option) *defaultTweetStatsLogModel {
	return &defaultTweetStatsLogModel{
		CachedConn: sqlc.NewConn(conn, c, opts...),
		table:      `"public"."tweet_stats_log"`,
	}
}

func (m *defaultTweetStatsLogModel) Delete(ctx context.Context, logId int64) error {
	publicTweetStatsLogLogIdKey := fmt.Sprintf("%s%v", cachePublicTweetStatsLogLogIdPrefix, logId)
	_, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("delete from %s where log_id = $1", m.table)
		return conn.ExecCtx(ctx, query, logId)
	}, publicTweetStatsLogLogIdKey)
	return err
}

func (m *defaultTweetStatsLogModel) FindOne(ctx context.Context, logId int64) (*TweetStatsLog, error) {
	publicTweetStatsLogLogIdKey := fmt.Sprintf("%s%v", cachePublicTweetStatsLogLogIdPrefix, logId)
	var resp TweetStatsLog
	err := m.QueryRowCtx(ctx, &resp, publicTweetStatsLogLogIdKey, func(ctx context.Context, conn sqlx.SqlConn, v any) error {
		query := fmt.Sprintf("select %s from %s where log_id = $1 limit 1", tweetStatsLogRows, m.table)
		return conn.QueryRowCtx(ctx, v, query, logId)
	})
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultTweetStatsLogModel) Insert(ctx context.Context, data *TweetStatsLog) (sql.Result, error) {
	publicTweetStatsLogLogIdKey := fmt.Sprintf("%s%v", cachePublicTweetStatsLogLogIdPrefix, data.LogId)
	ret, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("insert into %s (%s) values ($1, $2, $3, $4, $5, $6, $7)", m.table, tweetStatsLogRowsExpectAutoSet)
		return conn.ExecCtx(ctx, query, data.Tid, data.UpdateType, data.Delta, data.UpdateFrom, data.BeforeValue, data.AfterValue)
	}, publicTweetStatsLogLogIdKey)
	return ret, err
}

func (m *defaultTweetStatsLogModel) Update(ctx context.Context, data *TweetStatsLog) error {
	publicTweetStatsLogLogIdKey := fmt.Sprintf("%s%v", cachePublicTweetStatsLogLogIdPrefix, data.LogId)
	_, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("update %s set %s where log_id = $1", m.table, tweetStatsLogRowsWithPlaceHolder)
		return conn.ExecCtx(ctx, query, data.LogId, data.Tid, data.UpdateType, data.Delta, data.UpdateFrom, data.BeforeValue, data.AfterValue)
	}, publicTweetStatsLogLogIdKey)
	return err
}

func (m *defaultTweetStatsLogModel) formatPrimary(primary any) string {
	return fmt.Sprintf("%s%v", cachePublicTweetStatsLogLogIdPrefix, primary)
}

func (m *defaultTweetStatsLogModel) queryPrimary(ctx context.Context, conn sqlx.SqlConn, v, primary any) error {
	query := fmt.Sprintf("select %s from %s where log_id = $1 limit 1", tweetStatsLogRows, m.table)
	return conn.QueryRowCtx(ctx, v, query, primary)
}

func (m *defaultTweetStatsLogModel) tableName() string {
	return m.table
}
