// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2
// Source: userCenter.proto

package usercenter

import (
	"context"

	"gozeroX/app/usercenter/cmd/rpc/pb"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	BatchUserBriefReq  = pb.BatchUserBriefReq
	BatchUserBriefResp = pb.BatchUserBriefResp
	GetUserInfoReq     = pb.GetUserInfoReq
	GetUserInfoResp    = pb.GetUserInfoResp
	JwtToken           = pb.JwtToken
	LoginReq           = pb.LoginReq
	LoginResp          = pb.LoginResp
	RegisterReq        = pb.RegisterReq
	RegisterResp       = pb.RegisterResp
	UpdateStatsUidReq  = pb.UpdateStatsUidReq
	UpdateStatsUidResp = pb.UpdateStatsUidResp
	UserBrief          = pb.UserBrief
	UserInfo           = pb.UserInfo

	UserCenter interface {
		// 用户注册（返回token）
		Register(ctx context.Context, in *RegisterReq, opts ...grpc.CallOption) (*RegisterResp, error)
		// 用户登录（返回user_info + token）
		Login(ctx context.Context, in *LoginReq, opts ...grpc.CallOption) (*LoginResp, error)
		// 获取用户信息
		GetUserInfo(ctx context.Context, in *GetUserInfoReq, opts ...grpc.CallOption) (*GetUserInfoResp, error)
		// 批量获取用户简要信息（给互动微服务的）
		BatchGetUserBrief(ctx context.Context, in *BatchUserBriefReq, opts ...grpc.CallOption) (*BatchUserBriefResp, error)
		// 更新用户统计（给内容微服务和互动微服务）
		UpdateStatsUid(ctx context.Context, in *UpdateStatsUidReq, opts ...grpc.CallOption) (*UpdateStatsUidResp, error)
	}

	defaultUserCenter struct {
		cli zrpc.Client
	}
)

func NewUserCenter(cli zrpc.Client) UserCenter {
	return &defaultUserCenter{
		cli: cli,
	}
}

// 用户注册（返回token）
func (m *defaultUserCenter) Register(ctx context.Context, in *RegisterReq, opts ...grpc.CallOption) (*RegisterResp, error) {
	client := pb.NewUserCenterClient(m.cli.Conn())
	return client.Register(ctx, in, opts...)
}

// 用户登录（返回user_info + token）
func (m *defaultUserCenter) Login(ctx context.Context, in *LoginReq, opts ...grpc.CallOption) (*LoginResp, error) {
	client := pb.NewUserCenterClient(m.cli.Conn())
	return client.Login(ctx, in, opts...)
}

// 获取用户信息
func (m *defaultUserCenter) GetUserInfo(ctx context.Context, in *GetUserInfoReq, opts ...grpc.CallOption) (*GetUserInfoResp, error) {
	client := pb.NewUserCenterClient(m.cli.Conn())
	return client.GetUserInfo(ctx, in, opts...)
}

// 批量获取用户简要信息（给互动微服务的）
func (m *defaultUserCenter) BatchGetUserBrief(ctx context.Context, in *BatchUserBriefReq, opts ...grpc.CallOption) (*BatchUserBriefResp, error) {
	client := pb.NewUserCenterClient(m.cli.Conn())
	return client.BatchGetUserBrief(ctx, in, opts...)
}

// 更新用户统计（给内容微服务和互动微服务）
func (m *defaultUserCenter) UpdateStatsUid(ctx context.Context, in *UpdateStatsUidReq, opts ...grpc.CallOption) (*UpdateStatsUidResp, error) {
	client := pb.NewUserCenterClient(m.cli.Conn())
	return client.UpdateStatsUid(ctx, in, opts...)
}
