// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1
// Source: interactService.proto

package interaction

import (
	"context"

	"gozeroX/app/interactService/cmd/rpc/pb"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	CommentInfo         = pb.CommentInfo
	CreateCommentReq    = pb.CreateCommentReq
	CreateCommentResp   = pb.CreateCommentResp
	DeleteCommentReq    = pb.DeleteCommentReq
	DeleteCommentResp   = pb.DeleteCommentResp
	GetCommentsReq      = pb.GetCommentsReq
	GetCommentsResp     = pb.GetCommentsResp
	GetRepliesReq       = pb.GetRepliesReq
	GetRepliesResp      = pb.GetRepliesResp
	GetUserAllLikesReq  = pb.GetUserAllLikesReq
	GetUserAllLikesResp = pb.GetUserAllLikesResp
	LikeCommentInfo     = pb.LikeCommentInfo
	LikeCommentReq      = pb.LikeCommentReq
	LikeCommentResp     = pb.LikeCommentResp
	LikeTweetInfo       = pb.LikeTweetInfo
	LikeTweetReq        = pb.LikeTweetReq
	LikeTweetResp       = pb.LikeTweetResp
	UserCommentLike     = pb.UserCommentLike
	UserTweetLike       = pb.UserTweetLike

	Interaction interface {
		// 评论服务
		CreateComment(ctx context.Context, in *CreateCommentReq, opts ...grpc.CallOption) (*CreateCommentResp, error)
		DeleteComment(ctx context.Context, in *DeleteCommentReq, opts ...grpc.CallOption) (*DeleteCommentResp, error)
		GetComments(ctx context.Context, in *GetCommentsReq, opts ...grpc.CallOption) (*GetCommentsResp, error)
		GetReplies(ctx context.Context, in *GetRepliesReq, opts ...grpc.CallOption) (*GetRepliesResp, error)
		// 点赞/取消点赞
		LikeTweet(ctx context.Context, in *LikeTweetReq, opts ...grpc.CallOption) (*LikeTweetResp, error)
		LikeComment(ctx context.Context, in *LikeCommentReq, opts ...grpc.CallOption) (*LikeCommentResp, error)
		// 获取用户所有点赞关系（登录时调用）
		GetUserAllLikes(ctx context.Context, in *GetUserAllLikesReq, opts ...grpc.CallOption) (*GetUserAllLikesResp, error)
	}

	defaultInteraction struct {
		cli zrpc.Client
	}
)

func NewInteraction(cli zrpc.Client) Interaction {
	return &defaultInteraction{
		cli: cli,
	}
}

// 评论服务
func (m *defaultInteraction) CreateComment(ctx context.Context, in *CreateCommentReq, opts ...grpc.CallOption) (*CreateCommentResp, error) {
	client := pb.NewInteractionClient(m.cli.Conn())
	return client.CreateComment(ctx, in, opts...)
}

func (m *defaultInteraction) DeleteComment(ctx context.Context, in *DeleteCommentReq, opts ...grpc.CallOption) (*DeleteCommentResp, error) {
	client := pb.NewInteractionClient(m.cli.Conn())
	return client.DeleteComment(ctx, in, opts...)
}

func (m *defaultInteraction) GetComments(ctx context.Context, in *GetCommentsReq, opts ...grpc.CallOption) (*GetCommentsResp, error) {
	client := pb.NewInteractionClient(m.cli.Conn())
	return client.GetComments(ctx, in, opts...)
}

func (m *defaultInteraction) GetReplies(ctx context.Context, in *GetRepliesReq, opts ...grpc.CallOption) (*GetRepliesResp, error) {
	client := pb.NewInteractionClient(m.cli.Conn())
	return client.GetReplies(ctx, in, opts...)
}

// 点赞/取消点赞
func (m *defaultInteraction) LikeTweet(ctx context.Context, in *LikeTweetReq, opts ...grpc.CallOption) (*LikeTweetResp, error) {
	client := pb.NewInteractionClient(m.cli.Conn())
	return client.LikeTweet(ctx, in, opts...)
}

func (m *defaultInteraction) LikeComment(ctx context.Context, in *LikeCommentReq, opts ...grpc.CallOption) (*LikeCommentResp, error) {
	client := pb.NewInteractionClient(m.cli.Conn())
	return client.LikeComment(ctx, in, opts...)
}

// 获取用户所有点赞关系（登录时调用）
func (m *defaultInteraction) GetUserAllLikes(ctx context.Context, in *GetUserAllLikesReq, opts ...grpc.CallOption) (*GetUserAllLikesResp, error) {
	client := pb.NewInteractionClient(m.cli.Conn())
	return client.GetUserAllLikes(ctx, in, opts...)
}
