// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2
// Source: interactService.proto

package interaction

import (
	"context"

	"gozeroX/app/interactService/cmd/rpc/pb"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	BatchGetLikeStatusReq  = pb.BatchGetLikeStatusReq
	BatchGetLikeStatusResp = pb.BatchGetLikeStatusResp
	CommentInfo            = pb.CommentInfo
	CreateCommentReq       = pb.CreateCommentReq
	CreateCommentResp      = pb.CreateCommentResp
	DeleteCommentReq       = pb.DeleteCommentReq
	DeleteCommentResp      = pb.DeleteCommentResp
	GetCommentsReq         = pb.GetCommentsReq
	GetCommentsResp        = pb.GetCommentsResp
	GetLikeStatusReq       = pb.GetLikeStatusReq
	GetLikeStatusResp      = pb.GetLikeStatusResp
	GetRepliesReq          = pb.GetRepliesReq
	GetRepliesResp         = pb.GetRepliesResp
	LikeInfo               = pb.LikeInfo
	LikeReq                = pb.LikeReq
	LikeResp               = pb.LikeResp
	PageReq                = pb.PageReq
	PageResp               = pb.PageResp

	Interaction interface {
		// 评论服务
		CreateComment(ctx context.Context, in *CreateCommentReq, opts ...grpc.CallOption) (*CreateCommentResp, error)
		DeleteComment(ctx context.Context, in *DeleteCommentReq, opts ...grpc.CallOption) (*DeleteCommentResp, error)
		GetComments(ctx context.Context, in *GetCommentsReq, opts ...grpc.CallOption) (*GetCommentsResp, error)
		GetReplies(ctx context.Context, in *GetRepliesReq, opts ...grpc.CallOption) (*GetRepliesResp, error)
		// 点赞服务
		Like(ctx context.Context, in *LikeReq, opts ...grpc.CallOption) (*LikeResp, error)
		GetLikeStatus(ctx context.Context, in *GetLikeStatusReq, opts ...grpc.CallOption) (*GetLikeStatusResp, error)
		BatchGetLikeStatus(ctx context.Context, in *BatchGetLikeStatusReq, opts ...grpc.CallOption) (*BatchGetLikeStatusResp, error)
	}

	defaultInteraction struct {
		cli zrpc.Client
	}
)

func NewInteraction(cli zrpc.Client) Interaction {
	return &defaultInteraction{
		cli: cli,
	}
}

// 评论服务
func (m *defaultInteraction) CreateComment(ctx context.Context, in *CreateCommentReq, opts ...grpc.CallOption) (*CreateCommentResp, error) {
	client := pb.NewInteractionClient(m.cli.Conn())
	return client.CreateComment(ctx, in, opts...)
}

func (m *defaultInteraction) DeleteComment(ctx context.Context, in *DeleteCommentReq, opts ...grpc.CallOption) (*DeleteCommentResp, error) {
	client := pb.NewInteractionClient(m.cli.Conn())
	return client.DeleteComment(ctx, in, opts...)
}

func (m *defaultInteraction) GetComments(ctx context.Context, in *GetCommentsReq, opts ...grpc.CallOption) (*GetCommentsResp, error) {
	client := pb.NewInteractionClient(m.cli.Conn())
	return client.GetComments(ctx, in, opts...)
}

func (m *defaultInteraction) GetReplies(ctx context.Context, in *GetRepliesReq, opts ...grpc.CallOption) (*GetRepliesResp, error) {
	client := pb.NewInteractionClient(m.cli.Conn())
	return client.GetReplies(ctx, in, opts...)
}

// 点赞服务
func (m *defaultInteraction) Like(ctx context.Context, in *LikeReq, opts ...grpc.CallOption) (*LikeResp, error) {
	client := pb.NewInteractionClient(m.cli.Conn())
	return client.Like(ctx, in, opts...)
}

func (m *defaultInteraction) GetLikeStatus(ctx context.Context, in *GetLikeStatusReq, opts ...grpc.CallOption) (*GetLikeStatusResp, error) {
	client := pb.NewInteractionClient(m.cli.Conn())
	return client.GetLikeStatus(ctx, in, opts...)
}

func (m *defaultInteraction) BatchGetLikeStatus(ctx context.Context, in *BatchGetLikeStatusReq, opts ...grpc.CallOption) (*BatchGetLikeStatusResp, error) {
	client := pb.NewInteractionClient(m.cli.Conn())
	return client.BatchGetLikeStatus(ctx, in, opts...)
}
