// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1

package types

type CommentInfo struct {
	SnowCid    int64  `json:"snowCid,string"`  // 评论ID（雪花ID，string格式给前端）
	SnowTid    int64  `json:"snowTid,string"`  // 推文ID
	Uid        int64  `json:"uid"`             // 用户ID
	NickName   string `json:"nickname"`        // 从用户服务获取
	Avatar     string `json:"avatar"`          // 从用户服务获取
	ParentId   int64  `json:"parentId,string"` // 父评论ID，0表示顶级评论
	RootId     int64  `json:"rootId,string"`   // 根评论ID，0代表根评论
	Content    string `json:"content"`         // 评论内容
	LikeCount  int64  `json:"likeCount"`       // 点赞数
	ReplyCount int64  `json:"replyCount"`      // 回复数
	CreateTime int64  `json:"createTime"`      // 创建时间（毫秒级时间戳）
}

type CreateCommentReq struct {
	SnowTid  int64  `json:"snowTid,string"`  // 推文ID（雪花ID）
	Content  string `json:"content"`         // 评论内容
	ParentId int64  `json:"parentId,string"` // 父评论ID，0表示顶级评论
	RootId   int64  `json:"rootId,string"`   //根评论ID，0表示顶级评论
}

type CreateCommentResp struct {
	Code    int         `json:"code"`
	Message string      `json:"message"`
	Data    CommentInfo `json:"data"`
}

type DeleteCommentReq struct {
	SnowCid int64 `path:"snowCid,string"` // 评论ID（雪花ID）
}

type DeleteCommentResp struct {
	Code    int    `json:"code"`
	Message string `json:"message"`
}

type GetCommentsReq struct {
	SnowTid int64 `form:"snowTid,string"`   // 推文ID（雪花ID）
	Cursor  int64 `form:"cursor,optional"`  // 游标：上次请求最后一条评论的createTime或综合分值，首次请求不传或传0
	Limit   int64 `form:"limit,default=20"` // 请求数量
	Sort    int64 `form:"sort,default=0"`   // 0-综合排序（热门），1-按时间倒序（最新）
}

type GetCommentsResp struct {
	Code    int           `json:"code"`
	Message string        `json:"message"`
	Data    []CommentInfo `json:"data"`
	Total   int64         `json:"total"` // 总数
}

type GetRepliesReq struct {
	RootCid int64 `form:"rootCid,string"`   // 根评论ID（雪花ID）
	Cursor  int64 `form:"cursor,optional"`  // 游标：上次请求最后一条评论的createTime，首次请求不传或传0
	Limit   int64 `form:"limit,default=20"` // 请求数量
}

type GetRepliesResp struct {
	Code    int           `json:"code"`
	Message string        `json:"message"`
	Data    []CommentInfo `json:"data"`
	Total   int64         `json:"total"` // 总数
}

type GetUserLikesAllResp struct {
	Code             int               `json:"code"`
	Message          string            `json:"message"`
	LikesForTweets   []UserTweetLike   `json:"likesForTweets"`
	LikesForComments []UserCommentLike `json:"likesForComments"`
}

type GetUserlikesAllReq struct {
	LikesCursor int64 `json:"likesCursor"`
}

type LikeInfo struct {
	TargetType  int64 `json:"targetType"`
	TargetId    int64 `json:"targetId,string"`
	SnowLikesId int64 `json:"snowLikesId,string"` // 返回点赞记录ID，前端需要保存
	Status      int64 `json:"status"`
	UpdateTime  int64 `json"updateTime"`
}

type LikeReq struct {
	IsCreated   int64 `json:"isCreated"`               // 0-第一次操作（创建），1-非第一次（更新）
	SnowLikesId int64 `json:"snowLikesId,string"`      // 点赞记录ID，第一次操作时为0，更新时传之前的ID
	TargetType  int64 `json:"targetType"`              // 0-推文 1-评论
	TargetId    int64 `json:"targetId,string"`         // 目标ID（推文ID或评论ID，雪花ID）
	SnowTid     int64 `json:"snowTid,string,optional"` // 评论点赞时传入：评论所属推文ID（推文点赞时忽略）
	Status      int64 `json:"status"`                  // 1-点赞 0-取消
}

type LikeResp struct {
	Code    int      `json:"code"`
	Message string   `json:"message"`
	Data    LikeInfo `json:"data"`
}

type UserCommentLike struct {
	SnowTid     int64 `json:"snowTid,string"`     // 评论所属推文ID
	SnowCid     int64 `json:"snowCid,string"`     // 评论ID
	SnowLikesId int64 `json:"snowLikesId,string"` // 点赞记录ID
	Status      int64 `json:"status"`             // 1-已点赞，0-已取消
}

type UserTweetLike struct {
	SnowTid     int64 `json:"snowTid,string"`     // 推文ID
	SnowLikesId int64 `json:"snowLikesId,string"` // 点赞记录ID
	Status      int64 `json:"status"`             // 1-已点赞，0-已取消
}
