// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.10.1

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/cache"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	commentFieldNames          = builder.RawFieldNames(&Comment{}, true)
	commentRows                = strings.Join(commentFieldNames, ",")
	commentRowsExpectAutoSet   = strings.Join(stringx.Remove(commentFieldNames, "create_at", "create_time", "created_at", "update_at", "update_time", "updated_at"), ",")
	commentRowsWithPlaceHolder = builder.PostgreSqlJoin(stringx.Remove(commentFieldNames, "snow_cid", "create_at", "create_time", "created_at", "update_at", "update_time", "updated_at"))

	cachePublicCommentSnowCidPrefix = "cache:public:comment:snowCid:"
)

type (
	commentModel interface {
		Insert(ctx context.Context, data *Comment) (sql.Result, error)
		FindOne(ctx context.Context, snowCid int64) (*Comment, error)
		Update(ctx context.Context, data *Comment) error
		Delete(ctx context.Context, snowCid int64) error
	}

	defaultCommentModel struct {
		sqlc.CachedConn
		table string
	}

	Comment struct {
		SnowCid    int64  `db:"snow_cid"`    // 业务主键ID（雪花算法）
		Cid        int64  `db:"cid"`         // 自增主键ID（仅用于查看计数，不使用）
		SnowTid    int64  `db:"snow_tid"`    // 推文ID（雪花算法）
		Uid        int64  `db:"uid"`         // 评论用户ID
		ParentId   int64  `db:"parent_id"`   // 父评论ID（0表示顶级评论）
		RootId     int64  `db:"root_id"`     // 根评论ID
		Content    string `db:"content"`     // 评论内容
		LikeCount  int64  `db:"like_count"`  // 点赞数
		ReplyCount int64  `db:"reply_count"` // 回复数
		CreatedAt  int64  `db:"created_at"`  // 创建时间（毫秒级时间戳）
		UpdatedAt  int64  `db:"updated_at"`  // 更新时间（毫秒级时间戳）
		Status     int64  `db:"status"`      // 状态：0正常，1删除，2审核中
	}
)

func newCommentModel(conn sqlx.SqlConn, c cache.CacheConf, opts ...cache.Option) *defaultCommentModel {
	return &defaultCommentModel{
		CachedConn: sqlc.NewConn(conn, c, opts...),
		table:      `"public"."comment"`,
	}
}

func (m *defaultCommentModel) Delete(ctx context.Context, snowCid int64) error {
	publicCommentSnowCidKey := fmt.Sprintf("%s%v", cachePublicCommentSnowCidPrefix, snowCid)
	_, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("delete from %s where snow_cid = $1", m.table)
		return conn.ExecCtx(ctx, query, snowCid)
	}, publicCommentSnowCidKey)
	return err
}

func (m *defaultCommentModel) FindOne(ctx context.Context, snowCid int64) (*Comment, error) {
	publicCommentSnowCidKey := fmt.Sprintf("%s%v", cachePublicCommentSnowCidPrefix, snowCid)
	var resp Comment
	err := m.QueryRowCtx(ctx, &resp, publicCommentSnowCidKey, func(ctx context.Context, conn sqlx.SqlConn, v any) error {
		query := fmt.Sprintf("select %s from %s where snow_cid = $1 limit 1", commentRows, m.table)
		return conn.QueryRowCtx(ctx, v, query, snowCid)
	})
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultCommentModel) Insert(ctx context.Context, data *Comment) (sql.Result, error) {
	publicCommentSnowCidKey := fmt.Sprintf("%s%v", cachePublicCommentSnowCidPrefix, data.SnowCid)
	ret, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("insert into %s (%s) values ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10)", m.table, commentRowsExpectAutoSet)
		return conn.ExecCtx(ctx, query, data.SnowCid, data.Cid, data.SnowTid, data.Uid, data.ParentId, data.RootId, data.Content, data.LikeCount, data.ReplyCount, data.Status)
	}, publicCommentSnowCidKey)
	return ret, err
}

func (m *defaultCommentModel) Update(ctx context.Context, data *Comment) error {
	publicCommentSnowCidKey := fmt.Sprintf("%s%v", cachePublicCommentSnowCidPrefix, data.SnowCid)
	_, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("update %s set %s where snow_cid = $1", m.table, commentRowsWithPlaceHolder)
		return conn.ExecCtx(ctx, query, data.SnowCid, data.Cid, data.SnowTid, data.Uid, data.ParentId, data.RootId, data.Content, data.LikeCount, data.ReplyCount, data.Status)
	}, publicCommentSnowCidKey)
	return err
}

func (m *defaultCommentModel) formatPrimary(primary any) string {
	return fmt.Sprintf("%s%v", cachePublicCommentSnowCidPrefix, primary)
}

func (m *defaultCommentModel) queryPrimary(ctx context.Context, conn sqlx.SqlConn, v, primary any) error {
	query := fmt.Sprintf("select %s from %s where snow_cid = $1 limit 1", commentRows, m.table)
	return conn.QueryRowCtx(ctx, v, query, primary)
}

func (m *defaultCommentModel) tableName() string {
	return m.table
}
