// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.9.2

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/cache"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	commentFieldNames          = builder.RawFieldNames(&Comment{}, true)
	commentRows                = strings.Join(commentFieldNames, ",")
	commentRowsExpectAutoSet   = strings.Join(stringx.Remove(commentFieldNames, "cid", "create_at", "create_time", "created_at", "update_at", "update_time", "updated_at"), ",")
	commentRowsWithPlaceHolder = builder.PostgreSqlJoin(stringx.Remove(commentFieldNames, "cid", "create_at", "create_time", "created_at", "update_at", "update_time", "updated_at"))

	cachePublicCommentCidPrefix     = "cache:public:comment:cid:"
	cachePublicCommentSnowCidPrefix = "cache:public:comment:snowCid:"
)

type (
	commentModel interface {
		Insert(ctx context.Context, data *Comment) (sql.Result, error)
		FindOne(ctx context.Context, cid int64) (*Comment, error)
		FindOneBySnowCid(ctx context.Context, snowCid int64) (*Comment, error)
		Update(ctx context.Context, data *Comment) error
		Delete(ctx context.Context, cid int64) error
	}

	defaultCommentModel struct {
		sqlc.CachedConn
		table string
	}

	Comment struct {
		Cid        int64     `db:"cid"`         // 评论ID，没用
		Tid        int64     `db:"tid"`         // 推文ID，关联tweet表
		Uid        int64     `db:"uid"`         // 评论用户ID，关联user表
		ParentId   int64     `db:"parent_id"`   // 父评论ID（0表示顶级评论）
		RootId     int64     `db:"root_id"`     // 根评论ID（顶级评论该字段=cid）
		Content    string    `db:"content"`     // 评论内容
		LikeCount  int64     `db:"like_count"`  // 点赞数
		ReplyCount int64     `db:"reply_count"` // 回复数
		Status     int64     `db:"status"`      // 状态：0-正常，1-删除（软删），2-审核中
		CreateTime time.Time `db:"create_time"` // 创建时间（带时区）
		SnowCid    int64     `db:"snow_cid"`    // 雪花ID业务主键（前端后端交互主要使用）
	}
)

func newCommentModel(conn sqlx.SqlConn, c cache.CacheConf, opts ...cache.Option) *defaultCommentModel {
	return &defaultCommentModel{
		CachedConn: sqlc.NewConn(conn, c, opts...),
		table:      `"public"."comment"`,
	}
}

func (m *defaultCommentModel) Delete(ctx context.Context, cid int64) error {
	data, err := m.FindOne(ctx, cid)
	if err != nil {
		return err
	}

	publicCommentCidKey := fmt.Sprintf("%s%v", cachePublicCommentCidPrefix, cid)
	publicCommentSnowCidKey := fmt.Sprintf("%s%v", cachePublicCommentSnowCidPrefix, data.SnowCid)
	_, err = m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("delete from %s where cid = $1", m.table)
		return conn.ExecCtx(ctx, query, cid)
	}, publicCommentCidKey, publicCommentSnowCidKey)
	return err
}

func (m *defaultCommentModel) FindOne(ctx context.Context, cid int64) (*Comment, error) {
	publicCommentCidKey := fmt.Sprintf("%s%v", cachePublicCommentCidPrefix, cid)
	var resp Comment
	err := m.QueryRowCtx(ctx, &resp, publicCommentCidKey, func(ctx context.Context, conn sqlx.SqlConn, v any) error {
		query := fmt.Sprintf("select %s from %s where cid = $1 limit 1", commentRows, m.table)
		return conn.QueryRowCtx(ctx, v, query, cid)
	})
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultCommentModel) FindOneBySnowCid(ctx context.Context, snowCid int64) (*Comment, error) {
	publicCommentSnowCidKey := fmt.Sprintf("%s%v", cachePublicCommentSnowCidPrefix, snowCid)
	var resp Comment
	err := m.QueryRowIndexCtx(ctx, &resp, publicCommentSnowCidKey, m.formatPrimary, func(ctx context.Context, conn sqlx.SqlConn, v any) (i any, e error) {
		query := fmt.Sprintf("select %s from %s where snow_cid = $1 limit 1", commentRows, m.table)
		if err := conn.QueryRowCtx(ctx, &resp, query, snowCid); err != nil {
			return nil, err
		}
		return resp.Cid, nil
	}, m.queryPrimary)
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultCommentModel) Insert(ctx context.Context, data *Comment) (sql.Result, error) {
	publicCommentCidKey := fmt.Sprintf("%s%v", cachePublicCommentCidPrefix, data.Cid)
	publicCommentSnowCidKey := fmt.Sprintf("%s%v", cachePublicCommentSnowCidPrefix, data.SnowCid)
	ret, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("insert into %s (%s) values ($1, $2, $3, $4, $5, $6, $7, $8, $9)", m.table, commentRowsExpectAutoSet)
		return conn.ExecCtx(ctx, query, data.Tid, data.Uid, data.ParentId, data.RootId, data.Content, data.LikeCount, data.ReplyCount, data.Status, data.SnowCid)
	}, publicCommentCidKey, publicCommentSnowCidKey)
	return ret, err
}

func (m *defaultCommentModel) Update(ctx context.Context, newData *Comment) error {
	data, err := m.FindOne(ctx, newData.Cid)
	if err != nil {
		return err
	}

	publicCommentCidKey := fmt.Sprintf("%s%v", cachePublicCommentCidPrefix, data.Cid)
	publicCommentSnowCidKey := fmt.Sprintf("%s%v", cachePublicCommentSnowCidPrefix, data.SnowCid)
	_, err = m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("update %s set %s where cid = $1", m.table, commentRowsWithPlaceHolder)
		return conn.ExecCtx(ctx, query, newData.Cid, newData.Tid, newData.Uid, newData.ParentId, newData.RootId, newData.Content, newData.LikeCount, newData.ReplyCount, newData.Status, newData.SnowCid)
	}, publicCommentCidKey, publicCommentSnowCidKey)
	return err
}

func (m *defaultCommentModel) formatPrimary(primary any) string {
	return fmt.Sprintf("%s%v", cachePublicCommentCidPrefix, primary)
}

func (m *defaultCommentModel) queryPrimary(ctx context.Context, conn sqlx.SqlConn, v, primary any) error {
	query := fmt.Sprintf("select %s from %s where cid = $1 limit 1", commentRows, m.table)
	return conn.QueryRowCtx(ctx, v, query, primary)
}

func (m *defaultCommentModel) tableName() string {
	return m.table
}
