// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.9.2

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/cache"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	likesFieldNames          = builder.RawFieldNames(&Likes{}, true)
	likesRows                = strings.Join(likesFieldNames, ",")
	likesRowsExpectAutoSet   = strings.Join(stringx.Remove(likesFieldNames, "likes_id", "create_at", "create_time", "created_at", "update_at", "update_time", "updated_at"), ",")
	likesRowsWithPlaceHolder = builder.PostgreSqlJoin(stringx.Remove(likesFieldNames, "likes_id", "create_at", "create_time", "created_at", "update_at", "update_time", "updated_at"))

	cachePublicLikesLikesIdPrefix               = "cache:public:likes:likesId:"
	cachePublicLikesSnowLikesIdPrefix           = "cache:public:likes:snowLikesId:"
	cachePublicLikesUidTargetTypeTargetIdPrefix = "cache:public:likes:uid:targetType:targetId:"
)

type (
	likesModel interface {
		Insert(ctx context.Context, data *Likes) (sql.Result, error)
		FindOne(ctx context.Context, likesId int64) (*Likes, error)
		FindOneBySnowLikesId(ctx context.Context, snowLikesId int64) (*Likes, error)
		FindOneByUidTargetTypeTargetId(ctx context.Context, uid int64, targetType int64, targetId int64) (*Likes, error)
		Update(ctx context.Context, data *Likes) error
		Delete(ctx context.Context, likesId int64) error
	}

	defaultLikesModel struct {
		sqlc.CachedConn
		table string
	}

	Likes struct {
		LikesId     int64     `db:"likes_id"`      // 点赞ID，自增主键（备用）
		Uid         int64     `db:"uid"`           // 点赞用户ID，关联user表
		TargetType  int64     `db:"target_type"`   // 目标类型：1-内容(tid)，2-评论(cid)
		TargetId    int64     `db:"target_id"`     // 目标ID（内容就是tid，评论就是cid/snow_cid）
		Status      int64     `db:"status"`        // 状态：1-点赞，0-取消
		CreateTime  time.Time `db:"create_time"`   // 创建时间（带时区）
		UpdateTime  time.Time `db:"update_time"`   // 更新时间（带时区）
		SnowLikesId int64     `db:"snow_likes_id"` // 雪花ID业务主键（前端后端交互主要使用）
	}
)

func newLikesModel(conn sqlx.SqlConn, c cache.CacheConf, opts ...cache.Option) *defaultLikesModel {
	return &defaultLikesModel{
		CachedConn: sqlc.NewConn(conn, c, opts...),
		table:      `"public"."likes"`,
	}
}

func (m *defaultLikesModel) Delete(ctx context.Context, likesId int64) error {
	data, err := m.FindOne(ctx, likesId)
	if err != nil {
		return err
	}

	publicLikesLikesIdKey := fmt.Sprintf("%s%v", cachePublicLikesLikesIdPrefix, likesId)
	publicLikesSnowLikesIdKey := fmt.Sprintf("%s%v", cachePublicLikesSnowLikesIdPrefix, data.SnowLikesId)
	publicLikesUidTargetTypeTargetIdKey := fmt.Sprintf("%s%v:%v:%v", cachePublicLikesUidTargetTypeTargetIdPrefix, data.Uid, data.TargetType, data.TargetId)
	_, err = m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("delete from %s where likes_id = $1", m.table)
		return conn.ExecCtx(ctx, query, likesId)
	}, publicLikesLikesIdKey, publicLikesSnowLikesIdKey, publicLikesUidTargetTypeTargetIdKey)
	return err
}

func (m *defaultLikesModel) FindOne(ctx context.Context, likesId int64) (*Likes, error) {
	publicLikesLikesIdKey := fmt.Sprintf("%s%v", cachePublicLikesLikesIdPrefix, likesId)
	var resp Likes
	err := m.QueryRowCtx(ctx, &resp, publicLikesLikesIdKey, func(ctx context.Context, conn sqlx.SqlConn, v any) error {
		query := fmt.Sprintf("select %s from %s where likes_id = $1 limit 1", likesRows, m.table)
		return conn.QueryRowCtx(ctx, v, query, likesId)
	})
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultLikesModel) FindOneBySnowLikesId(ctx context.Context, snowLikesId int64) (*Likes, error) {
	publicLikesSnowLikesIdKey := fmt.Sprintf("%s%v", cachePublicLikesSnowLikesIdPrefix, snowLikesId)
	var resp Likes
	err := m.QueryRowIndexCtx(ctx, &resp, publicLikesSnowLikesIdKey, m.formatPrimary, func(ctx context.Context, conn sqlx.SqlConn, v any) (i any, e error) {
		query := fmt.Sprintf("select %s from %s where snow_likes_id = $1 limit 1", likesRows, m.table)
		if err := conn.QueryRowCtx(ctx, &resp, query, snowLikesId); err != nil {
			return nil, err
		}
		return resp.LikesId, nil
	}, m.queryPrimary)
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultLikesModel) FindOneByUidTargetTypeTargetId(ctx context.Context, uid int64, targetType int64, targetId int64) (*Likes, error) {
	publicLikesUidTargetTypeTargetIdKey := fmt.Sprintf("%s%v:%v:%v", cachePublicLikesUidTargetTypeTargetIdPrefix, uid, targetType, targetId)
	var resp Likes
	err := m.QueryRowIndexCtx(ctx, &resp, publicLikesUidTargetTypeTargetIdKey, m.formatPrimary, func(ctx context.Context, conn sqlx.SqlConn, v any) (i any, e error) {
		query := fmt.Sprintf("select %s from %s where uid = $1 and target_type = $2 and target_id = $3 limit 1", likesRows, m.table)
		if err := conn.QueryRowCtx(ctx, &resp, query, uid, targetType, targetId); err != nil {
			return nil, err
		}
		return resp.LikesId, nil
	}, m.queryPrimary)
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultLikesModel) Insert(ctx context.Context, data *Likes) (sql.Result, error) {
	publicLikesLikesIdKey := fmt.Sprintf("%s%v", cachePublicLikesLikesIdPrefix, data.LikesId)
	publicLikesSnowLikesIdKey := fmt.Sprintf("%s%v", cachePublicLikesSnowLikesIdPrefix, data.SnowLikesId)
	publicLikesUidTargetTypeTargetIdKey := fmt.Sprintf("%s%v:%v:%v", cachePublicLikesUidTargetTypeTargetIdPrefix, data.Uid, data.TargetType, data.TargetId)
	ret, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("insert into %s (%s) values ($1, $2, $3, $4, $5)", m.table, likesRowsExpectAutoSet)
		return conn.ExecCtx(ctx, query, data.Uid, data.TargetType, data.TargetId, data.Status, data.SnowLikesId)
	}, publicLikesLikesIdKey, publicLikesSnowLikesIdKey, publicLikesUidTargetTypeTargetIdKey)
	return ret, err
}

func (m *defaultLikesModel) Update(ctx context.Context, newData *Likes) error {
	data, err := m.FindOne(ctx, newData.LikesId)
	if err != nil {
		return err
	}

	publicLikesLikesIdKey := fmt.Sprintf("%s%v", cachePublicLikesLikesIdPrefix, data.LikesId)
	publicLikesSnowLikesIdKey := fmt.Sprintf("%s%v", cachePublicLikesSnowLikesIdPrefix, data.SnowLikesId)
	publicLikesUidTargetTypeTargetIdKey := fmt.Sprintf("%s%v:%v:%v", cachePublicLikesUidTargetTypeTargetIdPrefix, data.Uid, data.TargetType, data.TargetId)
	_, err = m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("update %s set %s where likes_id = $1", m.table, likesRowsWithPlaceHolder)
		return conn.ExecCtx(ctx, query, newData.LikesId, newData.Uid, newData.TargetType, newData.TargetId, newData.Status, newData.SnowLikesId)
	}, publicLikesLikesIdKey, publicLikesSnowLikesIdKey, publicLikesUidTargetTypeTargetIdKey)
	return err
}

func (m *defaultLikesModel) formatPrimary(primary any) string {
	return fmt.Sprintf("%s%v", cachePublicLikesLikesIdPrefix, primary)
}

func (m *defaultLikesModel) queryPrimary(ctx context.Context, conn sqlx.SqlConn, v, primary any) error {
	query := fmt.Sprintf("select %s from %s where likes_id = $1 limit 1", likesRows, m.table)
	return conn.QueryRowCtx(ctx, v, query, primary)
}

func (m *defaultLikesModel) tableName() string {
	return m.table
}
