// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.10.1

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/cache"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	likesTweetFieldNames          = builder.RawFieldNames(&LikesTweet{}, true)
	likesTweetRows                = strings.Join(likesTweetFieldNames, ",")
	likesTweetRowsExpectAutoSet   = strings.Join(stringx.Remove(likesTweetFieldNames, "create_at", "create_time", "created_at", "update_at", "update_time", "updated_at"), ",")
	likesTweetRowsWithPlaceHolder = builder.PostgreSqlJoin(stringx.Remove(likesTweetFieldNames, "snow_likes_id", "create_at", "create_time", "created_at", "update_at", "update_time", "updated_at"))

	cachePublicLikesTweetSnowLikesIdPrefix = "cache:public:likesTweet:snowLikesId:"
)

type (
	likesTweetModel interface {
		Insert(ctx context.Context, data *LikesTweet) (sql.Result, error)
		FindOne(ctx context.Context, snowLikesId int64) (*LikesTweet, error)
		Update(ctx context.Context, data *LikesTweet) error
		Delete(ctx context.Context, snowLikesId int64) error
	}

	defaultLikesTweetModel struct {
		sqlc.CachedConn
		table string
	}

	LikesTweet struct {
		SnowLikesId int64 `db:"snow_likes_id"` // 业务ID（前后端主要使用）
		Uid         int64 `db:"uid"`           // 点赞用户ID
		SnowTid     int64 `db:"snow_tid"`      // 推文ID
		CreatedAt   int64 `db:"created_at"`    // 创建时间（毫秒级时间戳）
		UpdatedAt   int64 `db:"updated_at"`    // 更新时间（毫秒级时间戳）
		Status      int64 `db:"status"`        // 状态：1点赞，0取消
	}
)

func newLikesTweetModel(conn sqlx.SqlConn, c cache.CacheConf, opts ...cache.Option) *defaultLikesTweetModel {
	return &defaultLikesTweetModel{
		CachedConn: sqlc.NewConn(conn, c, opts...),
		table:      `"public"."likes_tweet"`,
	}
}

func (m *defaultLikesTweetModel) Delete(ctx context.Context, snowLikesId int64) error {
	publicLikesTweetSnowLikesIdKey := fmt.Sprintf("%s%v", cachePublicLikesTweetSnowLikesIdPrefix, snowLikesId)
	_, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("delete from %s where snow_likes_id = $1", m.table)
		return conn.ExecCtx(ctx, query, snowLikesId)
	}, publicLikesTweetSnowLikesIdKey)
	return err
}

func (m *defaultLikesTweetModel) FindOne(ctx context.Context, snowLikesId int64) (*LikesTweet, error) {
	publicLikesTweetSnowLikesIdKey := fmt.Sprintf("%s%v", cachePublicLikesTweetSnowLikesIdPrefix, snowLikesId)
	var resp LikesTweet
	err := m.QueryRowCtx(ctx, &resp, publicLikesTweetSnowLikesIdKey, func(ctx context.Context, conn sqlx.SqlConn, v any) error {
		query := fmt.Sprintf("select %s from %s where snow_likes_id = $1 limit 1", likesTweetRows, m.table)
		return conn.QueryRowCtx(ctx, v, query, snowLikesId)
	})
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultLikesTweetModel) Insert(ctx context.Context, data *LikesTweet) (sql.Result, error) {
	publicLikesTweetSnowLikesIdKey := fmt.Sprintf("%s%v", cachePublicLikesTweetSnowLikesIdPrefix, data.SnowLikesId)
	ret, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("insert into %s (%s) values ($1, $2, $3, $4)", m.table, likesTweetRowsExpectAutoSet)
		return conn.ExecCtx(ctx, query, data.SnowLikesId, data.Uid, data.SnowTid, data.Status)
	}, publicLikesTweetSnowLikesIdKey)
	return ret, err
}

func (m *defaultLikesTweetModel) Update(ctx context.Context, data *LikesTweet) error {
	publicLikesTweetSnowLikesIdKey := fmt.Sprintf("%s%v", cachePublicLikesTweetSnowLikesIdPrefix, data.SnowLikesId)
	_, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("update %s set %s where snow_likes_id = $1", m.table, likesTweetRowsWithPlaceHolder)
		return conn.ExecCtx(ctx, query, data.SnowLikesId, data.Uid, data.SnowTid, data.Status)
	}, publicLikesTweetSnowLikesIdKey)
	return err
}

func (m *defaultLikesTweetModel) formatPrimary(primary any) string {
	return fmt.Sprintf("%s%v", cachePublicLikesTweetSnowLikesIdPrefix, primary)
}

func (m *defaultLikesTweetModel) queryPrimary(ctx context.Context, conn sqlx.SqlConn, v, primary any) error {
	query := fmt.Sprintf("select %s from %s where snow_likes_id = $1 limit 1", likesTweetRows, m.table)
	return conn.QueryRowCtx(ctx, v, query, primary)
}

func (m *defaultLikesTweetModel) tableName() string {
	return m.table
}
