// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.10.1

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/cache"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	likesCommentFieldNames          = builder.RawFieldNames(&LikesComment{}, true)
	likesCommentRows                = strings.Join(likesCommentFieldNames, ",")
	likesCommentRowsExpectAutoSet   = strings.Join(stringx.Remove(likesCommentFieldNames, "create_at", "create_time", "created_at", "update_at", "update_time", "updated_at"), ",")
	likesCommentRowsWithPlaceHolder = builder.PostgreSqlJoin(stringx.Remove(likesCommentFieldNames, "snow_likes_id", "create_at", "create_time", "created_at", "update_at", "update_time", "updated_at"))

	cachePublicLikesCommentSnowLikesIdPrefix = "cache:public:likesComment:snowLikesId:"
)

type (
	likesCommentModel interface {
		Insert(ctx context.Context, data *LikesComment) (sql.Result, error)
		FindOne(ctx context.Context, snowLikesId int64) (*LikesComment, error)
		Update(ctx context.Context, data *LikesComment) error
		Delete(ctx context.Context, snowLikesId int64) error
	}

	defaultLikesCommentModel struct {
		sqlc.CachedConn
		table string
	}

	LikesComment struct {
		SnowLikesId int64 `db:"snow_likes_id"` // 业务ID（前后端主要使用）
		Uid         int64 `db:"uid"`           // 点赞用户ID
		SnowCid     int64 `db:"snow_cid"`      // 评论ID
		CreatedAt   int64 `db:"created_at"`    // 创建时间（毫秒级时间戳）
		UpdatedAt   int64 `db:"updated_at"`    // 更新时间（毫秒级时间戳）
		Status      int64 `db:"status"`        // 状态：1点赞，0取消
	}
)

func newLikesCommentModel(conn sqlx.SqlConn, c cache.CacheConf, opts ...cache.Option) *defaultLikesCommentModel {
	return &defaultLikesCommentModel{
		CachedConn: sqlc.NewConn(conn, c, opts...),
		table:      `"public"."likes_comment"`,
	}
}

func (m *defaultLikesCommentModel) Delete(ctx context.Context, snowLikesId int64) error {
	publicLikesCommentSnowLikesIdKey := fmt.Sprintf("%s%v", cachePublicLikesCommentSnowLikesIdPrefix, snowLikesId)
	_, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("delete from %s where snow_likes_id = $1", m.table)
		return conn.ExecCtx(ctx, query, snowLikesId)
	}, publicLikesCommentSnowLikesIdKey)
	return err
}

func (m *defaultLikesCommentModel) FindOne(ctx context.Context, snowLikesId int64) (*LikesComment, error) {
	publicLikesCommentSnowLikesIdKey := fmt.Sprintf("%s%v", cachePublicLikesCommentSnowLikesIdPrefix, snowLikesId)
	var resp LikesComment
	err := m.QueryRowCtx(ctx, &resp, publicLikesCommentSnowLikesIdKey, func(ctx context.Context, conn sqlx.SqlConn, v any) error {
		query := fmt.Sprintf("select %s from %s where snow_likes_id = $1 limit 1", likesCommentRows, m.table)
		return conn.QueryRowCtx(ctx, v, query, snowLikesId)
	})
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultLikesCommentModel) Insert(ctx context.Context, data *LikesComment) (sql.Result, error) {
	publicLikesCommentSnowLikesIdKey := fmt.Sprintf("%s%v", cachePublicLikesCommentSnowLikesIdPrefix, data.SnowLikesId)
	ret, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("insert into %s (%s) values ($1, $2, $3, $4)", m.table, likesCommentRowsExpectAutoSet)
		return conn.ExecCtx(ctx, query, data.SnowLikesId, data.Uid, data.SnowCid, data.Status)
	}, publicLikesCommentSnowLikesIdKey)
	return ret, err
}

func (m *defaultLikesCommentModel) Update(ctx context.Context, data *LikesComment) error {
	publicLikesCommentSnowLikesIdKey := fmt.Sprintf("%s%v", cachePublicLikesCommentSnowLikesIdPrefix, data.SnowLikesId)
	_, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("update %s set %s where snow_likes_id = $1", m.table, likesCommentRowsWithPlaceHolder)
		return conn.ExecCtx(ctx, query, data.SnowLikesId, data.Uid, data.SnowCid, data.Status)
	}, publicLikesCommentSnowLikesIdKey)
	return err
}

func (m *defaultLikesCommentModel) formatPrimary(primary any) string {
	return fmt.Sprintf("%s%v", cachePublicLikesCommentSnowLikesIdPrefix, primary)
}

func (m *defaultLikesCommentModel) queryPrimary(ctx context.Context, conn sqlx.SqlConn, v, primary any) error {
	query := fmt.Sprintf("select %s from %s where snow_likes_id = $1 limit 1", likesCommentRows, m.table)
	return conn.QueryRowCtx(ctx, v, query, primary)
}

func (m *defaultLikesCommentModel) tableName() string {
	return m.table
}
