// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.10.1

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/cache"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	replyFieldNames          = builder.RawFieldNames(&Reply{}, true)
	replyRows                = strings.Join(replyFieldNames, ",")
	replyRowsExpectAutoSet   = strings.Join(stringx.Remove(replyFieldNames, "create_at", "create_time", "created_at", "update_at", "update_time", "updated_at"), ",")
	replyRowsWithPlaceHolder = builder.PostgreSqlJoin(stringx.Remove(replyFieldNames, "snow_cid", "create_at", "create_time", "created_at", "update_at", "update_time", "updated_at"))

	cachePublicReplySnowCidPrefix = "cache:public:reply:snowCid:"
)

type (
	replyModel interface {
		Insert(ctx context.Context, data *Reply) (sql.Result, error)
		FindOne(ctx context.Context, snowCid int64) (*Reply, error)
		Update(ctx context.Context, data *Reply) error
		Delete(ctx context.Context, snowCid int64) error
	}

	defaultReplyModel struct {
		sqlc.CachedConn
		table string
	}

	Reply struct {
		SnowCid    int64  `db:"snow_cid"` // 业务主键ID（雪花算法）
		Cid        int64  `db:"cid"`
		SnowTid    int64  `db:"snow_tid"`    // 推文ID（雪花算法）
		Uid        int64  `db:"uid"`         // 回复用户ID
		ParentId   int64  `db:"parent_id"`   // 父评论/回复ID（comment 或 reply 的 snow_cid）
		RootId     int64  `db:"root_id"`     // 根评论ID（comment 表的 snow_cid）
		Content    string `db:"content"`     // 回复内容
		LikeCount  int64  `db:"like_count"`  // 点赞数
		ReplyCount int64  `db:"reply_count"` // 回复数
		CreatedAt  int64  `db:"created_at"`  // 创建时间（毫秒级时间戳）
		UpdatedAt  int64  `db:"updated_at"`  // 更新时间（毫秒级时间戳）
		Status     int64  `db:"status"`      // 状态：0正常，1删除，2审核中
	}
)

func newReplyModel(conn sqlx.SqlConn, c cache.CacheConf, opts ...cache.Option) *defaultReplyModel {
	return &defaultReplyModel{
		CachedConn: sqlc.NewConn(conn, c, opts...),
		table:      `"public"."reply"`,
	}
}

func (m *defaultReplyModel) Delete(ctx context.Context, snowCid int64) error {
	publicReplySnowCidKey := fmt.Sprintf("%s%v", cachePublicReplySnowCidPrefix, snowCid)
	_, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("delete from %s where snow_cid = $1", m.table)
		return conn.ExecCtx(ctx, query, snowCid)
	}, publicReplySnowCidKey)
	return err
}

func (m *defaultReplyModel) FindOne(ctx context.Context, snowCid int64) (*Reply, error) {
	publicReplySnowCidKey := fmt.Sprintf("%s%v", cachePublicReplySnowCidPrefix, snowCid)
	var resp Reply
	err := m.QueryRowCtx(ctx, &resp, publicReplySnowCidKey, func(ctx context.Context, conn sqlx.SqlConn, v any) error {
		query := fmt.Sprintf("select %s from %s where snow_cid = $1 limit 1", replyRows, m.table)
		return conn.QueryRowCtx(ctx, v, query, snowCid)
	})
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultReplyModel) Insert(ctx context.Context, data *Reply) (sql.Result, error) {
	publicReplySnowCidKey := fmt.Sprintf("%s%v", cachePublicReplySnowCidPrefix, data.SnowCid)
	ret, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("insert into %s (%s) values ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10)", m.table, replyRowsExpectAutoSet)
		return conn.ExecCtx(ctx, query, data.SnowCid, data.Cid, data.SnowTid, data.Uid, data.ParentId, data.RootId, data.Content, data.LikeCount, data.ReplyCount, data.Status)
	}, publicReplySnowCidKey)
	return ret, err
}

func (m *defaultReplyModel) Update(ctx context.Context, data *Reply) error {
	publicReplySnowCidKey := fmt.Sprintf("%s%v", cachePublicReplySnowCidPrefix, data.SnowCid)
	_, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("update %s set %s where snow_cid = $1", m.table, replyRowsWithPlaceHolder)
		return conn.ExecCtx(ctx, query, data.SnowCid, data.Cid, data.SnowTid, data.Uid, data.ParentId, data.RootId, data.Content, data.LikeCount, data.ReplyCount, data.Status)
	}, publicReplySnowCidKey)
	return err
}

func (m *defaultReplyModel) formatPrimary(primary any) string {
	return fmt.Sprintf("%s%v", cachePublicReplySnowCidPrefix, primary)
}

func (m *defaultReplyModel) queryPrimary(ctx context.Context, conn sqlx.SqlConn, v, primary any) error {
	query := fmt.Sprintf("select %s from %s where snow_cid = $1 limit 1", replyRows, m.table)
	return conn.QueryRowCtx(ctx, v, query, primary)
}

func (m *defaultReplyModel) tableName() string {
	return m.table
}
