// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.10.1

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/cache"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	userLikeSyncFieldNames          = builder.RawFieldNames(&UserLikeSync{}, true)
	userLikeSyncRows                = strings.Join(userLikeSyncFieldNames, ",")
	userLikeSyncRowsExpectAutoSet   = strings.Join(stringx.Remove(userLikeSyncFieldNames, "create_at", "create_time", "created_at", "update_at", "update_time", "updated_at"), ",")
	userLikeSyncRowsWithPlaceHolder = builder.PostgreSqlJoin(stringx.Remove(userLikeSyncFieldNames, "uid", "create_at", "create_time", "created_at", "update_at", "update_time", "updated_at"))

	cachePublicUserLikeSyncUidPrefix = "cache:public:userLikeSync:uid:"
)

type (
	userLikeSyncModel interface {
		Insert(ctx context.Context, data *UserLikeSync) (sql.Result, error)
		FindOne(ctx context.Context, uid int64) (*UserLikeSync, error)
		Update(ctx context.Context, data *UserLikeSync) error
		Delete(ctx context.Context, uid int64) error
	}

	defaultUserLikeSyncModel struct {
		sqlc.CachedConn
		table string
	}

	UserLikeSync struct {
		Uid          int64 `db:"uid"`            // 用户ID（主键）
		LastLikeTime int64 `db:"last_like_time"` // 最后点赞操作时间（毫秒级时间戳），包括点赞推文和点赞评论
	}
)

func newUserLikeSyncModel(conn sqlx.SqlConn, c cache.CacheConf, opts ...cache.Option) *defaultUserLikeSyncModel {
	return &defaultUserLikeSyncModel{
		CachedConn: sqlc.NewConn(conn, c, opts...),
		table:      `"public"."user_like_sync"`,
	}
}

func (m *defaultUserLikeSyncModel) Delete(ctx context.Context, uid int64) error {
	publicUserLikeSyncUidKey := fmt.Sprintf("%s%v", cachePublicUserLikeSyncUidPrefix, uid)
	_, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("delete from %s where uid = $1", m.table)
		return conn.ExecCtx(ctx, query, uid)
	}, publicUserLikeSyncUidKey)
	return err
}

func (m *defaultUserLikeSyncModel) FindOne(ctx context.Context, uid int64) (*UserLikeSync, error) {
	publicUserLikeSyncUidKey := fmt.Sprintf("%s%v", cachePublicUserLikeSyncUidPrefix, uid)
	var resp UserLikeSync
	err := m.QueryRowCtx(ctx, &resp, publicUserLikeSyncUidKey, func(ctx context.Context, conn sqlx.SqlConn, v any) error {
		query := fmt.Sprintf("select %s from %s where uid = $1 limit 1", userLikeSyncRows, m.table)
		return conn.QueryRowCtx(ctx, v, query, uid)
	})
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultUserLikeSyncModel) Insert(ctx context.Context, data *UserLikeSync) (sql.Result, error) {
	publicUserLikeSyncUidKey := fmt.Sprintf("%s%v", cachePublicUserLikeSyncUidPrefix, data.Uid)
	ret, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("insert into %s (%s) values ($1, $2)", m.table, userLikeSyncRowsExpectAutoSet)
		return conn.ExecCtx(ctx, query, data.Uid, data.LastLikeTime)
	}, publicUserLikeSyncUidKey)
	return ret, err
}

func (m *defaultUserLikeSyncModel) Update(ctx context.Context, data *UserLikeSync) error {
	publicUserLikeSyncUidKey := fmt.Sprintf("%s%v", cachePublicUserLikeSyncUidPrefix, data.Uid)
	_, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("update %s set %s where uid = $1", m.table, userLikeSyncRowsWithPlaceHolder)
		return conn.ExecCtx(ctx, query, data.Uid, data.LastLikeTime)
	}, publicUserLikeSyncUidKey)
	return err
}

func (m *defaultUserLikeSyncModel) formatPrimary(primary any) string {
	return fmt.Sprintf("%s%v", cachePublicUserLikeSyncUidPrefix, primary)
}

func (m *defaultUserLikeSyncModel) queryPrimary(ctx context.Context, conn sqlx.SqlConn, v, primary any) error {
	query := fmt.Sprintf("select %s from %s where uid = $1 limit 1", userLikeSyncRows, m.table)
	return conn.QueryRowCtx(ctx, v, query, primary)
}

func (m *defaultUserLikeSyncModel) tableName() string {
	return m.table
}
