// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1

package handler

import (
	"net/http"

	recommend "gozeroX/app/recommendService/cmd/api/internal/handler/recommend"
	"gozeroX/app/recommendService/cmd/api/internal/svc"
	"gozeroX/pkg/jwt"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	jwtMiddleware := jwt.NewJwtMiddleware(serverCtx.Config.Auth.AccessSecret)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/feed",
				Handler: jwtMiddleware.Handle(recommend.FeedHandler(serverCtx)),
			},
		},
		rest.WithPrefix("/recommendService/v1"),
	)
}
