// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1
// Source: noticeService.proto

package server

import (
	"context"

	"gozeroX/app/noticeService/cmd/rpc/internal/logic"
	"gozeroX/app/noticeService/cmd/rpc/internal/svc"
	"gozeroX/app/noticeService/cmd/rpc/pb"
)

type NoticeServer struct {
	svcCtx *svc.ServiceContext
	pb.UnimplementedNoticeServer
}

func NewNoticeServer(svcCtx *svc.ServiceContext) *NoticeServer {
	return &NoticeServer{
		svcCtx: svcCtx,
	}
}

// 获取通知列表（点赞+评论混合）
func (s *NoticeServer) GetNotices(ctx context.Context, in *pb.GetNoticesReq) (*pb.GetNoticesResp, error) {
	l := logic.NewGetNoticesLogic(ctx, s.svcCtx)
	return l.GetNotices(in)
}

// 获取未读通知数
func (s *NoticeServer) GetUnreadCount(ctx context.Context, in *pb.GetUnreadCountReq) (*pb.GetUnreadCountResp, error) {
	l := logic.NewGetUnreadCountLogic(ctx, s.svcCtx)
	return l.GetUnreadCount(in)
}

// 标记通知已读
func (s *NoticeServer) MarkRead(ctx context.Context, in *pb.MarkReadReq) (*pb.MarkReadResp, error) {
	l := logic.NewMarkReadLogic(ctx, s.svcCtx)
	return l.MarkRead(in)
}
