// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2
// Source: interactService.proto

package server

import (
	"context"

	"gozeroX/app/interactService/cmd/rpc/internal/logic"
	"gozeroX/app/interactService/cmd/rpc/internal/svc"
	"gozeroX/app/interactService/cmd/rpc/pb"
)

type InteractionServer struct {
	svcCtx *svc.ServiceContext
	pb.UnimplementedInteractionServer
}

func NewInteractionServer(svcCtx *svc.ServiceContext) *InteractionServer {
	return &InteractionServer{
		svcCtx: svcCtx,
	}
}

// 评论服务（创建、删除评论，获取推文顶级评论区、获取某条评论的回复评论区）
func (s *InteractionServer) CreateComment(ctx context.Context, in *pb.CreateCommentReq) (*pb.CreateCommentResp, error) {
	l := logic.NewCreateCommentLogic(ctx, s.svcCtx)
	return l.CreateComment(in)
}

func (s *InteractionServer) DeleteComment(ctx context.Context, in *pb.DeleteCommentReq) (*pb.DeleteCommentResp, error) {
	l := logic.NewDeleteCommentLogic(ctx, s.svcCtx)
	return l.DeleteComment(in)
}

func (s *InteractionServer) GetComments(ctx context.Context, in *pb.GetCommentsReq) (*pb.GetCommentsResp, error) {
	l := logic.NewGetCommentsLogic(ctx, s.svcCtx)
	return l.GetComments(in)
}

func (s *InteractionServer) GetReplies(ctx context.Context, in *pb.GetRepliesReq) (*pb.GetRepliesResp, error) {
	l := logic.NewGetRepliesLogic(ctx, s.svcCtx)
	return l.GetReplies(in)
}

// 点赞/取消点赞行为
func (s *InteractionServer) LikeTweet(ctx context.Context, in *pb.LikeTweetReq) (*pb.LikeTweetResp, error) {
	l := logic.NewLikeTweetLogic(ctx, s.svcCtx)
	return l.LikeTweet(in)
}

func (s *InteractionServer) LikeComment(ctx context.Context, in *pb.LikeCommentReq) (*pb.LikeCommentResp, error) {
	l := logic.NewLikeCommentLogic(ctx, s.svcCtx)
	return l.LikeComment(in)
}
