// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2
// Source: interactService.proto

package server

import (
	"context"

	"gozeroX/app/interactService/cmd/rpc/internal/logic"
	"gozeroX/app/interactService/cmd/rpc/internal/svc"
	"gozeroX/app/interactService/cmd/rpc/pb"
)

type InteractionServer struct {
	svcCtx *svc.ServiceContext
	pb.UnimplementedInteractionServer
}

func NewInteractionServer(svcCtx *svc.ServiceContext) *InteractionServer {
	return &InteractionServer{
		svcCtx: svcCtx,
	}
}

// 评论服务
func (s *InteractionServer) CreateComment(ctx context.Context, in *pb.CreateCommentReq) (*pb.CreateCommentResp, error) {
	l := logic.NewCreateCommentLogic(ctx, s.svcCtx)
	return l.CreateComment(in)
}

func (s *InteractionServer) DeleteComment(ctx context.Context, in *pb.DeleteCommentReq) (*pb.DeleteCommentResp, error) {
	l := logic.NewDeleteCommentLogic(ctx, s.svcCtx)
	return l.DeleteComment(in)
}

func (s *InteractionServer) GetComments(ctx context.Context, in *pb.GetCommentsReq) (*pb.GetCommentsResp, error) {
	l := logic.NewGetCommentsLogic(ctx, s.svcCtx)
	return l.GetComments(in)
}

func (s *InteractionServer) GetReplies(ctx context.Context, in *pb.GetRepliesReq) (*pb.GetRepliesResp, error) {
	l := logic.NewGetRepliesLogic(ctx, s.svcCtx)
	return l.GetReplies(in)
}

// 点赞服务
func (s *InteractionServer) Like(ctx context.Context, in *pb.LikeReq) (*pb.LikeResp, error) {
	l := logic.NewLikeLogic(ctx, s.svcCtx)
	return l.Like(in)
}

func (s *InteractionServer) GetLikeStatus(ctx context.Context, in *pb.GetLikeStatusReq) (*pb.GetLikeStatusResp, error) {
	l := logic.NewGetLikeStatusLogic(ctx, s.svcCtx)
	return l.GetLikeStatus(in)
}

func (s *InteractionServer) BatchGetLikeStatus(ctx context.Context, in *pb.BatchGetLikeStatusReq) (*pb.BatchGetLikeStatusResp, error) {
	l := logic.NewBatchGetLikeStatusLogic(ctx, s.svcCtx)
	return l.BatchGetLikeStatus(in)
}
